scripts: update clang scan script to use clang version 11.
thesofproject/sof pull request #2768
Opened 2020-04-15 13:44 UTC by zrombel

Update clang-scan-build-xtensa.sh to use clang version 11 explicitly.

2020-04-16 07:32 UTC, zrombel commented
This is the script used by clang on QB. Process Team and @jajanusz agreed on using Clang 11 and I'm updating the script at the request of PT.

2020-04-16 10:53 UTC, lgirdwood commented
> This is the script used by clang on QB. Process Team and @jajanusz agreed on using Clang 11 and I'm updating the script at the request of PT.

ok, we should also update sof-docs for the clang 11 dependency for installation.

2020-04-20 10:51 UTC, jajanusz commented
One thing that we may add is version check in the script, but this name chang to *-11 is not acceptable.

2020-04-20 12:30 UTC, lgirdwood commented
@jajanusz ok, so I guess you never approved the change with process group ? Are we needing a feature in version 11+ ?

2021-02-06 03:56 UTC, gkbldcig commented
Can one of the admins verify this patch?

2021-02-08 11:23 UTC, lgirdwood commented
@marc-hb can you comment here and approve if you think it's good. I'll rerun CI.

2021-02-08 11:23 UTC, lgirdwood commented
SOFCI TEST

2021-02-08 11:24 UTC, lgirdwood commented on scripts/scan/clang-scan-build-xtensa.sh
> +scan-build-11 $VERBOSE_SCAN_BUILD cmake \
I think this maybe better as a shell variable that can by default be "11", but we should have command line option to change it to say a different version.

2021-02-08 17:16 UTC, marc-hb requested changes
This obviously shouldn't be merged as it is  because right now it's breaking the very thing it's supposed to fix.


> This is the script used by clang on QB.

Maybe  it _was_ at the time but now on the 2nd of February https://quickbuild.igk.intel.com/build/6015190 failed like this after 21 seconds:
```
clang-scan-build-xtensa.sh: line 73: scan-build-11: command not found
```


Looking at some other, unrelated and recent PR (3783), the same check was "successful", more precisely https://quickbuild.igk.intel.com/build/6035015 appears green despite failing  like this after 2 minutes
```
Failed to run command:
#!/bin/bash

zip -r FW/GITHUB/PULL_REQUEST/pull-3783-merge_20763/LOGS/CLANG/TGL.zip FW/GITHUB/PULL_REQUEST/pull-3783-merge_20763/LOGS/CLANG/TGL
Command return code: 12
```
At the top of some log file I found this: `clang version 6.0.0-1ubuntu2` (clang v6 was released in 2018)



If this is really needed for some reason then here's a more user-friendly option:

```shell
# Prefer version 11 if available
SCAN_BUILD=scan-build-11
type -p "$SCAN_BUILD" || SCAN_BUILD=scan-build
```

2021-03-28 13:44 UTC, closed without merging

2021-03-29 09:02 UTC, paulstelian97 commented
Please resubmit with "main" as PR base branch.