sof: drc: Fixed-point component implementation
thesofproject/sof pull request #3549
Opened 2020-10-23 09:15 UTC by johnylin76

2020-10-26 20:32 UTC, cujomalainey reviewed
LGTM but really should have @singalsu sign off as most of this fixed point macro math is beyond my knowledge.

2020-10-26 20:32 UTC, cujomalainey commented on src/audio/drc/drc_generic.c
> +#define ONE_Q20        Q_CONVERT_FLOAT(1.0f, 20)                /* Q12.20 */
I would prefer we don't do this with the defines, I don't think we need to name these values. Keep them inline please (unless anyone objects)

2020-10-29 13:53 UTC, lgirdwood reviewed
@johnylin76 can you add some more detail in the commit message but otherwise LGTM.
@singalsu can you take a look here and provide any comments or approval.

2020-10-30 06:25 UTC, johnylin76 commented
> @johnylin76 can you add some more detail in the commit message but otherwise LGTM.

Added, thanks.

2020-10-30 14:05 UTC, singalsu requested changes
Good work with fixed conversion! Please check few issues those I commented.

2020-10-30 14:05 UTC, singalsu commented on src/audio/drc/drc_generic.c
> +				y = audio_stream_read_frag_s32(sink, idx);
Should this be audio_stream_write_frag_s32() and the same for previous function for s24 format?

2020-11-02 20:18 UTC, cujomalainey commented
Also see checkpatch errors

2020-11-03 08:51 UTC, johnylin76 commented on src/audio/drc/drc_math_generic.c
> +inline float warp_sinf(float x)
Thanks. Used sin_fixed instead.

@singalsu Do you consider all other fixed implementation (e.g. asin, lin2db, log...) which are not existing in math library should be moved there?

2020-11-03 16:05 UTC, cujomalainey commented
Still a bunch of checkpatch errors https://sof-ci.01.org/sofpr/PR3549/build7565/checkpatch/

2020-11-04 08:12 UTC, johnylin76 commented
> Still a bunch of checkpatch errors https://sof-ci.01.org/sofpr/PR3549/build7565/checkpatch/

I cleaned up all warnings except the "ABI update" one (don't know what to do for this).
Is it required to clean up "checks" as well?

2020-11-04 09:58 UTC, singalsu commented on src/audio/drc/drc_math_generic.c
> +inline float warp_sinf(float x)
@johnylin76 Yes please, I think those functions are generic and very useful.

2020-11-04 19:02 UTC, cujomalainey commented
The ending in ( line issue should probably be fixed. CamelCase, - macro reuse and - spacing look like they should be ignored.

2020-11-05 04:20 UTC, johnylin76 commented
> The ending in ( line issue should probably be fixed. CamelCase, - macro reuse and - spacing look like they should be ignored.

Fixed checks for "ending in ( line".

2020-11-05 23:18 UTC, lgirdwood approved these changes
@singalsu @cujomalainey please merge when you are good with the PR. It LGTM.

2020-11-06 06:34 UTC, johnylin76 commented
I rebased the PR to upstream due to https://github.com/thesofproject/sof/pull/3581 update.

2020-11-10 07:36 UTC, johnylin76 commented
> @singalsu @cujomalainey please merge when you are good with the PR. It LGTM.

@singalsu @cujomalainey friendly ping :)

2020-11-10 07:57 UTC, cujomalainey commented
Waiting for @singalsu as he is the fixed point master :) Ill check tomorrow and sign off then

2020-11-10 10:26 UTC, singalsu approved these changes
Looks good, thanks @johnylin76 !

2020-11-11 02:38 UTC, merged