ssp: power down on pause
thesofproject/sof pull request #3615
Opened 2020-11-16 15:39 UTC by abonislawski

This patch will turn off ssp when not used and allow to
power down more dsp clocks

Signed-off-by: Adrian Bonislawski <adrian.bonislawski@linux.intel.com>

2020-11-16 16:23 UTC, lgirdwood requested changes
LGTM - Just needs some more comments. Btw any impact with the pause SSP work from @ktrzcinx and @slawblauciak ?

2020-11-16 16:23 UTC, lgirdwood commented on src/drivers/intel/ssp/ssp.c
> +		mn_reg_write(MN_MDIVCTRL, 0, 0);
useful to have an inline comment here stating we are powering off.

2020-11-16 16:23 UTC, lgirdwood commented on src/drivers/intel/ssp/ssp.c
> +		mn_reg_write(MN_MDIVCTRL, 0, 0);
ditto for comment here too, this way its obvious to everyone.

2021-03-28 13:44 UTC, closed without merging

2021-03-29 09:00 UTC, paulstelian97 commented
Is this still needed? If so, please resubmit with "main" as PR base branch.