cavs: clk: correct the WOVCRO attempting logic
thesofproject/sof pull request #3634
Opened 2020-11-23 06:02 UTC by keyonjie

Set CLKCTL_WOV_CRO_REQUEST to request WOVCRO, and fallback to use LPRO
if it is not available, correct the attempting logic here, to address
the random boot fail issue.

Fixes #3633

Signed-off-by: Keyon Jie <yang.jie@linux.intel.com>

2020-11-23 07:43 UTC, ranj063 approved these changes

2020-11-23 10:04 UTC, lgirdwood commented
@zrombel @slawblauciak  I'm seeing this in the CI
```
10:27:48.297   => Post-iteration cleanup
10:27:48.297   => Verification
10:27:48.297     => Topology Iteration 0, Playback Iteration 0
10:27:48.656       Wrong data alignment. Preceding silence size is not multiplicity of the channel format (16 in 17748).

10:27:48.703        BBB value is smaller than acceptable value (0.00) on channel 0: 0.00
```
Do we know why this would impact data alignment ?

2020-11-23 10:06 UTC, lgirdwood approved these changes
@keyonjie can you do a subsequent trace_err() that tells the user what has failed here and the fallback.

2020-11-23 10:14 UTC, abonislawski requested changes
As described on the meeting, SHIM_CLKCTL is not a mistake, we dont want to to use STS - we want only check ability to write WOVCRO bit, this is how stepping is verified on CAVS.

With this version we are disabling WOVCRO at all and LPRO will be used as waiti clock, at least on my test platform, probably idelay not long enough?

2020-11-23 10:39 UTC, lgirdwood commented
> As described on the meeting, SHIM_CLKCTL is not a mistake, we dont want to to use STS - we want only check ability to write WOVCRO bit, this is how stepping is verified on CAVS.
> 
> With this version we are disabling WOVCRO at all and LPRO will be used as waiti clock, at least on my test platform, probably idelay not long enough?

@abonislawski I assume you are trying longer delays ?
@keyonjie good to close this ?

2020-11-24 02:54 UTC, keyonjie commented
let me close this since the boot fail issue is not coming from here, and as @abonislawski commented, checking SHIM_CLKCTL but not SHIM_CLKSTS was intentional.

2020-11-24 02:54 UTC, closed without merging