alloc: pick up allocation start correctly
thesofproject/sof pull request #3647
Opened 2020-11-26 15:42 UTC by lyakh

When allocating multiple buffers the first free buffer might not contain a suitably aligned start address. Skip it instead of allocating it with the others. Also don't add alignment to the allocation size, but find a suitably aligned start address instead.

2020-11-27 08:07 UTC, lyakh commented
SOFCI TEST

2020-11-27 15:19 UTC, lgirdwood requested changes
Needs more comments.

2020-11-27 15:19 UTC, lgirdwood commented on src/lib/alloc.c
> +	for (current = map->first_free, hdr = map->block + current;
Can you comment what we are doing here.

2020-11-27 15:19 UTC, lgirdwood commented on src/lib/alloc.c
> +		if (!found) {
and comment on the action we are taking here.

2020-11-27 15:19 UTC, lgirdwood commented on src/lib/alloc.c
> +	if (map->first_free == start) {
and comment on action here.

2020-12-01 13:28 UTC, lgirdwood commented
Not sure why there is a failure as this seems unrelated but rerun CI to be sure.

2020-12-01 13:28 UTC, lgirdwood commented
SOFCI TEST

2021-01-08 21:24 UTC, lyakh commented
all tests passed!

2021-01-11 16:07 UTC, lgirdwood approved these changes

2021-01-11 16:07 UTC, merged