zephyr: add a cache variable with a rimage configuration path
thesofproject/sof pull request #3733
Opened 2021-01-07 11:30 UTC by lyakh

zephyr needs a path to rimage configuration files, add it to cmake cache. As suggested by @mbolivar-nordic in https://github.com/zephyrproject-rtos/zephyr/pull/31127#discussion_r552916260

2021-01-07 12:09 UTC, lgirdwood requested changes

2021-01-07 12:09 UTC, lgirdwood commented on zephyr/CMakeLists.txt
> +get_filename_component(RIMAGE_CONFIG "../rimage/config" ABSOLUTE)
Can we have an inline comment above the requirement.

2021-01-07 13:25 UTC, lgirdwood approved these changes

2021-01-08 06:50 UTC, lyakh commented
CI failure is unrelated

2021-01-08 10:24 UTC, merged