DSP clock switching refining
thesofproject/sof pull request #3773
Opened 2021-01-22 06:55 UTC by keyonjie

1. add notification event for the clock switching.
2. use the event to notify KPB to start draining.

2021-01-22 15:53 UTC, lgirdwood requested changes
We need to make the clock request a reference count for the "min required frequency", clock can be lowered when there are no users of this frequency to next lowest (and so on).

2021-01-22 15:53 UTC, lgirdwood commented on src/include/sof/lib/clk.h
> +	uint32_t clk_id;
This is getting more complex here, could you add some inline comments for each field here.

2021-01-22 15:53 UTC, lgirdwood commented on src/schedule/ll_schedule.c
> +	if (clk_data->clk_id != sch->domain->clk)
can you comment what we are doing here.

2021-01-22 15:53 UTC, lgirdwood commented on src/audio/kpb.c
> +static void kpb_drain_notify(void *arg, enum notify_id type, void *data)
I think this has to be
```c
pm_runtime_get(clock_id, min_freq);
```
to tell the core this is the min clock we need and then we ```put``` it when we are finished.

2021-03-02 02:41 UTC, keyonjie commented
@lgirdwood @mwasko since our ll_scheduler is using wall clock which actually never change its frequency so no notification is needed, and the notification for KPB looks not an urgent task now, let me close this PR now, we can reopen it if needed in someday.

2021-03-02 02:41 UTC, closed without merging