[skip ci] oss-fuzz/cmake: provide an error message when $ENV{OUT} is missing
thesofproject/sof pull request #3824
Opened 2021-02-05 20:15 UTC by marc-hb

... instead of:
```
  set_target_properties called with incorrect number of arguments
```
A little bit of user-friendliness goes a long way.

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

2021-02-05 20:24 UTC, cujomalainey commented
I should probably add a readme pointing to the oss-fuzz docs on how to build this tool....

2021-02-05 20:24 UTC, cujomalainey approved these changes

2021-02-05 21:17 UTC, cujomalainey requested changes
actually on second thought, can you change this error to "this tool should only be built with oss-fuzz, please refer to oss-fuzz docs". if these vars a missing then it won't work

2021-02-05 22:01 UTC, marc-hb commented
In the context of #3821 I could build not all but most of it before and after #3821 and compare the two without installing any additional software or reading any documentation and I found that useful. I imagine it could be useful for CI to do something similar. I found that #3821 required some changes here only thanks to `git grep`, that's not great.

2021-02-05 23:33 UTC, cujomalainey commented
If this breaks we will get a bug filed to some of us through monorail. This build is very similar to the testbench build so I am not too worried about CI since if testbench breaks, then this will likely break too. Although I think there is some room for de-duping the cmake code across userspace tools that incorporate the firmware as a lib.

2021-02-06 05:21 UTC, marc-hb commented
@cujomalainey I'll let you add the perfect error message / README / any of the above. I really don't know anything about this.

2021-02-06 05:21 UTC, closed without merging

2021-02-08 20:30 UTC, cujomalainey commented
Ack

2021-02-08 23:56 UTC, cujomalainey commented
PR #3830