cavs: clk: simplify the clock switching
thesofproject/sof pull request #3825
Opened 2021-02-07 12:36 UTC by keyonjie

When user requires to do D0I3->D0 switching, double switching will
happen while entering WFI low power mode with today's code, that is
D0I3(WOVCRO) -> D0(HPRO) -> WFI enter (LPRO) -> WFI exit (HPRO).

We can simplify to avoid superfluous WOVCRO -> HPRO switching, only the
D0I3(WOVCRO) -> WFI enter (LPRO) -> WFI exit (HPRO) are needed.

Change as below to for this simplification:

On _waiti(), only check and set if switching to D0I3/lowest clock is
required.
On _wakeup(), update to select D0/highest/HPRO clok if required.

Signed-off-by: Keyon Jie <yang.jie@linux.intel.com>

2021-02-09 13:47 UTC, lgirdwood requested changes

2021-02-09 13:47 UTC, lgirdwood commented on src/platform/intel/cavs/lib/clk.c
> +		*uncached_freq_idx = CPU_HPRO_FREQ_IDX;
uncached_freq_idx must be updated in ```pm_runtime_get(clock, cpu);``` otherwise we get out of sync.

2021-02-12 09:42 UTC, abonislawski commented
This will not work as intended because you cannot process pm gate ipc between waiti enter and wakeup

2021-03-28 13:44 UTC, closed without merging

2021-03-29 08:58 UTC, paulstelian97 commented
Please resubmit with "main" as PR base branch.