ll_schedule: refine to schedule period task no later than half period
thesofproject/sof pull request #3968
Opened 2021-03-29 09:18 UTC by keyonjie

For period task like DMIC/SSP pipeline, starting the first copying too
late may lead to xrun after the DAI is started.

Change to ask for earlier first-time scheduling (not later than half
period) to avoid this kind of issue as more as possible.

Signed-off-by: Keyon Jie <yang.jie@linux.intel.com>

2021-03-29 14:23 UTC, lgirdwood reviewed
Can you describe the problem this is solving ? Are you saying first copy() wrt to IPC trigger is too long ?

2021-03-30 09:32 UTC, keyonjie commented
@lgirdwood this was created aimed to address the issue https://github.com/thesofproject/sof/issues/3939, but since the issue is very difficult to reproduce, let me make this as draft at the moment.

I will create another PR to add some useful information logs about the task scheduling point with ll_scheduler, which will help to capture logs once we hit the issue again.

2021-04-08 13:34 UTC, mwasko commented on src/schedule/ll_schedule.c
> +			offset -= sch->domain->ticks_per_ms * deadline_delay_us;
Based on description I think the intention was to set offset to half period when it is later than half period: offset = sch->domain->ticks_per_ms * deadline_delay_us; not current offset minus half period.

2021-04-08 13:35 UTC, mwasko requested changes
Please check my review comments.

2021-04-08 14:35 UTC, lgirdwood commented
@keyonjie it sound like a race between IPC trigger(start) and the scheduler doing the work ?i.e. is IPC trggier start happens at the start of the scheduler tick then we have to wait upto 1ms for the next tick to do our work (but the DMA and DAI have started ??)

2021-06-07 02:31 UTC, closed without merging