waves: move API headers to correct place.
thesofproject/sof pull request #4016
Opened 2021-04-08 14:30 UTC by lgirdwood

Move the waves headers to the correct directory.

Signed-off-by: Liam Girdwood <liam.r.girdwood@linux.intel.com>

2021-04-08 14:31 UTC, lgirdwood commented
@stolx can you give this a try with your binaries and let us know.

2021-04-08 14:38 UTC, dbaluta approved these changes

2021-04-08 16:58 UTC, stolx commented on src/audio/codec_adapter/CMakeLists.txt
> -target_include_directories(sof PUBLIC ${CMAKE_CURRENT_LIST_DIR}/../../include/sof/audio/codec_adapter/codec/)
SOF with Waves codec will not compile with those changes
as a comment says Waves API folder should be on includes path
new API location is not on includes path
so do not delete this but rather change it to 
`target_include_directories(sof PUBLIC ${CMAKE_CURRENT_LIST_DIR}/../../include/sof/audio/)`
and keep a comment

2021-04-09 07:48 UTC, stolx requested changes
please add folder with MaxxEffect API to path, it wont compile without it 
`target_include_directories(sof PUBLIC ${CMAKE_CURRENT_LIST_DIR}/../../include/sof/audio/)`

2021-04-09 12:50 UTC, lgirdwood commented
@stolx update pushed with your changes applied..

2021-04-09 13:46 UTC, stolx approved these changes

2021-04-09 14:02 UTC, dbaluta approved these changes

2021-04-09 16:01 UTC, cujomalainey approved these changes

2021-04-09 16:01 UTC, cujomalainey commented
Doxygen is known issue, all other CIs are non-informational since this code is not part of CI

2021-04-09 16:01 UTC, merged