ipc4: add fw ready support for ipc4
thesofproject/sof pull request #4091
Opened 2021-04-26 08:40 UTC by RanderWang

Add ipc_boot_complete_msg in ipc3 & ipc4

2021-04-26 14:12 UTC, lgirdwood requested changes
This may have to block on the ipc abstraction being merged. Can you do on top of the ipc4 branch.

2021-04-26 14:12 UTC, lgirdwood commented on src/ipc/handler-ipc4.c
> +int ipc_boot_complete_msg(uint32_t *header, , uint32_t *data)
two commas here.

2021-04-26 14:12 UTC, lgirdwood commented on src/include/sof/ipc/common.h
> +int ipc_boot_complete_msg(uint32_t *header, uint32_t *data);
We should really use the new ```ipc_cmd_hdr``` type here instead of uint32_t.

2021-04-26 18:47 UTC, jgunn0262 commented
@RanderWang I'm assuming there is nothing forcing me to use IPC4 in here ?

2021-04-27 02:00 UTC, RanderWang commented
> @RanderWang I'm assuming there is nothing forcing me to use IPC4 in here ?
we can select it in kconfig

2021-04-27 03:08 UTC, RanderWang commented
wrong branch

2021-04-27 03:08 UTC, closed without merging