dai: add check for NULL pcm converter function
thesofproject/sof pull request #4131
Opened 2021-05-03 18:40 UTC by juimonen

If processing format is restricted from Kconfig there's a possibility of
pcm_converter not having proper conversion function. Thus check for NULL
in dai to avoid crashes.

Signed-off-by: Jaska Uimonen <jaska.uimonen@intel.com>

2021-05-03 19:36 UTC, cujomalainey requested changes
need for capture path as well

2021-05-03 19:38 UTC, cujomalainey commented
> need for capture path as well

with capture path fix the crash is downgraded to IPC errors as expected

2021-05-03 19:48 UTC, juimonen commented
@cujomalainey ok thanks, updated. I'll check the convert issue tomorrow with sof folks... I guess the idea is that you would like the most of the pipeline to be 16 bit -> but convert in dai to dai format (if the dai format needs to be hardcoded to other value)?

2021-05-03 19:52 UTC, cujomalainey commented
Kinda....I was more just fiddling around with configs in hopes to potentially save memory for a large integration.

2021-05-03 19:52 UTC, cujomalainey approved these changes

2021-05-03 21:05 UTC, lgirdwood approved these changes

2021-05-03 21:06 UTC, lgirdwood commented
@kkarask @zrombel @wszypelt looks like a DUT HW failure. Good to merge ?

2021-05-04 09:52 UTC, dbaluta approved these changes

2021-05-04 11:42 UTC, jgunn0262 approved these changes

2021-05-04 15:05 UTC, lgirdwood commented
CI showing DUT HW boot failures but other APL and CML DUTs are passing.

2021-05-04 15:05 UTC, merged