converged: add build_library script required to create loadable library
thesofproject/sof pull request #4226
Opened 2021-05-20 11:25 UTC by bkokoszx

Loadable library contains set of N precompiled loadable modules. In order
to build loadable library, firstly the specific module/modules should be
compiled. Loadable library can be built using build_library.py script
added by this commit. Build_library creates library binmap refills
loadable library template mekafile and invokes it.

This commit also adds lib_config.conf file, which is used by build_library
script and is used for setting proper tools paths.

artifacts/dsp_fw_example_release.xml is a example of attribute file
required by build_library script to calculate loadable library
address.

Signed-off-by: Bartosz Kokoszko <bartoszx.kokoszko@linux.intel.com>

2021-05-20 13:08 UTC, lgirdwood requested changes

2021-05-20 13:08 UTC, lgirdwood commented on .gitignore
> +!converged_sound_open_fw_modules_development/*
This looks like it's in the other PRs too ?

2021-05-20 13:08 UTC, lgirdwood commented on converged_sound_open_fw_modules_development/scripts/build_library.py
> +# SPDX-License-Identifier: BSD-3-Clause
This should be under tools dir.

2021-05-25 14:39 UTC, kv2019i requested changes

2021-05-25 14:39 UTC, kv2019i commented on .gitignore
Maybe sof/modules as the top-level directory name?

2021-05-25 14:39 UTC, kv2019i commented on converged_sound_open_fw_modules_development/scripts/build_library.py
> +INTEL_ADSP_DIR = REPO_PATH / Path("FW/src/intel_adsp/")
This should be made vendor agnostic, or at least mark down places where vendor specific steps need to be taken like in sof/scripts/xtensa-build-all.sh .

2022-04-20 07:01 UTC, sys-pt1s commented
Can one of the admins verify this patch?

2022-04-20 15:41 UTC, kv2019i commented
Almost a year without activity, closing.

2022-04-20 15:41 UTC, closed without merging