topology: fix hdmi pcm id for cnl-rt5682-sdw2
thesofproject/sof pull request #4245
Opened 2021-05-26 02:13 UTC by libinyang

HDMI PCM id should be 5, 6, 7 as described in the
sof-cnl-rt5682-sdw2.m4.

Let's use 5, 6, 7 as the HDMI PCM ID to match the UCM setting.

Signed-off-by: Libin Yang <libin.yang@intel.com>

2021-05-26 12:07 UTC, lgirdwood commented
@plbossart does this align with drivers ?

2021-05-26 15:01 UTC, plbossart approved these changes
that's correct, but I am surprised that this is still used. @libinyang are you testing on UpExtreme with SoundWire?

2021-05-26 19:29 UTC, lgirdwood requested changes
Can you remove the rimage git submodule update here.

2021-05-27 01:32 UTC, libinyang commented
> that's correct, but I am surprised that this is still used. @libinyang are you testing on UpExtreme with SoundWire?

@plbossart I found this issue when I reviewed the UCM to align with the topologies. All soundwire topologies has aligned the HDMI PCM ID's except this one.

2021-05-27 01:37 UTC, libinyang commented
> Can you remove the rimage git submodule update here.

@lgirdwood Thanks for reminder.

2021-05-27 09:53 UTC, lgirdwood approved these changes

2021-05-27 09:54 UTC, merged