topology: switch some SDW topologies to use dynamic pipelines
thesofproject/sof pull request #4253
Opened 2021-05-26 17:17 UTC by ranj063

We've been testing the HDA and some nocodec topologies for a few weeks now. Switch some more now to increase testing coverage.

2021-05-26 18:06 UTC, plbossart requested changes
I'd prefer all SoundWire topologies to be converted in one shot. it'll be easier to validate and find bugs. Everything that has references to ALH should be converted.

2021-05-26 18:06 UTC, plbossart commented on tools/topology/CMakeLists.txt
> +	"sof-cml-rt700\;sof-cml-rt700\;-DCHANNELS=4\;-DPLATFORM=cml\;-DDMICPROC_FILTER1=eq_iir_coef_highpass_40hz_20db_48khz.m4\;-DDMIC16KPROC_FILTER1=eq_iir_coef_highpass_40hz_20db_16khz.m4\;-DDYNAMIC=1"
let's also convert from line 85

2021-05-26 18:06 UTC, plbossart commented on tools/topology/CMakeLists.txt
> +	"sof-cml-rt700\;sof-cml-rt700-2ch\;-DCHANNELS=2\;-DPLATFORM=cml\;-DDMICPROC_FILTER1=eq_iir_coef_highpass_40hz_20db_48khz.m4\;-DDMIC16KPROC_FILTER1=eq_iir_coef_highpass_40hz_20db_16khz.m4\;-DDYNAMIC=
let's also convert until line 103 included.

2021-05-26 18:06 UTC, plbossart commented on tools/topology/CMakeLists.txt
> +	"sof-tgl-rt711-rt1308\;sof-tgl-rt711-rt1308-4ch\;-DCHANNELS=4\;-DEXT_AMP\;-DDMICPROC_FILTER1=eq_iir_coef_highpass_40hz_20db_48khz.m4\;-DDMIC16KPROC_FILTER1=eq_iir_coef_highpass_40hz_20db_16khz.m4\;-
same, let's add lines 119 and 120

2021-05-26 18:23 UTC, ranj063 commented on tools/topology/CMakeLists.txt
> +	"sof-tgl-rt711-rt1308\;sof-tgl-rt711-rt1308-4ch\;-DCHANNELS=4\;-DEXT_AMP\;-DDMICPROC_FILTER1=eq_iir_coef_highpass_40hz_20db_48khz.m4\;-DDMIC16KPROC_FILTER1=eq_iir_coef_highpass_40hz_20db_16khz.m4\;-
All added @plbossart

2021-05-26 19:25 UTC, plbossart commented
since most SoundWire devices are not in the CI farm, we need to ask @fredoh9 and @aiChaoSONG for a dedicated SoundWire 'daily test' with this PR before merging it. Thanks!

2021-05-27 19:39 UTC, plbossart commented
> Merge pending test results.

At this point the results on SoundWire platforms *before* this change are rather problematic so I'd really want to punt until the known issues are fixed.

2021-06-02 05:30 UTC, marc-hb commented
> We've been testing the HDA and some nocodec topologies for a few weeks now.

See regressions in #4199 and #4273

2021-06-03 14:05 UTC, lgirdwood commented
@ranj063 I'm assuming that https://github.com/thesofproject/sof/commit/fcaede7a8710c94a774aa080c425774d517ce43e will fix this ?

2021-06-03 14:09 UTC, ranj063 commented
> @ranj063 I'm assuming that [fcaede7](https://github.com/thesofproject/sof/commit/fcaede7a8710c94a774aa080c425774d517ce43e) will fix this ?

yes that will fix #4199 and I have a kernel fix that will fix #4273. But Im not sure if we'd still have to wait for the other SDW bugs before merging this

2021-06-03 14:13 UTC, plbossart commented
> > @ranj063 I'm assuming that [fcaede7](https://github.com/thesofproject/sof/commit/fcaede7a8710c94a774aa080c425774d517ce43e) will fix this ?
> 
> yes that will fix #4199 and I have a kernel fix that will fix #4273. But Im not sure if we'd still have to wait for the other SDW bugs before merging this

yes, no SoundWire changes until we are back to normal in the daily tests, thanks!

2021-06-03 14:15 UTC, lgirdwood commented
> > @ranj063 I'm assuming that [fcaede7](https://github.com/thesofproject/sof/commit/fcaede7a8710c94a774aa080c425774d517ce43e) will fix this ?
> 
> yes that will fix #4199 and I have a kernel fix that will fix #4273. But Im not sure if we'd still have to wait for the other SDW bugs before merging this

Are these known SDW bugs or yet to be discovered ? i.e. would merging this now expose the bugs since we have time before v1.9. 

@plbossart are you happy to merge or do you have pending SDW issues to fix first for SDW stability?

2021-06-03 14:21 UTC, ranj063 commented
> Are these known SDW bugs or yet to be discovered ? i.e. would merging this now expose the bugs since we have time before v1.9.

these are known bugs today. But the reason I want to enable dynamic pipelines on these is to expose new bugs that it might bring before 1.9

2021-06-03 14:51 UTC, plbossart commented
> > Are these known SDW bugs or yet to be discovered ? i.e. would merging this now expose the bugs since we have time before v1.9.
> 
> these are known bugs today. But the reason I want to enable dynamic pipelines on these is to expose new bugs that it might bring before 1.9

@ranj063 @fredoh9 we need to have a dedicated test run for this PR, i asked for this 8 days ago :-)

2021-06-03 15:13 UTC, lgirdwood commented
> @ranj063 @fredoh9 we need to have a dedicated test run for this PR, i asked for this 8 days ago :-)

Ah, great. :) @fredoh9 are you doing this or maybe @XiaoyunWu6666  ?

2021-06-03 16:20 UTC, fredoh9 commented
internal daily test 4364 is triggered with kernel topic/sof-dev tip
`20cf8377 fixup! ASoC: SOF: Don't set up widgets during topology parsing`

2021-06-08 15:39 UTC, lgirdwood commented
@fredoh9 @ranj063 are we good to merge or blocking on tests passing ?

2021-06-08 16:34 UTC, ranj063 commented
> @fredoh9 @ranj063 are we good to merge or blocking on tests passing ?

@lgirdwood not ready yet. SDW issues are still being worked upon. Lets hold off merging this for another 2-3 days until daily tests stabilize

2021-11-30 19:24 UTC, plbossart commented
@ranj063 this one should be updated, we should really have all the HDAudio, SoundWire and nocodec topologies used with DYNAMIC pipelines.

2021-12-01 09:37 UTC, lgirdwood commented
> @ranj063 this one should be updated, we should really have all the HDAudio, SoundWire and nocodec topologies used with DYNAMIC pipelines.

Ack - a good v2.1 feature :)

2022-04-20 07:00 UTC, sys-pt1s commented
Can one of the admins verify this patch?

2022-04-20 18:29 UTC, lgirdwood commented
@plbossart @ranj063 any blockers for this now ?

2022-04-20 18:47 UTC, plbossart commented
@lgirdwood @ranj063 @marc-hb I don't think we should change topologies, it could very well be that they end-up being used with a kernel that's too old. We've already seen this problem with HDaudio.

I think we need to enable dynamic pipelines in our CI tests though, so maybe this needs to be combined with the deep-buffer changes I suggested, that way we test the latest and greatest topologies but we don't impact existing end-user setups.

Alternatively, we can use a kernel parameter to force all topologies used by CI to be dynamic, which means there is no need to change files one by one.

2022-04-20 18:58 UTC, lgirdwood commented
> @lgirdwood @ranj063 @marc-hb I don't think we should change topologies, it could very well be that they end-up being used with a kernel that's too old. We've already seen this problem with HDaudio.
> 
> I think we need to enable dynamic pipelines in our CI tests though, so maybe this needs to be combined with the deep-buffer changes I suggested, that way we test the latest and greatest topologies but we don't impact existing end-user setups.
> 
> Alternatively, we can use a kernel parameter to force all topologies used by CI to be dynamic, which means there is no need to change files one by one.

Ok, will close this so that SDW can be folded into the CI at first and changes can be tested incrementally..

2022-04-20 18:58 UTC, closed without merging