topology: revert apl-nocodec to static pipelines for now
thesofproject/sof pull request #4273
Opened 2021-06-02 04:59 UTC by marc-hb

This partial, apl-nocodec only revert of commit 426d7816e265 ("topology:
nocodec: switch to dynamic pipelines") solves the `aplay:
set_params:1432: Unable to install hw params:` failure described below.

According to Xiaoyun, it also fixes #4199. This regression has been
opened for more than 2 weeks now.

Note `-DDYNAMIC=0` produces the same output as `-DDYNAMIC=1`. Bug or
feature?

Reproduction steps:

- Unload and reload the drivers with sof-test/tools/kmod/

- Turn off Power Management as described in sof-docs. Long story short:
```shell
  find /sys/devices/pci0000:00/0000:00:0e.0 -name control |
        while read -r; do echo on | sudo tee "$REPLY" > /dev/null
  done
```
- sof-test/test-case/check-playback.sh -d 1 -l 1
```
  aplay   -Dhw:0,1 -r 48000 -c 2 -f S16_LE -d 1 /dev/zero -v -q
  aplay: set_params:1432: Unable to install hw params:
```
Trace shows `ERROR ipc: comp X pipeline not found`

Notes:

- aplay seems to fail only once per pipeline. After failing the first
  time, each pipeline seems to be working fine.

- Turning off power management seems required.

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

2021-06-02 06:28 UTC, ranj063 commented
@marc-hb what are the odds somebody will fix these issues if you revert dynamic pipelines for this tplg? If we really want to show a green, can you please escalate the priority for the bug instead?

2021-06-02 09:58 UTC, kv2019i requested changes
Let's try to address this via priorities. The affected bug did not have any priority set and nobody was assigned to fix it. I now tagged it as P1 and assigned it to someone. If it still remains open, then we can consider reverting, but let's try. We had to back down from dynamic pipelines already for 1.8 and I think same will happen for 1.9 unless we fix the issues.

2021-06-02 12:54 UTC, plbossart approved these changes
I highlighted validation issues last week, nothing happened.
I have no issue with reverting a single commit that clearly needs more time.

2021-06-02 14:06 UTC, marc-hb commented
> I have no issue with reverting a single commit that clearly needs more time.

It's even less than a single commit BTW: it's only one line / one platform from it.

2021-06-02 16:23 UTC, ranj063 commented
Please dont merge this. I am close to finding a fix for #4199

2021-06-02 19:10 UTC, marc-hb commented
After an intense pair-debugging session with @ranj063 (thanks!) where she could desperately not reproduce I found this critical reproduction requirement, which I just added to the description (not to the commit message):

- Insert the drivers and REQUIRED: turn off Power Management [as described in sof-docs](https://thesofproject.github.io/latest/developer_guides/debugability/logger/index.html)

```
sof-test/tools/kmod/sof_insert.sh && echo on |  sudo tee /sys/devices/pci0000:00/0000:00:0e.0/power/control 
```

EDIT+ WARNING: all the above must be on the same line NOT to give the DSP time to be suspended which happens after a couple seconds. Tip: `journalctl -f -p 7 -g 'DSP'`

In other words this bug reproduces *only on the very first DSP boot.*

2021-06-02 19:12 UTC, marc-hb commented
> Please dont merge this. I am close to finding a fix for #4199

I tested #4282 and it does fix #4199 in my local testing but it does _not_ fix this here.

2021-06-02 19:21 UTC, ranj063 commented
@marc-hb I think it is an artificial bug caused due to timing issues between sof_insert and disabling PM while during sof_insert.

sof-test/tools/kmod/sof_insert.sh && echo on |  sudo tee /sys/devices/pci0000:00/0000:00:0e.0/power/control 

@plbossart do you think we should worry about this?

2021-06-02 19:32 UTC, marc-hb commented
This PR is turning into a bug, I will do a bit more testing and file a new bug later. It will probably be called something like "dynamic topologies now require one initial D3 suspend cycle"

2021-06-03 03:35 UTC, ranj063 commented
> This PR is turning into a bug, I will do a bit more testing and file a new bug later. It will probably be called something like "dynamic topologies now require one initial D3 suspend cycle"

here's the fix for the problem https://github.com/thesofproject/linux/pull/2964

2021-06-08 16:13 UTC, lgirdwood commented
@marc-hb any update here ? I guess we have some recent fixes merged now so is this issue fixed for you ?

2021-06-09 17:23 UTC, marc-hb commented
> here's the fix for the problem thesofproject/linux#2964

I cherry-picked this and fix confirmed, thanks!

2021-06-09 17:23 UTC, closed without merging

2021-06-09 17:45 UTC, marc-hb commented
> @marc-hb any update here ? I guess we have some recent fixes merged now so is this issue fixed for you ?

I downgraded this PR to a github draft when @ranj063 announced a fix. Drafts appear grey instead of green, that's a bit too subtle, next time I'll add a `[DRAFT]` prefix. There's also the very useful:

https://github.com/thesofproject/sof/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse

2021-06-18 05:04 UTC, marc-hb commented
Was re-submitted and merged in commit 5b072d97d5 / PR #4323