scripts: xtensa-build-all: remove unsupported platforms
thesofproject/sof pull request #4291
Opened 2021-06-03 20:22 UTC by ranj063

SLK/KBL/HSW/SUE are no longer supported. Remove support
for building these using the script.

Signed-off-by: Ranjani Sridharan <ranjani.sridharan@linux.intel.com>

2021-06-03 20:25 UTC, plbossart approved these changes
need to remove the code/makefiles as well...

2021-06-04 00:52 UTC, fredoh9 approved these changes
Looks good.
I updated jenkins build template also.

2021-06-04 00:52 UTC, fredoh9 commented
SOFCI TEST

2021-06-04 01:03 UTC, fredoh9 commented
SOFCI TEST

2021-06-04 01:19 UTC, marc-hb reviewed
These still build and even boot in QEMU so I wonder what motivates this, saving time when running `xtensa-build-all.sh -a` maybe? There's no reason to use the `-a` option anymore, the `installer/` lets you select which platforms you want to build and it can build all platforms in parallel with `-j` (all platforms in less than 20s on my not very fast system). In fact the `installer/` does already NOT build these (but it can)

BTW there are also references to skylake and others in `tools/topology/`, in `src/arch/xtensa/configs/` and there is even an entire `src/platform/suecreek` directory, why keep those? Obsolete source code seems more likely to get in the way of maintenance and refactorings than this top-level script.

2021-06-04 01:41 UTC, keyonjie commented
yes, what is the motivation here @ranj063 ?

2021-06-04 03:46 UTC, ranj063 commented
> yes, what is the motivation here @ranj063 ?

what is the motivation to keep dead code @keyonjie @marc-hb. Its not like we can ever test these can we?
And this is just the start, I filed an issue to actually remove the source code as well: https://github.com/thesofproject/sof/issues/4292

2021-06-04 05:36 UTC, marc-hb requested changes
> what is the motivation to keep dead code @keyonjie @marc-hb.

Nice try but we didn't submit any PR to preserve dead code :-) So what is the motivation for this PR, what difference does it make?

If this only about speeding up `./xtensa-build-all.sh -a` then changing the first line is enough (or 10 times faster: use the parallel `installer/`)

> Its not like we can ever test these can we?

Some of these still boots in QEMU and they all build in CI so this code is not really "dead", I mean it does not bitrot. I understand they're neither officially supported nor hardware tested but how about hobbyists? SKL and KBL are not even very old products, I'm typing this on a SKL system right now.

One of the things we really miss in CI is some randconfig testing (last I checked on kconfig.py does not support randconfig). Have multiple platforms with defconfig variations is far from randconfig but it's better than nothing. BTW I'm actually pushing this even further locally: to make sure different CONFIG_ variations all compile I'm tweaking the _defconfig of some random platforms.

Here's an example where compiling unsupported suecreek provided more "compilation coverage": https://github.com/thesofproject/sof/pull/3747

You can never have too much coverage.

> And this is just the start, I filed an issue to actually remove the source code as well: #4292

Sorry but I don't see the point of removing only the tiny bits of shell script that have not changed in ages and cost zero maintenance effort while postponing to an undefined date the harder and more likely valuable work: removal of the "real", platform specific code that could actually speed up some hypothetical refactoring. That makes the code "really dead" without removing it and the codebase inconsistent.

2022-04-20 07:00 UTC, sys-pt1s commented
Can one of the admins verify this patch?

2022-04-20 15:49 UTC, kv2019i commented
@ranj063 @marc-hb Any conclusion on this? This has been stuck since June last year.

2022-04-20 16:07 UTC, marc-hb commented
My opinion has not changed: if removing a platform helps simplify the code, then remove that platform _when the code is actually getting simplified_. Removing a platform without simplifying the code is just losing some poor man's `randconfig` coverage for no value.

2022-10-13 09:37 UTC, kv2019i commented
No updates in half a year, closing.

2022-10-13 09:37 UTC, closed without merging