Prepare for building Topology2.0 topologies
thesofproject/sof pull request #4363
Opened 2021-06-16 18:50 UTC by ranj063

In preparation for Topology2.0, move the current topology files
to the topology1 folder and once the 1.0 topologies are
built copy them to the /sof/tools/build-tools/topology folder.

When Topology2.0 topologies come along, they will be built into
the topology2 folder and the 2.0 binaries will be copied over
the 1.0 binaries.

2021-06-16 20:01 UTC, lgirdwood approved these changes
I guess the build scripts wont need updated as changes will be incorporated in the makefiles ?

2021-06-16 21:23 UTC, lgirdwood commented
@ranj063 I've finished merging for tonight - good time to fix the conflicts now :)

2021-06-17 04:52 UTC, ranj063 commented
> @ranj063 I've finished merging for tonight - good time to fix the conflicts now :)

@lgirdwood, i've fixed the conflicts now but there are a bunch of topology PR's pending. Should we merge those before merging this?

2021-06-17 06:05 UTC, marc-hb requested changes
Main issue is the "fake?" final_output.tplg file, other comments below.

2021-06-17 06:05 UTC, marc-hb commented on tools/topology/topology1/CMakeLists.txt
> +		OUTPUT final_${output}.tplg
This looks like lying to CMake because the COMMAND does not create any `final_${output}.tplg` file.

2021-06-17 14:37 UTC, ranj063 commented on tools/topology/topology1/CMakeLists.txt
> +)
I cant do that. The outout ofthe get_abi.sh script is different for topology1 and topology2

2021-06-17 14:58 UTC, ranj063 commented on tools/topology/topology1/CMakeLists.txt
> +		COMMAND cp ${CMAKE_CURRENT_BINARY_DIR}/${output}.tplg ${CMAKE_CURRENT_BINARY_DIR}/..
done. thanks!

2021-06-17 16:56 UTC, marc-hb reviewed
Logic looks good. Sorry for nit-picking on the code style and symbol names but it's not like we have many full-time CMake experts in the project (none?) so reducing cognitive strain makes a significant difference.

2021-06-17 16:56 UTC, marc-hb commented on tools/topology/topology1/CMakeLists.txt
> +)
Should this be renamed to `abi_v1` then? Just wondering. Sorry I forgot again what is the purpose of this, I mean which ABI it is. Add a comment?

2021-06-17 16:56 UTC, marc-hb commented on tools/topology/topology1/CMakeLists.txt
> +	add_dependencies(topologies1_output topologies1_${output})
The previous code used singular "topology" for a single file and plural "topologies" for the target that depends on them all. I think this made it very clear that the `add_dependencies(topologies topology_${i})` line is growing a list, even for people who don't know anything about CMake. Can you please preserve that?

2021-06-17 16:56 UTC, marc-hb commented on tools/topology/topology1/CMakeLists.txt
> +    DEPENDS topologies1_output
I find the names `topologies1_output` and `topologies1` not very clear. How about:
```
add_custom_target(topologies1 ALL)
add_custom_target(topologies1_copy ALL
   COMMAND copy_directory
```
End users should rarely ever invoke "make topologies1" directly. The very few who do should know what they're doing.

Or even simpler, have you tried to combine these two into a single `add_custom_target`? Shorter code and naming issue goes away

```
add_custom(topologies1 ALL
          COMMAND copy_directory...
...
)
...
add_dependencies(topologies1 topology1_${output})
```
The dependencies are obviously built before the COMMAND is run.

2021-06-17 17:50 UTC, ranj063 commented
> Logic looks good. Sorry for nit-picking on the code style and symbol names but it's not like we have many full-time CMake experts in the project (none?) so reducing cognitive strain makes a significant difference.

fixed now. Thanks for your help!

2021-06-17 18:00 UTC, ranj063 commented on tools/topology/topology1/CMakeLists.txt
> +)
ther's only one ABI and its for the firmware. What should I say in the comment? that this is the firmware ABI?

2021-06-17 18:33 UTC, marc-hb approved these changes

2021-06-17 18:33 UTC, marc-hb commented on tools/topology/topology1/CMakeLists.txt
> +)
Two different formats for the same ABI, got it thanks for your patience.

2021-06-17 21:17 UTC, lgirdwood commented
CI showing unrelated failure.

2021-06-17 21:17 UTC, merged

2021-12-10 18:11 UTC, marc-hb commented on tools/topology/topology1/CMakeLists.txt
> +		COMMAND cp ${CMAKE_CURRENT_BINARY_DIR}/${output}.tplg ${CMAKE_CURRENT_BINARY_DIR}/..
Just learned the really hard way this is racing with the build of development topologies: #5067