ipc4: add fw_reg definition
thesofproject/sof pull request #4454
Opened 2021-07-06 09:03 UTC by RanderWang

fw_reg is located in memory windows 0 for host to
query fw status

Signed-off-by: Rander Wang <rander.wang@intel.com>

2021-07-07 14:51 UTC, lgirdwood requested changes

2021-07-07 14:51 UTC, lgirdwood commented on src/platform/tigerlake/include/platform/lib/dma.h
> +#define GP_DMA_ENGING_COUNT	2
We already have a macro for number of DW DMA and HDA DMA engines.

2021-07-07 14:51 UTC, lgirdwood commented on src/include/ipc4/fw_reg.h
> +#define PV_MAX_SUPPORTED_CHANNELS 8
needs IPC4_ prefix

2021-07-07 14:51 UTC, lgirdwood commented on src/include/ipc4/fw_reg.h
> +struct FwRegisters {
code style

2021-07-07 14:51 UTC, lgirdwood commented on src/include/ipc4/fw_reg.h
> +	uint32_t full;
Do we need the full members in each struct/union ?

2021-07-08 04:48 UTC, RanderWang commented
update PR, thanks!

2021-07-08 20:36 UTC, lgirdwood approved these changes

2021-07-08 20:37 UTC, merged

2021-07-08 20:38 UTC, lgirdwood commented
@RanderWang can you work on upstreaming more of this branch now. Feel free to create a new branch e.g. topic/ipc4 where you can rebase this code into a sequence of patches for fundamental IPC4 protocol in v1.9

2021-07-09 02:38 UTC, RanderWang commented
> @RanderWang can you work on upstreaming more of this branch now. Feel free to create a new branch e.g. topic/ipc4 where you can rebase this code into a sequence of patches for fundamental IPC4 protocol in v1.9

sure