sof-tgl-sdw-max98373-rt5682: remove 3rd party dependency + BT offload
thesofproject/sof pull request #4637
Opened 2021-08-13 21:45 UTC by fredoh9

1st commit to use a mockup of the smart amp

for 2nd commit, BT offload is not working on TGL Voxel I2S. I don't think BT offload is ready for TGL.

sof-tgl-sdw-max98373-rt5682.m4 uses BT offload when platform is ADL.
https://github.com/thesofproject/sof/blob/6713cace3586115c82dd18a111b63d6f4cd4b435/tools/topology/topology1/sof-tgl-sdw-max98373-rt5682.m4#L57

This is error message when I tested on TGL Voxel.
```
# for playback
2021-08-13 20:08:39 UTC [COMMAND] aplay   -Dhw:0,6 -r 8000 -c 1 -f S16_LE -d 5 /dev/zero -v -q
aplay: set_params:1432: Unable to install hw params:

[  116.834656] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[  116.835013] sof-audio-pci-intel-tgl 0000:00:1f.3: error: ipc error for 0x60010000 size 20
[  116.835115] sof-audio-pci-intel-tgl 0000:00:1f.3: error: hw params ipc failed for stream 1
[  116.835121] sof-audio-pci-intel-tgl 0000:00:1f.3: ASoC: error at snd_soc_pcm_component_hw_params on 0000:00:1f.3: -22
[  116.835130]  Bluetooth: ASoC: soc_pcm_hw_params() failed (-22)
[  116.835152] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[  116.835679] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
[  116.835689]  Bluetooth: ASoC: dpcm_fe_dai_hw_params failed (-22)

# for capture
2021-08-13 20:09:56 UTC [COMMAND] arecord   -Dhw:0,6 -r 8000 -c 1 -f S16_LE -d 5 /dev/null -v -q
Hardware PCM card 0 'sof-rt5682' device 6 subdevice 0
...
arecord: pcm_read:2178: read error: Input/output error
```

2021-08-13 21:50 UTC, plbossart approved these changes
Both changes LGTM, but @kv2019i and @keyonjie must review.

2021-08-16 08:12 UTC, lgirdwood commented
@fredoh9 is the first commit a testing UUID or the real UUID for the Maxim smart amp ?
It also seems the PCM6 pipeline or SSP endpoint is not configured for the BT rate or channels in topology. @juimonen any comment.

2021-08-16 14:48 UTC, kv2019i requested changes
Hmm, this is basicly revert @yongzhi1 's patch "topology: adl-sdw-max98373-rt5682: Add BT offload support" , so I'd like a bit more discussion and ack from @yongzhi1 before we revert. The TGL Chromebooks have capability for BT offload, but it's not yet enabled in coreboot. We enabled in the machine driver as it did not seem to cause harm to non-BT usage.

So is the main problem here failures in sof-test when it tries to go through all PCMs, right?

2021-08-16 16:41 UTC, fredoh9 commented
> @fredoh9 is the first commit a testing UUID or the real UUID for the Maxim smart amp ?

I'm removing real UUID for for the Maxim smart amp. If SMART_UUID is not defined, sof/pipe-smart-amplifier-playback.m4 will use a SOF mockup of the smart amp.

2021-08-16 16:42 UTC, fredoh9 commented
@kv2019i that's right, sof-test will try to go through all the PCM, but BT offload PCMs are failed. I already had a short chat with @yongzhi1 in last week. @yongzhi1 can you comment?

2021-08-16 17:23 UTC, plbossart commented
> @kv2019i that's right, sof-test will try to go through all the PCM, but BT offload PCMs are failed. I already had a short chat with @yongzhi1 in last week. @yongzhi1 can you comment?

what exactly fails @fredoh9 ? The BT case is a 'nocodec' mode, there is no management of the BT chip through ALSA so things should 'just work'.

2021-08-16 17:49 UTC, fredoh9 commented
> what exactly fails @fredoh9 ? The BT case is a 'nocodec' mode, there is no management of the BT chip through ALSA so things should 'just work'.

The failure logs are in pr description. For playback setting hw params failed. For capture, input/output error.

2021-08-16 18:53 UTC, plbossart commented
> > what exactly fails @fredoh9 ? The BT case is a 'nocodec' mode, there is no management of the BT chip through ALSA so things should 'just work'.
> 
> The failure logs are in pr description. For playback setting hw params failed. For capture, input/output error.

probably a case of the topology being wrong  then. Removing it altogether seems a bit extreme, there is really nothing 3rd party or proprietary for this path.

2021-08-17 16:07 UTC, lgirdwood commented
> > @fredoh9 is the first commit a testing UUID or the real UUID for the Maxim smart amp ?
> 
> I'm removing real UUID for for the Maxim smart amp. If SMART_UUID is not defined, sof/pipe-smart-amplifier-playback.m4 will use a SOF mockup of the smart amp.

But what about users with the smart AMP ? Is this intended for CI ? Sorry, not following the CI requirements.

2021-08-17 17:05 UTC, plbossart commented
> > > @fredoh9 is the first commit a testing UUID or the real UUID for the Maxim smart amp ?
> > 
> > 
> > I'm removing real UUID for for the Maxim smart amp. If SMART_UUID is not defined, sof/pipe-smart-amplifier-playback.m4 will use a SOF mockup of the smart amp.
> 
> But what about users with the smart AMP ? Is this intended for CI ? Sorry, not following the CI requirements.

@lgirdwood the public topology uses a mockup of the smartamp module, that's what is used in CI and what would be used if you install sof-bin on a Chromebook with ubuntu. OEMs can enable the actual smart-amp module by compiling it in the firmware and making a reference to it by changing the UUID of the component used in topology.

2021-08-17 19:30 UTC, lgirdwood commented
> @lgirdwood the public topology uses a mockup of the smartamp module, that's what is used in CI and what would be used if you install sof-bin on a Chromebook with ubuntu. OEMs can enable the actual smart-amp module by compiling it in the firmware and making a reference to it by changing the UUID of the component used in topology.

I'm fine with this for CI, but we seem to have a fiddle everytime someone wants to use the real UUID. Can we not have a ```make -DUSE_MOCK_CI_MODULES topology``` that would use the mock UUIDs and leave the real ones intact.

2021-08-17 19:34 UTC, plbossart commented
> > @lgirdwood the public topology uses a mockup of the smartamp module, that's what is used in CI and what would be used if you install sof-bin on a Chromebook with ubuntu. OEMs can enable the actual smart-amp module by compiling it in the firmware and making a reference to it by changing the UUID of the component used in topology.
> 
> I'm fine with this for CI, but we seem to have a fiddle everytime someone wants to use the real UUID. Can we not have a `make -DUSE_MOCK_CI_MODULES topology` that would use the mock UUIDs and leave the real ones intact.

Well, the OEM needs to recompile the firmware anyways using their own tree. We do not have those libraries in the public tree so the default has to be the mockup, and the OEM recompiles, not the other way around.

2021-08-17 20:49 UTC, fredoh9 commented
I dropped 2nd patch for removing BT offload, I can skip BT offload PCM.

2021-08-18 12:10 UTC, lgirdwood approved these changes

2021-08-18 12:10 UTC, merged