zephyr: Use upstream core startup API
thesofproject/sof pull request #4726
Opened 2021-09-07 15:51 UTC by andyross

The original Zephyr version of arch_cpu_enable_core() duplicated logic
internal to the Zephyr SMP layer.  This is now exposed as an internal
API that is more easily testable upstream.  Use that instead.

Signed-off-by: Andy Ross <andrew.j.ross@intel.com>

2021-09-07 15:52 UTC, andyross commented
Submitted as example code, really.  I don't have the ability to run true multicore SOF tests on my hardware, I can only get as far as initialization (which seems to work for me fine on TGL).  But this is the "supported" Zephyr runtime smp startup mechanism, and as of today there's an upstream test in review for it, at least.

2021-09-07 16:16 UTC, andyross commented
Sorry, I think I had mentioned this verbally or via chat, but to call it out explicitly:

This patch removes a call to pm_runtime_get() in the original code.  I don't know if that's correct or not, honestly.  My brief read is that this code is entirely driver-level in SOF and responsible only for hardware stuff the Zephyr code is now doing.  If that's not correct, it's surely going to break something.

Also: note that this currently needs https://github.com/zephyrproject-rtos/zephyr/pull/38319 applied to Zephyr because of a build glitch (though we could fix and merge that separately from the cleanup PR).

2021-09-07 16:20 UTC, kv2019i reviewed
Build error still, but otherwise looks good.

2021-09-07 16:20 UTC, kv2019i commented on zephyr/wrapper.c
> +	z_smp_start_cpu(id);
The pm_runtime_get() is a bit worrisome, but I went (again) through the actions on e.g. sof/src/platform/intel/cavs/lib/pm_runtime.c and it does seem that it's all replaced by Zephyr core management.

One thing I noticed is that src/platform/intel/cavs/platform.c:platform_boot_complete() is powering up the last core on TGL, and uses this pm_runtime_get() to do it (with bit PWRD_BY_HPRO). I think to preserve these on Zephyr, we'd need to provide wrapping from pm_runtime_get() -> calls to z_smp_start_cpu(). But that's not really business of this PR.

2021-09-07 16:55 UTC, andyross commented
FWIW: I split the Zephyr build fix out separately as a single patch in https://github.com/zephyrproject-rtos/zephyr/pull/38368 , which might have a chance of merging during the current release cycle (it's definitely a bug fix).

2021-09-07 19:28 UTC, lgirdwood reviewed
Seeing code removal in the wrapper is good to see (as the wrapper will one day completely evaporate).
@kv2019i re the PM call, I assume this is for powering On/OFF cores and we are using this elsewhere in SOF today (using ref count) ? 
@andyross we can get this in for v1.9, but will need to get our Zephyr CI back up and building before we merge.

2021-09-08 15:08 UTC, andyross commented
FWIW: the Zephyr build fix merged, so this should be able to build successfully against current main.  I don't know how to kick the CI in SOF though.

2021-09-08 17:23 UTC, lgirdwood commented
SOFCI TEST

2021-09-08 17:24 UTC, lgirdwood commented
> FWIW: the Zephyr build fix merged, so this should be able to build successfully against current main. I don't know how to kick the CI in SOF though.

With the command above :)

2021-09-08 19:21 UTC, lgirdwood commented
@andyross this may need rebased on HEAD  and forced pushed to pick up the Zephyr fixed that's now merged.

2021-09-09 16:11 UTC, kv2019i requested changes
Hmm, I was testing your adsp cleanup patch to Zephyr git, but kept getting failures with multitcore TPLG on TGL. It turns out it was this patch that causes the the CORE_ENABLE IPC to fail.

Not sure what's happening, but I'll log a minus so this doesn't get merged before we understsand the failure.

2021-09-09 18:02 UTC, andyross commented
Seems not unlikely that the SOF pm call is doing something to en/disable/whatever the IPC interrupt?  Or scheduling/not-scheduling a task that changes CPU assignments?   This is sort of what I was worried about.

Would be worth trying to add just that one line back, though I'd be afraid of other interactions given it's duplicating a lot of hardware interfacing that Zephyr is now doing.

Note that Zephyr has no IPC driver right now, so all masking and management is happening in SOF exclusively.  We should probably migrate that driver first...

2021-09-09 19:36 UTC, lgirdwood commented
> Note that Zephyr has no IPC driver right now, so all masking and management is happening in SOF exclusively. We should probably migrate that driver first...

Zephyr has the CAVS v1.5 IPC IIRC, I think I've discussed with @dcpleung in the past. We need to keep the current v1.5 code and add in the differences for v1.8 - v2.5 (same IP). I dont think it's too big a job since the interface is in place already.

2022-01-20 16:39 UTC, andyross commented
Ancient.  Close.

2022-01-20 16:39 UTC, closed without merging