pipeline: remove heap status dumps from pipeline code
thesofproject/sof pull request #4744
Opened 2021-09-10 08:11 UTC by lyakh

With dynamic pipelines, pipelines can be created and destroyed often enough at runtime, which makes dumping heap statue for each such action too noisy.

2021-09-10 11:09 UTC, lgirdwood requested changes
We need this atm for debug with allocator, I think its a debug option though which you could turn off.

2021-09-10 12:23 UTC, lyakh commented
> We need this atm for debug with allocator, I think its a debug option though which you could turn off.

@lgirdwood Don't think I've enabled any additional debug options, I think it's printed in default configuration. But sure, nothing critical. Would just be good to reduce that noise, it's really filling the log when testing quick pipeline start / stop sequences and using up performance

2021-09-18 00:28 UTC, keyonjie commented
maybe we can add condition e.g.
```
 #if CONFIG_DEBUG_HEAP
 heap_trace_all(0);
#endif
```

2021-09-20 10:15 UTC, lgirdwood commented
@lyakh @keyonjie lets make this a Kconfig debug option.

2022-04-20 06:49 UTC, sys-pt1s commented
Can one of the admins verify this patch?

2022-10-13 09:37 UTC, kv2019i commented
@lyakh Still valid?

2022-10-14 08:43 UTC, lyakh commented
> @lyakh Still valid?

@kv2019i I think it's only for XTOS, so, as long as nobody complains about this there, we can close this

2022-10-14 08:43 UTC, closed without merging