Fix/hda dma
thesofproject/sof pull request #4797
Opened 2021-09-23 20:39 UTC by ranj063

2021-09-23 22:47 UTC, plbossart commented on src/audio/host.c
> -			audio_stream_get_free_bytes(&hd->local_buffer->stream);
oh, this declaration shadowed the variable at the higher level. This was completely broken. ARGHHH.

2021-09-23 22:47 UTC, plbossart commented on src/drivers/intel/hda/hda-dma.c
> +	if (chan->direction == DMA_DIR_DEV_TO_MEM && dgcs & DGCS_BOR) {
nit-pick: I would add parentheses here and line 860, this sort of code is awful.

2021-09-24 06:24 UTC, dbaluta approved these changes

2021-09-24 14:40 UTC, plbossart approved these changes

2021-09-24 14:40 UTC, lgirdwood approved these changes

2021-09-24 14:55 UTC, ranj063 commented
@lgirdwood please do not merge this. It is doing the right thing but this will make every single device fail the pause/release test.

I don't know what the right thing is. 1. continue with green failure while we identify the cause of the xrun reported by the hw or 2. merge this and identify the root cause for the xrun but this will mean all PR tests will fail

2021-09-24 15:00 UTC, lgirdwood commented
@ranj063 best to split into separate PRs as it's likely just the one PR thats causing the issue.

2021-09-24 15:01 UTC, plbossart commented
@ranj063 the main issue seems to be an ipc timeout?

all the tests with HDaudio in https://sof-ci.01.org/sofpr/PR4797/build10457/devicetest/ give the same pattern:

````
[  429.556672] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x60070000: GLB_STREAM_MSG: TRIG_RELEASE
[  429.803074] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[  429.803144] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[  430.063097] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx timed out for 0x60070000 (msg/reply size: 12/12)
````

2021-09-24 15:10 UTC, lyakh requested changes

2021-09-24 15:10 UTC, lyakh commented on src/audio/host.c
>  	return copy_bytes;
you can now just `return ALIGN_DOWN(copy_bytes, hd->dma_copy_align);`

2021-09-25 01:07 UTC, ranj063 commented
> @ranj063 the main issue seems to be an ipc timeout

No @plbossart , the IPC timeout is the result of the xrun. We recently changed the trigger IPC response to be sent from the pipeline task and that's what causes the timeout. I have suggested a fix in #4802

2021-09-27 15:13 UTC, plbossart commented
> > @ranj063 the main issue seems to be an ipc timeout
> 
> No @plbossart , the IPC timeout is the result of the xrun. We recently changed the trigger IPC response to be sent from the pipeline task and that's what causes the timeout. I have suggested a fix in #4802

well then let's first deal with the timeout before merging this, otherwise we don't know what we are testing. And if the changes mentioned are already part of the 1.9 release, we'll have to release 1.9.1...

2021-09-27 15:32 UTC, lgirdwood commented
> well then let's first deal with the timeout before merging this, otherwise we don't know what we are testing. And if the changes mentioned are already part of the 1.9 release, we'll have to release 1.9.1...

1.9.1 is planned already for fixes for stream offset DMA flows (after they have been validated).

2021-09-28 16:46 UTC, ranj063 commented
Im going to split this one into 2 PR for host and HD_DMA. closing this one for now

2021-09-28 16:46 UTC, closed without merging