debug: panic: fix log file name error
thesofproject/sof pull request #4800
Opened 2021-09-24 05:06 UTC by keyonjie

When the length of the path/file name surpass 32, there is no '\0'
anymore in the panicinfo.filename[] array, which will lead to file name
printing errors on the host side like this:
	.../include/cavs/lib/pm_memory.h\xd8:472

Here keep the last character in the array as '\0' to fix the issue and
eventually got correct output like this:
	.../include/cavs/lib/pm_memory.h:472

Signed-off-by: Keyon Jie <yang.jie@linux.intel.com>

2021-09-24 06:58 UTC, marc-hb requested changes
This code looks like a mess, can you please fix all other issues while at it?

1. The first annoyance is wondering whether SOF_TRACE_FILENAME_SIZE and sizeof(panicinfo.filename) are the same. If they are the same, then why does the code use one sometimes  and other times  the other? So they must be different, probably for some \0 reason, right? Wrong! Conclusion: remove SOF_TRACE_FILENAME_SIZE to stop this confusion and use only sizeof(panicinfo.filename). For brevity: const unsigned panic_size = sizeof(panicinfo.filename) at the top.

2. Probably the most serious problem: the else clause seems wrong when strlen() == SOF_TRACE_FILENAME_SIZE == sizeof(panicinfo.filename) because it tries to copy +1 character than the size of the buffer!! I guess this never happened because panics fortunately don't happen often.

3. strlen = rstrlen(filename) without the zero is useless here. What is needed here is the memory used WITH the zero. So replace it with memlen = rstrlen(filename) + 1 and use memlen everywhere instead of strlen. This avoids the - ( SIZE - 1)

4. Maybe add a short comment that partial initialization guarantees that panicinfo.filename is initialized to zero.

2021-09-24 07:21 UTC, keyonjie commented
> This code looks like a mess, can you please fix all other issues while at it?
> 
> 1. The first annoyance is wondering whether SOF_TRACE_FILENAME_SIZE and sizeof(panicinfo.filename) are the same. If they are the same, then why does the code use one sometimes  and other times  the other? So they must be different, probably for some \0 reason, right? Wrong! Conclusion: remove SOF_TRACE_FILENAME_SIZE to stop this confusion and use only sizeof(panicinfo.filename). For brevity: const unsigned panic_size = sizeof(panicinfo.filename) at the function top.

This is a good point, let me clean it up.

> 2. ~Probably the most serious problem: the else clause seems wrong when strlen() == SOF_TRACE_FILENAME_SIZE == sizeof(panicinfo.filename) because it tries to copy +1 character than the size of the buffer!! I guess this never happened because panics fortunately don't happen often.~
> 3. strlen = rstrlen(filename) without the zero is useless here. What is needed here is the memory used WITH the zero. So replace it with memlen = rstrlen(filename) + 1 and use memlen everywhere instead of strlen. This avoids the - ( SIZE - 1)
> 4. Maybe add a short comment that partial initialization guarantees that panicinfo.filename is initialized to zero.

in case of using 'memlen' in item 3 above, we don't need item 4 as '\0' will be copied from the filename also.

2021-09-24 07:47 UTC, keyonjie commented
@marc-hb updated.

2021-09-24 14:21 UTC, marc-hb approved these changes
Much more readable IMHO thank you!

2021-09-27 06:50 UTC, keyonjie commented
@lgirdwood @ranj063 this could be helpful for debugging of recent DSP panic issues, we will see the panic line from dmesg directly with it.

2021-09-27 06:59 UTC, dbaluta approved these changes

2021-09-27 14:20 UTC, lgirdwood commented
@kkarask @wszypelt this looks unrelated to this PR. Good to merge ? 
```
12:35:43.575     => Configure dummy component:
12:35:43.575     => Configure DMIC interface
12:35:43.575     => Playback iteration 0
12:35:43.575       => Prepare Kd Notification Catcher
12:35:43.575       => Create capture stream
12:35:43.606       => Start playback/capture
12:35:59.572         Keyword detection notification timeout

12:35:59.589         => Clear Kd Notification Catcher
12:35:59.589       => Stop playback/capture
12:35:59.636     => Free all components
```

2021-09-28 08:45 UTC, wszypelt commented
@lgirdwood I ran the tests again, it looks like everything is fine, good to merge :)

2021-09-28 08:52 UTC, merged