drivers: amd: renoir: Fix 16K sample rate for dmic
thesofproject/sof pull request #4827
Opened 2021-09-29 15:01 UTC by balakishorepati

Fix dmic sample rate to 16000 as default sample rate.

Signed-off-by: balapati <balakishore.pati@amd.com>

2021-09-29 15:19 UTC, plbossart requested changes

2021-09-29 15:19 UTC, plbossart commented on src/drivers/amd/renoir/acp_dmic_dma.c
> +		/* DMIC Clock for 16K smaple rate */
typo: sample

2021-09-29 15:36 UTC, balakishorepati commented on src/drivers/amd/renoir/acp_dmic_dma.c
> +		/* DMIC Clock for 16K smaple rate */
addressed the comment

2021-09-29 15:36 UTC, balakishorepati commented on src/drivers/amd/renoir/acp_dmic_dma.c
> +		/* DMIC Clock for 16K smaple rate */
@plbossart please review

2021-09-29 15:50 UTC, plbossart approved these changes

2021-09-29 15:51 UTC, lgirdwood approved these changes

2021-09-30 06:55 UTC, bhiregoudar approved these changes

2021-09-30 06:56 UTC, sunilkumardommati approved these changes

2021-09-30 15:09 UTC, lgirdwood commented
Unrelated issue being reported by CI on BYT.

2021-09-30 15:09 UTC, merged