xtensa-build-zephyr: add imx8m as supported platform
thesofproject/sof pull request #4837
Opened 2021-10-01 19:03 UTC by iuliana-prodan

Add imx8m platform to be tested with Zephyr.
imx8m refers to i.MX8MP target.

2021-10-01 19:05 UTC, iuliana-prodan commented
Let's keep this in draft until the Zephyr and SOF pull requests are merged.
Zephyr: https://github.com/zephyrproject-rtos/zephyr/pull/39050
SOF: https://github.com/thesofproject/sof/pull/4836

2021-10-01 19:39 UTC, marc-hb commented
Don't forget you can combine any SOF pull request / work in progress with any unmerged Zephyr commit in progress and run SOF CI on the combination. See commit 9452af0a5e8db for how.

It's not like we have a lot of Zephyr tests in CI yet but better than nothing?

2021-10-04 10:12 UTC, lgirdwood approved these changes

2021-10-04 23:58 UTC, marc-hb commented
https://github.com/thesofproject/sof/pull/4837/checks?check_run_id=3797103210 found an interesting error:

```
/workdir/zephyr/include/sof/trace/trace.h:44:11: error: format '%x' expects argument of type 'unsigned int',
but argument 3 has type 'long unsigned int' [-Werror=format=]
...
/workdir/src/drivers/imx/sdma.c:166:3: note: in expansion of macro 'tr_err'
  166 |   tr_err(&sdma_tr, "SDMA reset error, base address 0x%08x", (uintptr_t)dma_base(dma))
      |   ^~~~~~
```
`tig blame` points at initial commit 87d79c48dd72 from @paulstelian97 

Some potentially useful Zephyr background: https://github.com/zephyrproject-rtos/zephyr/issues/25327

2021-10-05 01:47 UTC, marc-hb commented
Simply dropping the cast works. `dma_base()` is currently an `uint32_t` so I'm not sure why the cast was added. Casts tend to hide real issues. 
```diff
--- a/src/drivers/imx/sdma.c
+++ b/src/drivers/imx/sdma.c
@@ -164,7 +164,7 @@ static int sdma_register_init(struct dma *dma)
 	ret = poll_for_register_delay(dma_base(dma) + SDMA_RESET, 1, 0, 1000);
 	if (ret < 0) {
 		tr_err(&sdma_tr, "SDMA reset error, base address 0x%08x",
-		       (uintptr_t)dma_base(dma));
+		       dma_base(dma));
 		return ret;
 	}
```

Also keep in mind our "legacy"  logging only supports 32 bits values. So, while this below compiles with Zephyr just fine it fails with XTOS like this:
```C
tr_err(&sdma_tr, "SDMA reset error, base address 0x%08llx",  (uint64_t)dma_base(dma));

in expansion of macro 'CT_ASSERT'
  251 |  CT_ASSERT(sizeof(a) <= sizeof(uint32_t), "error: trace argument is bigger than a uint32_t");
```

2021-10-05 08:01 UTC, paulstelian97 commented
> Simply dropping the cast works. `dma_base()` is currently an `uint32_t` so I'm not sure why the cast was added. Casts tend to hide real issues.
> 
> ```diff
> --- a/src/drivers/imx/sdma.c
> +++ b/src/drivers/imx/sdma.c
> @@ -164,7 +164,7 @@ static int sdma_register_init(struct dma *dma)
>  	ret = poll_for_register_delay(dma_base(dma) + SDMA_RESET, 1, 0, 1000);
>  	if (ret < 0) {
>  		tr_err(&sdma_tr, "SDMA reset error, base address 0x%08x",
> -		       (uintptr_t)dma_base(dma));
> +		       dma_base(dma));
>  		return ret;
>  	}
> ```
> 
> Also keep in mind our "legacy" logging only supports 32 bits values. So, while this below compiles with Zephyr just fine it fails with XTOS like this:
> 
> ```c
> tr_err(&sdma_tr, "SDMA reset error, base address 0x%08llx",  (uint64_t)dma_base(dma));
> 
> in expansion of macro 'CT_ASSERT'
>   251 |  CT_ASSERT(sizeof(a) <= sizeof(uint32_t), "error: trace argument is bigger than a uint32_t");
> ```

I casted to a 32-bit value, with intended truncation, because of that limitation that non-Zephyr trace doesn't support 64-bit values. I already knew that 64-bit values didn't work well when irqsteer tracing for IRQ storms didn't work correctly (that thing involved a 64-bit value of interrupts and it was always showing me a zero).

@iuliana-prodan submitted a patch adding a cast to uint32_t. While it's not the _proper_ solution it's the best solution we have (dma_base() is intended to be a pointer, not specifically a 32-bit value)

2021-10-05 14:37 UTC, lgirdwood commented
> @iuliana-prodan submitted a patch adding a cast to uint32_t. While it's not the _proper_ solution it's the best solution we have (dma_base() is intended to be a pointer, not specifically a 32-bit value)

Merged, but at some point we can fix all the printf formatting to align with Zephyr (i.e. once xtos is deprecated)

2021-10-05 16:41 UTC, marc-hb commented
> While it's not the proper solution it's the best solution we have (dma_base() is intended to be a pointer, not specifically a 32-bit value)

Switch to %p submitted in #4848, let's discuss there because this PR is actually unrelated, just the messenger.

2021-10-05 16:57 UTC, marc-hb commented
> let's discuss there because this PR is actually unrelated

(immediately proving myself wrong with the topic below that does not belong to #4848 either...)

> I already knew that 64-bit values didn't work well when irqsteer tracing for IRQ storms didn't work correctly (that thing involved a 64-bit value of interrupts and it was always showing me a zero).

That should have been caught at compile time like this:
```
in expansion of macro 'CT_ASSERT'
  251 |  CT_ASSERT(sizeof(a) <= sizeof(uint32_t), "error: trace argument is bigger than a uint32_t");
```
Unless a cast hid information from the compiler again.

2021-10-05 17:13 UTC, paulstelian97 commented
> > I already knew that 64-bit values didn't work well when irqsteer tracing for IRQ storms didn't work correctly (that thing involved a 64-bit value of interrupts and it was always showing me a zero).
> 
> That should have been caught at compile time like this:
> 
> ```
> in expansion of macro 'CT_ASSERT'
>   251 |  CT_ASSERT(sizeof(a) <= sizeof(uint32_t), "error: trace argument is bigger than a uint32_t");
> ```
> 
> Unless a cast hid information from the compiler again.

In that case I manually split it into two 32-bit values and printed them in sequence (it was supposed to be displayed in hex).

2021-11-02 08:34 UTC, dbaluta approved these changes

2021-11-02 08:34 UTC, dbaluta commented
@lgirdwood good to merge.

2021-11-02 08:35 UTC, dbaluta commented
SOFCI TEST

2021-11-02 08:37 UTC, dbaluta commented
SOFCI TEST

2021-11-02 14:06 UTC, marc-hb requested changes
The test `zephyr_fetch_and_switch` temporary test hack must be removed.

pull/39050/head has been merged 2 weeks ago, so pointing at it still today can at best drag zephyr back in the past (right now it seems to make the build fail like this )
```
workdir/zephyr/wrapper.c:159:33: error: implicit declaration of function 'sys_heap_usable_size' [-Werror=implicit-function-declaration]
  159 |   z_xtensa_cache_flush_inv(mem, sys_heap_usable_size(&h->heap, mem_uncached));
      |                                 ^~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

2021-11-02 14:25 UTC, dbaluta approved these changes

2021-11-02 15:30 UTC, marc-hb approved these changes

2021-11-02 22:34 UTC, merged