Minor fixes
thesofproject/sof pull request #4860
Opened 2021-10-10 00:39 UTC by keyonjie

The series includes 2 fixes:
1. return failure in case ipc_init() fails.
2. dma-trace: avoid multiple allocations to fix fuzzy IPC.

2021-10-12 05:40 UTC, keyonjie commented
> First two look like they should be squashed. I'll accept this whether they're squashed or not though.

Thanks, I would leave them as they are, as I want the testbench part to be separated for easier bisection.

2021-10-14 01:40 UTC, keyonjie commented
@marc-hb @plbossart the initial PR was intended to be minor. Anyway, let me move controversial ones out and take it back to minor again.

@plbossart to unify the zeroing of the allocated buffer, I will make another PR to proceed that.

2021-10-14 06:00 UTC, lyakh commented
> The bzero() will help for buffers as this has caught out a few users already (one recently fixed just prior to v1.9)

@lgirdwood shouldn't those users be fixed? If we're at this, shall we maybe take a step back and decide what we want our heap allocation API look like? If we're moving towards Zephyr, should we say, that we basically only have `xmalloc()` anc `xcalloc()` with flags for caching etc.? And each `*alloc()` can fail, so, it must be checked? Laying out such an API would help reviewers follow those changes.

2021-11-12 17:51 UTC, lgirdwood commented
@keyonjie I've lost track of what's going on here, is there any rework required or is this no longer required ?

2021-11-18 07:26 UTC, keyonjie commented
> @keyonjie I've lost track of what's going on here, is there any rework required or is this no longer required ?

@lgirdwood this was split from #4747 , don't have chance to proceed the refinement part4 PR, so is this.

2021-11-18 13:26 UTC, ujfalusi requested changes
The dtrace fix is still not correct.

2021-11-18 16:19 UTC, lgirdwood commented on src/ipc/ipc-common.c
> +		return -ENOMEM;
This is fine, we need to assume we are using Zephyr allocator and this could fail. No harm in xtos mode as we transition.

2021-11-18 16:20 UTC, lgirdwood reviewed
First 2 patches seem fine, could be a separate PR whilst the final patch is being aligned.

2021-11-18 16:29 UTC, ujfalusi commented
> First 2 patches seem fine, could be a separate PR whilst the final patch is being aligned.

@lgirdwood, fwiw PR #4879 deals with the memleak along with other problems which could happen if the release dtrace message is not sent.

2021-11-30 19:18 UTC, plbossart commented
it doesn't seem like this PR is anywhere close to a consensus. @lgirdwood @keyonjie what's the plan here?

2021-12-01 04:18 UTC, keyonjie commented
> it doesn't seem like this PR is anywhere close to a consensus. @lgirdwood @keyonjie what's the plan here?

The change is needed in case we want the #4747 get proceed, they are for memory zones refinement/simplification only and not mandatory needed. I will proceed them if have time before Christmas, otherwise will close them.

2021-12-20 02:03 UTC, keyonjie commented
I have no plan to work on this anymore, closing it.

2021-12-20 02:03 UTC, closed without merging