pipeline: improve timestamp failure reporting
thesofproject/sof pull request #5233
Opened 2022-01-20 07:08 UTC by lyakh

When pipeline_get_timestamp() fails it prints a warning message without context. Replace it with a more informative one.

2022-01-20 17:18 UTC, plbossart requested changes
please use BIT() and defines, thank you!

2022-01-20 17:18 UTC, plbossart commented on src/audio/pipeline/pipeline-graph.c
> +	int flag = dir & 0x80000000;
BIT(SOMETHING_MEANINGFUL)?

2022-01-20 17:18 UTC, plbossart commented on src/audio/pipeline/pipeline-graph.c
> +		reason = 3;
use defines for 'reason' values, it's just unreadable for the rest of us otherwise.

2022-01-20 17:18 UTC, plbossart commented on src/audio/pipeline/pipeline-graph.c
> +			static unsigned int n_dbg;
is this an open-coded rate limiting? Why 20?

2022-01-21 02:14 UTC, marc-hb commented
There is really bad looking crash in https://sof-ci.01.org/sofpr/PR5233/build11717/devicetest/?model=ADLP_RVP_NOCODEC&testcase=multiple-pipeline-all

Failures on the other platforms seem known: #5120 and thesofproject/linux/issues/3370

2022-01-21 07:23 UTC, lyakh commented
@plbossart sorry, I really need to learn to hide my debug-only PRs to avoid people wasting time reviewing them :-( Those flags and counters are absolutely just my debug because I didn't have a suitable platform immediately available for testing, so I pushed that for CI to test and didn't explain it strongly enough in the PR :-( My apologies!

2022-01-21 07:39 UTC, marc-hb commented
> sorry, I really need to learn to hide my debug-only PRs to avoid people wasting time reviewing them :-( 

This PR has always been a draft. Drafts have a different, grey color, do not automatically assign reviewers, do not send notifications and they can be excluded with [draft:false](https://github.com/thesofproject/sof/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse). While some `[Do not review]` tag never hurts, people who review drafts anyway do it because they have enough spare time and/or interest.

2022-01-21 09:43 UTC, lyakh commented
Now this is becoming somewhat interesting. There is indeed a (harmless / by design) race on platforms like BYT / BDW, which use `pipeline_get_timestamp()` to update their stream position. AFAIK other platforms don't do that unless the kernel configuration forces IPC position updates. The race happens when a request for a position update arrives while the firmware is performing a data copy on the same stream. Then the copy process walks the pipeline buffers and sets the `.walking` flag and then the IPC tries to walk the same pipeline and finds that flag already set and bails out.
This made me wonder why at all that flag is needed. Normally it shouldn't trigger - `pipeline_for_each_comp()` walks various buffer lists and uses recursion to follow pipeline branches, but each buffer should only be listed once in absence of circular paths. I added more debugging to see when that flag triggers. The first trigger went off in `pipeline_comp_params()` because it calls `pipeline_for_each_comp() twice in it with different context in opposite directions for parameter negotiation. Doesn't that mean, that that negotiation is aborted earlier than we think and is therefore incomplete?

2022-01-21 11:23 UTC, lyakh commented
strangely many CI failures but I cannot imagine any of them being related

2022-01-21 13:21 UTC, lgirdwood approved these changes
@marc-hb does this info level work for the CI ?

2022-01-21 18:36 UTC, marc-hb commented
> @marc-hb does this info level work for the CI ?

Right now validation does not care about FW errors, we're not at that level of quality yet. There's only a check that the logs are not empty and that's all. #5017 was filed only because the WARN spam makes the FW logs unusable for _humans_, not for CI.


thesofproject/sof-test/pull/799

2022-01-21 18:44 UTC, marc-hb commented
> strangely many CI failures but I cannot imagine any of them being related

Please add link(s) and a short summary and we can help identify and make sure this PR is not to blame.

The links are important because github does not help tracking runs across force pushes.

2022-01-21 18:47 UTC, marc-hb commented
> There is indeed a (harmless / by design) race on platforms like BYT / BDW,...

This deep analysis seems really worth copying into a new bug that should be mentioned in the commit message. Maybe in the source code even?

2022-01-24 06:57 UTC, lyakh commented
> > strangely many CI failures but I cannot imagine any of them being related
> 
> Please add link(s) and a short summary and we can help identify and make sure this PR is not to blame.
> 
> The links are important because github does not help tracking runs across force pushes.

Is a link to the top-level test page https://sof-ci.01.org/sofpr/PR5233/build11729/devicetest/ enough to trace all of them or are individual links needed?

2022-01-24 07:02 UTC, marc-hb commented
> Is a link to the top-level test page https://sof-ci.01.org/sofpr/PR5233/build11729/devicetest/ enough to trace all of them or are individual links needed?

Either is fine IMHO, whatever you think is best depending on the context.

2022-01-24 07:05 UTC, lyakh commented
> > There is indeed a (harmless / by design) race on platforms like BYT / BDW,...
> 
> This deep analysis seems really worth copying into a new bug that should be mentioned in the commit message. Maybe in the source code even?

https://github.com/thesofproject/sof/issues/5242 not adding it to the commit message though. They aren't directly related, that issue is just something that occurred to me while working on this PR

2022-01-24 17:12 UTC, lgirdwood commented
Good to merge ?

2022-01-26 14:09 UTC, merged