Audio: EQFIR: Optimize source and sink buffers use in generic C version
thesofproject/sof pull request #5339
Opened 2022-02-09 17:18 UTC by singalsu

This patch replaces the audio stream read/write frag based
access to source and sink by block processing based on
audio_stream_bytes_without_wrap() bytes count.

Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>

2022-02-09 18:25 UTC, singalsu commented
Here's test run with forced generic C version and 250 tap stereo FIR for xtensa build. The gcc build was not fast enough for realtime.

![Screenshot from 2022-02-09 20-17-52](https://user-images.githubusercontent.com/28754793/153264756-8527dcc7-6e7e-401f-b4c0-03830a41b49b.png)

Processing load in original was 324 MCPS, in optimized 309 MCPS, saving is 15 MCPS. The load is nearly same for all formats  s16/s24/s32.

Note: There's some strange variation in processing times in end of s16 playback with 10 us and 1500 us processing times seen and not steady 770 us. Need to find out why it happens in optimized version. I tried twice and got the same.

2022-02-10 12:11 UTC, lgirdwood commented
@singalsu GCC generic C build will likely need a reduced TAP count and hence performance. This can be in the Kconfig though so it's spelled out. i.e. a Kconfig setting with TAP count and comments directing users to low tap count for GCC.

2022-02-10 14:34 UTC, lgirdwood requested changes

2022-02-10 16:15 UTC, singalsu commented on src/audio/eq_fir/eq_fir.c
> +	int max_frames;				/**< Max frames to process per copy() */
Sorry, I'm not aware of such. How?

2022-02-11 08:10 UTC, singalsu commented on src/audio/eq_fir/eq_fir.c
> +	int max_frames;				/**< Max frames to process per copy() */
Done, but this needs a fix somewhere in the framework.

2022-02-11 11:49 UTC, lgirdwood commented
@marc-hb fyi the test is reporting PASS in the console but a TIMEOUT in the dashboard. https://sof-ci.01.org/sofpr/PR5339/build11990/devicetest/?model=CML_SKU0955_HDA&testcase=check-suspend-resume-with-playback-5

2022-02-11 11:52 UTC, lgirdwood approved these changes

2022-02-11 11:52 UTC, merged

2022-02-11 14:38 UTC, jsarha approved these changes

2022-02-11 14:39 UTC, jsarha reviewed
Don't understand about to context too much, but the optimizations themselves make sense and look correct.