xtensa-build-zepher: add ipc4 build support for tgl
thesofproject/sof pull request #5412
Opened 2022-02-24 06:40 UTC by aiChaoSONG

Add ipc4 build support for tgl with OVERLAY_CONFIG.

Signed-off-by: Chao Song <chao.song@linux.intel.com>

if any other IPC4 config should be added, please comment.

2022-02-24 06:49 UTC, aiChaoSONG commented
Andrey proposed a very nice solution for sof+zephyr+ipc4 build, but it cannot implemented very soon because of the complexity, and it is still under discussion.

This PR borrows some concepts from there, for example, file structure.  The solution here uses the OVERLAY_CONFIG for IPC4 software config overlay instead of CONF_FILE, and make use of Marc's patch on `west sign` https://github.com/zephyrproject-rtos/zephyr/pull/42993.

This solution targeting on a temporary solution for sof+zephyr+ipc4 build, it has no implementation conflict with the Andrey's solution. Your can take this PR here as part of Andrey's solution

2022-02-24 11:27 UTC, kv2019i approved these changes
Looks great, thanks @aiChaoSONG ! Slight typo in commit "zepher"->"zephyr".

2022-02-24 12:26 UTC, gkbldcig commented
Can one of the admins verify this patch?

2022-02-24 14:42 UTC, lgirdwood approved these changes

2022-02-24 15:10 UTC, lgirdwood commented
@aborisovich any comments ?

2022-02-24 15:19 UTC, marc-hb requested changes
> Slight typo in commit "zepher"->"zephyr".

Also, don't drop the `.py` suffix in the subject because we still have the `.sh` script right now (for a limited time)

2022-02-24 15:19 UTC, marc-hb commented on scripts/xtensa-build-zephyr.py
> +		"IPC4_ADSP_DESC": "tgl-cavs.toml",
```suggestion
		"IPC4_RIMAGE_DESC": "tgl-cavs.toml",
```

2022-02-24 15:19 UTC, marc-hb commented on scripts/xtensa-build-zephyr.py
> +		if args.ipc == "IPC4" and "IPC4_ADSP_DESC" in platform_dict:
See above.
```suggestion
		if args.ipc == "IPC4":
```

2022-02-24 15:19 UTC, marc-hb commented on scripts/xtensa-build-zephyr.py
> +			adsp_desc = pathlib.Path(SOF_TOP, "rimage", "config", platform_dict["IPC4_ADSP_DESC"])
```suggestion
			rimage_desc = pathlib.Path(SOF_TOP, "rimage", "config", platform_dict["IPC4_RIMAGE_DESC"])
```

2022-02-24 15:23 UTC, aborisovich approved these changes
Its ok for a starting point 👍

2022-02-25 02:50 UTC, aiChaoSONG commented
Version 2: 
- fix typo zepher -> zephyr
- address reviews from Marc

2022-02-26 11:07 UTC, merged

2022-02-28 20:16 UTC, marc-hb commented
We have two xtensa-build-zephyr build scripts right now, transitioning from .sh to .py. Please keep the filename extension in the commit subject otherwise it makes managing the transition period much harder than it has to be.

2022-09-21 22:21 UTC, marc-hb commented
I'm removing the `IPC3` option in #6320 because it never did anything and now `./scripts/xtensa-build-zephyr.py -i IPC3 mtl` is building IPC4 for MTL (cause it's MTL's default).