xtensa-build-zephyr.py: small de-duplication
thesofproject/sof pull request #5476
Opened 2022-03-04 23:25 UTC by marc-hb

3 commits

2022-03-05 00:04 UTC, marc-hb commented
sof-ci/jenkins is down for the week-end

2022-03-06 09:39 UTC, lgirdwood approved these changes

2022-03-07 00:12 UTC, aborisovich requested changes
Good refactor in general, only some remarks related to the comments wording and that exception catching.

2022-03-07 18:36 UTC, marc-hb commented on scripts/xtensa-build-zephyr.py
> +	if args.west_path:			# allow re-use of existing zephyrproject/ anywhere
> Maybe its subjective but this wording is not intuitive for me.

Natural language is very rarely objective :-)

> I've been taught to not describe in the comments "what the code does" but rather "what is the purpose" of this code. "Re-use" in context of assigning to global variable just looks like you would be describing "how python works".

That's really not what I meant, I was referring neither to the code nor to python but to how the end-user can avoid cloning.

Unless you know the script well I think it's not obvious that --west-path is the option not to clone from scratch. How about this:

```suggestion
	if args.west_path: # lets the user provide an existing zephyrproject/ workspace anywhere
```

2022-03-07 18:36 UTC, marc-hb commented on scripts/xtensa-build-zephyr.py
> +	except BaseException as e:
> First of all, catching a BaseException is a work-around to silence pylint.

I didn't even run pylint, I just spotted this code first without pylint and then I googled the pylint warning. This sort of catch-all is bad in any language, so I knew pylint would have a warning for this and a better "commit message" than me. Every linter will flag this in any language.

> Correct me if I am wrong but I gave it at lot of thought to this line writing this.

I wasn't aware of these complexities. Silencing a warning makes sense only when there is comment that explains why + makes sure all your thoughts don't get lost!

> I found in this thread that you can just do except Exception: # pylint: disable=broad-except .

I'm not familiar enough with Windows to test this. I will drop this commit from this PR. Could you submit this when you get a chance?

PS: this script has 261 pylint warnings right now.
```
Your code has been rated at -1.26/10
```

2022-03-07 18:36 UTC, marc-hb commented on scripts/xtensa-build-zephyr.py
> +	# argparse makes these two modes mutually exclusive.
Well of course the `argparse` authors have not written code to detect `--west-path` and `--clone-mode` and implement a mutual exclusion for free just for us, that seemed obvious to me but I can try to make that more explicit. My problem with the previous comment is that it did not gave any indication of why the two modes are mutually explicit, so it looked like a missing `else if` / bug.

How about this:
```suggestion
	#  we made these two modes mutually exclusive with argparse
```

2022-03-10 12:09 UTC, aborisovich commented on scripts/xtensa-build-zephyr.py
> +	except BaseException as e:
Yeah I will check asap that exception.

> PS: this script has 261 pylint warnings right now.
Your code has been rated at -1.26/10

Well, it's not surprising given that this code was rewritten from bash script and not designed from scratch the "pythonic" way :/

2022-03-10 12:10 UTC, aborisovich commented on scripts/xtensa-build-zephyr.py
> +	if args.west_path:			# allow re-use of existing zephyrproject/ anywhere
Yes this makes much more sense now! 👍

2022-03-10 12:11 UTC, aborisovich approved these changes

2022-03-10 13:15 UTC, merged

2022-03-10 17:01 UTC, marc-hb commented on scripts/xtensa-build-zephyr.py
> +	except BaseException as e:
> Well, it's not surprising given that this code was rewritten from bash script and not designed from scratch the "pythonic" way :/

The vast majority of the pylint warnings are about indentation or mix of tabs and spaces. The second most frequent are about naming style.

2022-03-11 01:28 UTC, aborisovich commented on scripts/xtensa-build-zephyr.py
> +	except BaseException as e:
Then looks like I need to improve my python styles, Installed pylint just now so expect improvements hoho!

2022-03-11 02:37 UTC, marc-hb commented on scripts/xtensa-build-zephyr.py
> +	except BaseException as e:
> Then looks like I need to improve my python styles, Installed pylint just now so expect improvements hoho!

:-)

I think your coding style is fine, some of pylint choices are subjective, especially wrt. whitespace. I think there's a way to override some of them, maybe with a header. Please go easy on the whitespace, I have work in progress and others might have too! So I would prefer a header.