xtensa-build-zephyr.sh: build against SOF Zephyr stable-v2.1 branch
thesofproject/sof pull request #5519
Opened 2022-03-11 10:47 UTC by kv2019i

Checkout sof/stable-v2.1 branch of
https://github.com/thesofproject/zephyr.git and use that for SOF Zephyr
build.

Signed-off-by: Kai Vehmanen <kai.vehmanen@linux.intel.com>

2022-03-11 22:39 UTC, lgirdwood approved these changes
Thanks @kv2019i this will be helpful until a more formal solution is ready upstream.

2022-03-11 22:53 UTC, marc-hb requested changes

2022-03-11 22:53 UTC, marc-hb commented on scripts/xtensa-build-zephyr.sh
> +	zephyr_fetch_and_switch    sof       sof/stable-v2.1
This makes it impossible to clone any other Zephyr version. This hack here was never meant to be merged, only submitted. Let me submit something more flexible today.

2022-03-12 07:06 UTC, marc-hb commented on scripts/xtensa-build-zephyr.sh
> +	zephyr_fetch_and_switch    sof       sof/stable-v2.1
> Let me submit something more flexible today.

Done in
- #5530

So the idea is to cherry-pick #5530 to stable-v2.1 once it's merged and then change only 2 lines / 2 default values on top.

2022-03-14 11:34 UTC, lgirdwood commented
Close this since #5530 merged.

2022-03-14 11:34 UTC, closed without merging

2022-03-14 17:18 UTC, marc-hb commented
Submitted #5538 to rule them all but our "Zephyr safety feature" seems to get in the way. See you in
- #5538