dma: switch to native Zephyr API for dw-dma & HDA
thesofproject/sof pull request #5610
Opened 2022-03-28 14:20 UTC by abonislawski

This patch will add dw-dma wrapper for zephyr driver

Opens: 
- sof dma ops names: dma_channel_put_sof? dw_dma_channel_put_zephyr?
- zephyr/CMakeLists.txt: dma-zephyr.c should be restricted for a specific platform/s?

2022-03-31 15:22 UTC, teburd commented
This seems like a nice way to adapt the SOF <-> Zephyr APIs

2022-04-04 13:52 UTC, lyakh requested changes

2022-04-04 13:52 UTC, lyakh commented on src/drivers/dw/dma-zephyr.c
> +		       channel->dma->plat_data.id, channel->index);
just a `tr_dbg()`?

2022-04-04 13:52 UTC, lyakh commented on src/drivers/dw/dma-zephyr.c
> +		return -ENODATA;
not propagating?

2022-04-04 17:15 UTC, lgirdwood requested changes
Needs to be more generic and not per DMA driver.

2022-04-15 11:34 UTC, sys-pt1s commented
Can one of the admins verify this patch?

2022-04-25 17:40 UTC, lgirdwood commented
@abonislawski any update ?
My expectation is that for each DMA API call we have today we would map current users onto the Zephyr version of that call and wrap the SOF version (for existing xtos users).
e.g. for dma_stop()
```
 grep -rn " dma_stop(" --include=*.c
src/trace/dma-trace.c:375:		err = dma_stop(d->dc.chan);
src/audio/host.c:604:		ret = dma_stop(hd->chan);
src/audio/dai.c:782:		ret = dma_stop(dd->chan);
src/audio/dai.c:786:		ret = dma_stop(dd->chan);
src/probe/probe.c:175:	err = dma_stop(dma->dc.chan);
src/probe/probe.c:177:		tr_err(&pr_tr, "probe_dma_deinit(): dma_stop() failed");
```
These would be mapped to the native Zephyr API call i.e. all user would be converted to use

int dma_stop(const struct [device](https://docs.zephyrproject.org/3.0.0/reference/drivers/index.html#c.device) *dev, uint32_t channel)[¶](https://docs.zephyrproject.org/3.0.0/reference/peripherals/dma.html#c.dma_stop)

We would need to convert the existing SOF dma calls to the Zephyr APIs as the first part of this work and then add in support for linking with the Zephyr implementation of this API. 

@juimonen same applies to SSP and other DAI drivers.

2022-05-03 07:42 UTC, abonislawski commented
@lgirdwood this approach will require to switch all dma or all dai drivers once. With sof api -> zephyr api wrapper we can merge and test each driver separately, it is also possible to use for example one dai driver from sof and one from zephyr.
Can we go this way until all drivers are ready and then in separate step switch dma/dai api to native zephyr?

2022-05-03 15:46 UTC, lgirdwood commented
> @lgirdwood this approach will require to switch all dma or all dai drivers once. With sof api -> zephyr api wrapper we can merge and test each driver separately, it is also possible to use for example one dai driver from sof and one from zephyr. Can we go this way until all drivers are ready and then in separate final step switch dma/dai api to native zephyr?

I want to avoid having an intermediate stage to develop and validate, I think it's fine to transition in steps with a Kconfig option "Use Zephyr drivers" with default value n. This means that all the local xtos based driver will be used unless this Kconfig is "y". 
i.e. stages with Zephyr drivers enabled.
1)  HDA DMA and HDA/HDMI audio - only HDA and trace can be tested.
2) DW DMA and DMIC, SSP - DMIC and SSP can also be tested.
3) Remaining Intel DAIs - all features now enabled.

2022-05-12 07:26 UTC, abonislawski reviewed
@lgirdwood please take a look, added early version but few things still needs to be changed

added host_zephyr.c and dai_zephyr.c, so both HDA and DW-DMA (similar changes)
sof dma lib not divided yet

Please ignore _sof functions, it will be reverted later

2022-05-12 07:26 UTC, abonislawski commented on src/audio/host_zephyr.c
> +	struct dma_config *dma_cfg = &hd->z_config;
The main issue is dma_config, Im still using old config and translating it to the dma_config at the end, which is obviously wrong but the old config contain some fields which are not available in the new config, like is_scheduling_source, not sure if we can ignore such fields?

2022-05-12 07:26 UTC, abonislawski commented on src/audio/host_zephyr.c
> +	err = dma_get_attribute(hd->dma, DMA_ATTR_BUFFER_ADDRESS_ALIGNMENT,
dma_get_attrubite is still missing in new version, Zephyr API does not support this.
Not sure if we can use here defines directly?

2022-05-24 07:30 UTC, abonislawski commented on src/audio/dai.c
> +		dma_channel_put_sof(dd->chan);
with native api _sof functions will not be needed so I will remove them

2022-05-24 11:33 UTC, kv2019i requested changes
Looks good for the most part. A few minor comments, but no issue with the overall approach.

2022-05-24 11:33 UTC, kv2019i commented on src/include/sof/lib/dai.h
> +	struct dma_config z_config;
Should this be ifdeffed for ZEPHYR?

2022-05-24 12:25 UTC, lgirdwood requested changes
Both this and #5731 are/were abstracting at the wrong point. The abstraction points for DMA are ```src/audio/dai.c``` and ```src/audio/host.c```.
This needs to be mechanically changed to
1) create a dai-zephyr.c (starts to use native Zephyr APIs) and copy dai.c to dai-legacy.c (this last file is exact copy of dai.c today plus any legacy dai logic from lib/dai.c).
2) same as 1) for host.c
Good for call if needed.

2022-05-24 12:27 UTC, lgirdwood commented
> Both this and #5731 are/were abstracting at the wrong point. The abstraction points for DMA are `src/audio/dai.c` and `src/audio/host.c`. This needs to be mechanically changed to
> 
> 1. create a dai-zephyr.c (starts to use native Zephyr APIs) and copy dai.c to dai-legacy.c (this last file is exact copy of dai.c today plus any legacy dai logic from lib/dai.c).
> 2. same as 1) for host.c
>    Good for call if needed.

One more thing, lets not use ```_sof``` suffixes for the legacy APIs. We can use ```_legacy``` instead and this would also align with the file name.

2022-05-25 06:10 UTC, dbaluta commented
@abonislawski , maybe this could be useful. 

FYI: https://github.com/zephyrproject-rtos/zephyr/pull/44999/commits/2035f3aa2a849a61404df0444336d9a46523b165

2022-05-25 08:53 UTC, abonislawski commented
> Both this and #5731 are/were abstracting at the wrong point. The abstraction points for DMA are `src/audio/dai.c` and `src/audio/host.c`. This needs to be mechanically changed to
> 
> 1. create a dai-zephyr.c (starts to use native Zephyr APIs) and copy dai.c to dai-legacy.c (this last file is exact copy of dai.c today plus any legacy dai logic from lib/dai.c).
> 2. same as 1) for host.c
>    Good for call if needed.

@lgirdwood please check carefully, this is how it works now with native zephyr api in src/audio/dai_zephyr.c and src/audio/host_zephyr.c, I can also rename them to dai.c/host.c and old version to dai-legacy.c/host-legacy.c

2022-05-25 09:32 UTC, lgirdwood commented
> @lgirdwood please check carefully, this is how it works now with native zephyr api in src/audio/dai_zephyr.c and src/audio/host_zephyr.c, I can also rename them to dai.c/host.c and old version to dai-legacy.c/host-legacy.c

Yes please - we really need to make it obvious what files are Zephyr and what files are legacy. Also please use the ```_legacy```  suffix. This gives us a clear dividing line.

2022-05-26 18:30 UTC, abonislawski commented on src/include/sof/lib/dai.h
> +	struct dma_config z_config;
sure, why not :)

2022-05-26 19:07 UTC, abonislawski commented
@lgirdwood updated with new legacy/zephyr suffix, also added CONFIG_ZEPHYR_NATIVE_DRIVERS as you adviced previously so we can enable it later when everything is ready along with dai PR

2022-05-27 13:21 UTC, lgirdwood approved these changes
This is a good first step toward full native Zephyr. Next things (in subsequent PRs)  are
1) Reduce other SOF native RTOS APIs in host-zephyr.c and dai-zephyr.c and use the Zephyr versions, i.e for PM, notifiers memory.
2) Fix the DAI, DMA init to have const tables of DT name strings and topology IDs so that teh CC does more of the init and not the runtime code.

2022-05-30 08:46 UTC, lgirdwood commented
SOFCI TEST

2022-05-31 08:18 UTC, abonislawski commented
@lyakh I will fix most of your comments today but please note that this PR is not about dai&host refactor

2022-05-31 11:07 UTC, abonislawski commented on src/audio/dai-zephyr.c
> +	if (dev->direction == SOF_IPC_STREAM_PLAYBACK) {
This is not a brand new dai component, just modified a little dma things, flows are the same

2022-05-31 11:08 UTC, abonislawski commented on src/audio/dai-zephyr.c
> +			irq_local_enable(irq_flags);
I can removed this but this is just our original code, no changes in this PR

2022-05-31 14:26 UTC, lgirdwood approved these changes

2022-05-31 14:28 UTC, merged