audio: remove all redundant list init's
thesofproject/sof pull request #5655
Opened 2022-04-07 00:08 UTC by ranj063

comp_new() for both IPC3 and IPC4 initializes the source/sink buffer
lists already. So, remove the redundant init from the component create
callbacks.

Signed-off-by: Ranjani Sridharan <ranjani.sridharan@linux.intel.com>

2022-04-07 06:23 UTC, dbaluta approved these changes

2022-04-07 08:21 UTC, dbaluta commented
oh man, that should have been caught by coverity.

2022-04-07 11:57 UTC, lgirdwood approved these changes

2022-04-07 16:31 UTC, cujomalainey approved these changes

2022-04-08 09:26 UTC, lgirdwood commented
@kkarask @wszypelt fwiw, looks like we have some test failures but the logs wont display. See https://sof-ci.01.org/sof-pr-viewer/#/build/PR5655/build9042903

2022-04-08 10:22 UTC, kkarask commented
@lgirdwood Yes, we have noticed that. In order to collect logs for IPC4 tests there is a need to change test code and adjust it to internal services. Work in progress.

2022-04-11 19:40 UTC, lgirdwood commented
@kkarask ok, thanks - pls ping us when it's back working and we ca rerun this one (and any others)

2022-04-15 11:34 UTC, sys-pt1s commented
Can one of the admins verify this patch?

2022-04-19 10:50 UTC, lgirdwood commented
SOFCI TEST

2022-04-19 15:47 UTC, lgirdwood commented
@wszypelt the CI result is still not loading the logs for failed tests. Can you check ? Thanks !

2022-07-07 11:02 UTC, lgirdwood commented
@ranj063 ping

2022-07-18 08:48 UTC, lyakh requested changes

2022-07-18 08:48 UTC, lyakh commented on src/audio/copier.c
> -
are you sure this one and the one below are correct? `create_host()` and `create_dai()` call `drv->ops.create()` manually and `.create()` now doesn't initialise lists, so we initialise them here. `create_host()` and `create_dai()` are indeed called from a `.new()` method but that's creating a different device object.

2022-12-16 11:54 UTC, kv2019i commented
No activity in a long time, converting as draft.

2026-05-20 22:44 UTC, closed without merging