Audio: Clean up processing function and coefficients of dcblock on reset.
thesofproject/sof pull request #5710
Opened 2022-04-21 17:36 UTC by eddy1021

This PR contributes to issues #4488

2022-04-22 09:49 UTC, lgirdwood approved these changes

2022-04-22 09:50 UTC, lgirdwood commented
@cujomalainey pls merge if good.

2022-04-23 00:15 UTC, cujomalainey requested changes

2022-04-23 00:15 UTC, cujomalainey commented on src/audio/dcblock/dcblock.c
> +	memset(cd->R_coeffs, 0, sizeof(cd->R_coeffs));
R coeff is the config passed in and should not be touched

2022-04-25 17:08 UTC, lgirdwood commented
@eddy1021 can you delete the merge commit from the PR. Thanks !

2022-04-25 17:19 UTC, eddy1021 commented
Oops.... I totally mess up the PR. sorry about that

2022-04-25 17:27 UTC, eddy1021 commented
> @eddy1021 can you delete the merge commit from the PR. Thanks !

Fixed the PR now. Sorry about adding many people to the reviewers

2022-04-26 00:59 UTC, cujomalainey approved these changes

2022-04-26 08:25 UTC, lgirdwood commented
SOFCI TEST

2022-04-27 01:20 UTC, RanderWang approved these changes

2022-04-27 09:56 UTC, lgirdwood commented
IPC4 build fixes merged yesterday, unrelated to this PR.

2022-04-27 09:56 UTC, merged