zephyr: alh: add ALH zephyr driver
thesofproject/sof pull request #5727
Opened 2022-04-25 13:27 UTC by abonislawski

Rename dai funcs, add zephyr alh driver,
add get_stream_id to dai driver
Switch to ALH zephyr driver in zephyr build

based on SSP example https://github.com/juimonen/sof/commits/ssp-wip

2022-04-26 10:05 UTC, lyakh commented on src/drivers/intel/alh/alh-zephyr.c
> +        }
indentation - like in SSP

2022-04-27 12:23 UTC, lgirdwood requested changes
@juimonen @abonislawski we need to do the abstraction at the layer above for both DMA and DAIs. i.e.for DAIs like ALH and SSP we need to
1) rename src/audio/dai.c to src/audio/dai-xtos.c
2) create a new file called src/audio/dai.c that maps the SOF dai module to Zephyr DAI driver APIs
Likewise for the DMAs
This avoids all the alh-zephyr.c and ssp-zephyr.c (+more) wrappers - as we map/wrap at the layer above.

2022-04-28 08:46 UTC, juimonen commented
> @juimonen @abonislawski we need to do the abstraction at the layer above for both DMA and DAIs. i.e.for DAIs like ALH and SSP we need to
> 
> 1. rename src/audio/dai.c to src/audio/dai-xtos.c
> 2. create a new file called src/audio/dai.c that maps the SOF dai module to Zephyr DAI driver APIs
>    Likewise for the DMAs
>    This avoids all the alh-zephyr.c and ssp-zephyr.c (+more) wrappers - as we map/wrap at the layer above.

@lgirdwood I see we could unify ssp-zephyr and alh-zephyr etc. into a single wrapper file, but that's about it....??? the dai_probe etc name clash with zephyr needs to be resolved anyway.

2022-05-24 12:06 UTC, kv2019i requested changes
This modifies cAVS2.5 build which is probably not intentional. 

I'm guessing this is better done via https://github.com/thesofproject/sof/pull/5731 , right ?

2022-05-31 08:24 UTC, abonislawski commented
Just to make sure everyone is up to date: this PR is using old way with zephyr wrappers in sof, it is not needed anymore as we are switching to native zephyr api in DAI PR where alh part from this PR is already included
or if the DAI PR will be merged without alh then this PR will just extend DAI PR with alh

2022-06-01 13:01 UTC, lgirdwood commented
> Just to make sure everyone is up to date: this PR is using old way with zephyr wrappers in sof, it is not needed anymore as we are switching to native zephyr api in DAI PR where alh part from this PR is already included or if the DAI PR will be merged without alh then this PR will just extend DAI PR with alh

We will be using native Zephyr APIs in the same manner as the DMA API that has been merged so does this need closed ?

2022-06-07 13:59 UTC, closed without merging

2022-06-07 13:59 UTC, abonislawski commented
Yes, I will reopen if needed