sof: workaround shared memory log collision with zephyr
thesofproject/sof pull request #5802
Opened 2022-05-11 12:26 UTC by aiChaoSONG

For SOF with Zephyr RTOS, both zephyr logging and sof
logging are enabled currently, shared memory log collision
happens sometimes because both zephyr and SOF error trace
use shared memory for logging.

This patch uses Zehpyr logging for error trace to mitigate
the log collision issue in SOF logging system transition
stage. Once the transition is done, this should be revreted.

With this patch, logging behavior stated below:
- SOF + XTOS: SOF DMA trace and SOF shared memory trace are used.

- SOF + Zephyr and CONFIG_ZEPHYR_LOG=y: Zephyr logging is used.

- SOF + Zephyr and CONFIG_ZEPHYR_LOG=n: Zephyr logging is used
  for Zephyr OS and SOF error logs, SOF DMA trace is used for
  SOF info/dbg/warn logs.

Signed-off-by: Chao Song <chao.song@linux.intel.com>

2022-05-11 13:25 UTC, aiChaoSONG commented
@keqiaozhang this will need your help to test.

2022-05-11 13:39 UTC, aiChaoSONG commented
This doesn't touch the shared region, if we use different regions for sof logging and zephyr logging, this PR will not be needed.

2022-05-11 14:23 UTC, lgirdwood approved these changes

2022-05-11 15:50 UTC, kv2019i requested changes
Can you point where do error traces still get written to mbox with Zephyr? I think it should be easier to block the mbox writes from SOF directly (like done in sof/src/trace/trace.c:_log_sofdict()).

I mean it would be better to have:
""- SOF + Zephyr and CONFIG_ZEPHYR_LOG=n: Zephyr logging is used
     for Zephyr OS logs and SOF DMA trace is used for SOF logs.""

... so _log_nodict() would also route SOF error prints to Zephyr via printk(). 

I might be missing something, but I think this would be better. Having the error logs missing from regular sof-logger output might mislead people.

2022-05-12 01:19 UTC, RanderWang commented
@aiChaoSONG  for IPC4, memory window 2 is used for log but windows 3 is used for IPC3.  So there is no conflict

2022-05-12 01:48 UTC, aiChaoSONG commented
> Can you point where do error traces still get written to mbox with Zephyr?

@kv2019i  For SOF error traces, we switch to use zephyr api, but other trace calls stay with SOF logging. we don't use two sets of APIs that output to same shared memory, we don't get log collision. This is done by macro like this:
```
#ifndef __ZEPHYR__
// THIS IS SOF+XTOS, SOF logging for error is used
#define pipe_err(pipe_p, __e, ...)					\
	trace_dev_err(trace_pipe_get_tr_ctx, trace_pipe_get_id,		\
		      trace_pipe_get_subid, pipe_p, __e, ##__VA_ARGS__)
#else
// THIS IS SOF+ZEPHYR, zephyr logging for error is used.
#define pipe_err(ctx, fmt, ...) LOG_ERR(fmt, ##__VA_ARGS__)
#endif
```
We will still have two log files(tabs) in CI, one is the error trace, which contains zephyr os log and sof error log, the other is slogger, which only contains SOF DMA trace(warn/info/dbg).

> for IPC4, memory window 2 is used for log but windows 3 is used for IPC3. So there is no conflict

@RanderWang This will have no impact on windows, thanks.

2022-05-12 03:43 UTC, aiChaoSONG commented
@kv2019i Thanks for you comment, appreciate it.

This PR is not needed, because there is no log collision at all. I go through the current sof logging infrastructure, the log call stack is: tr_err/warn/info/dbg -> _trace_event_with_ids() -> _log_message -> _log_sofdict() and _log_nodict.

SOF+XTOS: _log_sofdict() will output log to dma trace, and also forward error log to shared memory, _log_nodict() is an empty macro. The log format is dict.

SOF+Zephyr: _log_sofdict() will output log to dma trace, log format is dict, _log_nodict() will call zephyr printk to also print logs to shared memory, log format is plain text. 

Thanks to the great work of Marc.

2022-05-12 03:43 UTC, closed without merging

2022-05-13 21:31 UTC, marc-hb commented
> Thanks to the great work of Marc. We are already good.

You did not copy me on this, I'm discovering this only now after it's closed :-)

Next time please add me to the reviewers, maybe I can save some time!