ipc4: set component direction if it is not set
thesofproject/sof pull request #5854
Opened 2022-05-24 11:55 UTC by RanderWang

FW doesn't set component direction if the component is
for gateway. Now check the component direction and
skip set it if it is set. Only the direction of gateway
module is figured out based on gateway type so
only copier module supports get_attribute of direction.

The original method can't deal with a corner case that
gateway module has both input & output.

Signed-off-by: Rander Wang <rander.wang@intel.com>

2022-05-24 13:09 UTC, lgirdwood requested changes
@marcinszkudlinski @tmleman

2022-05-24 13:09 UTC, lgirdwood commented on src/audio/copier.c
> +			*(uint32_t *)value = -EINVAL;
return -EINVAL instead here.

2022-05-24 15:37 UTC, wszypelt commented
On internal testing. Please be patient, there are problems with the internal service, we will try to fix it within 24 hours

2022-05-25 02:50 UTC, RanderWang commented on src/audio/copier.c
> +			*(uint32_t *)value = -EINVAL;
sure

2022-05-25 08:45 UTC, lyakh commented on src/ipc/ipc4/helper.c
> +	comp_get_attribute(dev, COMP_ATTR_COPY_DIR, (void *)&dir);
no need to type-cast to `void *`

2022-05-25 08:45 UTC, lyakh commented on src/audio/copier.c
> +			return -EINVAL;
nit-pick
```
	if (!cd->endpoint_num)
		return -EINVAL;

	*(uint32_t *)value = dev->direction;
```

2022-05-26 07:44 UTC, RanderWang commented on src/ipc/ipc4/helper.c
> +	comp_get_attribute(dev, COMP_ATTR_COPY_DIR, (void *)&dir);
sure

2022-05-26 13:27 UTC, lgirdwood commented
@wszypelt looks like some IPC3 tests are failing but this is IPC4 PR. Can you check. Thanks !

2022-05-26 15:50 UTC, wszypelt commented
@lgirdwood Rerun tests, and now everything's all right

2022-05-27 10:18 UTC, tmleman approved these changes

2022-05-27 13:39 UTC, merged