xtensa-build-zephyr.py: fix find_west_workspace() to return west topdir
thesofproject/sof pull request #5906
Opened 2022-06-08 17:26 UTC by marc-hb

When neither -c nor -p is passed, the script defaults to '-p
SOF_TOP/zephyrproject', initializing the `west_top` global with
that. When everything is already cloned, this becomes
zephyrproject/modules/audio/sof/zephyrproject which is really not a
`west topdir`. Then west is pointed at:
 real_west_top/modules/audio/sof/zephyrproject/zephyr/samples/subsys/audio/sof
which obviously fails.

This was found while testing
https://thesofproject.github.io/latest/getting_started/build-guide/build-with-zephyr.html
and trying (and failing) to switch away from the older .sh script.

Fix find_west_workspace() to return the output of `west topdir` and use
that to update the `west_top` global.

This bug was introduced from the very start when the script was
converted from shell to python. The shell script did not have this
problem because it could be used without using neither -c nor -p. This
logical difference was mentioned in the code review:
https://github.com/thesofproject/sof/pull/5299#discussion_r801158177

Also remove a couple of accidental creations of a sof/zephyrproject/
directory when sof is already inside a higher zephyrproject.

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

2022-06-08 22:09 UTC, greg-intel approved these changes

2022-06-09 08:34 UTC, aborisovich requested changes

2022-06-09 14:28 UTC, marc-hb commented on scripts/xtensa-build-zephyr.py
> -		if not sof_symlink.is_symlink():
I'm afraid this is an important part of the fix. I'm not sure how you've been using this script but when simply following the most basic `west init; west update` instructions at https://thesofproject.github.io/latest/getting_started/build-guide/build-with-zephyr.html then `west_top/modules/audio/sof` exists and is not a symlink.

Again the problem is that this script defaults to `-p`, the older shell script defaulted to neither to support the most basic `west init; west update` situation.

2022-06-09 14:59 UTC, marc-hb commented on scripts/xtensa-build-zephyr.py
> -		if not sof_symlink.is_symlink():
I think you misunderstand me: I want to support ALL possible directory setups! Mine, yours and anyone else's. So I don't think these instructions are `outdated` (and I linked to a new sof-docs PR in the description).

The script should IMHO especially support the most basic `west init; west update` setup = the one that does not  require any symlink or any other magic.

The older shell script supported all possible directory setups so there's no reason why the python script cannot and I think this fix achieves that!

2022-06-09 14:59 UTC, aborisovich commented on scripts/xtensa-build-zephyr.py
> -		if not sof_symlink.is_symlink():
If it works both ways lets keep it.

2022-06-09 15:52 UTC, lgirdwood approved these changes

2022-06-09 15:53 UTC, merged

2022-06-09 16:48 UTC, kv2019i commented on scripts/xtensa-build-zephyr.py
> -		if not sof_symlink.is_symlink():
@aborisovich @marc-hb Let's keep both ways. One will be used by Zephyr developers for whom SOF is just another module (focus on Zephyr development), another used by SOF developers (focus on SOF development with a fixed Zephyr commit used to build the SOF application). We may still unify to a single model, but I don't think we should arbitrarily limit the usage especially if we have existing documentation out there.