Doxygen: Increase DOT_GRAPH_MAX_NODES to 100
thesofproject/sof pull request #5978
Opened 2022-07-01 14:58 UTC by singalsu

This avoids a currently happening error:

"error: Include graph for 'src_ipc4_int32_table.h' not generated,
too many nodes (89), threshold is 50. Consider increasing
DOT_GRAPH_MAX_NODES."

Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>

2022-07-01 17:55 UTC, marc-hb commented
Not a big fan of this.

Can you share a screenshot of how a graph with ~ 100 nodes looks like? I'm afraid it won't be very useful - there must be a reason why the default is 50...

Another reason for this default: graph generation is by far the most time consuming part of doxygen. In fact it's often the ONLY time consuming part.

The alternative is to exclude generate code
https://www.doxygen.nl/manual/faq.html#faq_code How to exclude some code

Quoting a private chat from a certain @singalsu:

> The file is computer generated and not interesting for document content.
> ...
> But it needs to be added into the code generator too, so a bit more effort.

2022-07-01 17:58 UTC, singalsu commented
@marc-hb Agree, I will try the other approach. It's OK if it doesn't suppress all src.h documentation, only the big rates matrix tables.

2022-07-01 18:47 UTC, marc-hb commented
We run doxygen twice, the second time we add `WARN_AS_ERROR = YES`. This worked when I implemented this ages ago but now it merely prints and does not fail:

https://github.com/thesofproject/sof/runs/7138341491

2022-07-01 21:37 UTC, marc-hb commented
This escape was a bug in doxygen, it has been fixed: https://github.com/thesofproject/sof/runs/7157109995

2022-07-01 21:57 UTC, marc-hb commented
doxygen upgrade (and fix) submitted in #5979 . Currently blocked by this warning.

2022-07-06 22:11 UTC, marc-hb requested changes
I found a simple way to exclude files in #5995 (and there are others)

EDIT: alternative to this PR added to #5979

2022-07-25 11:22 UTC, singalsu commented
> I found a simple way to exclude files in #5995 (and there are others)
> 
> EDIT: alternative to this PR added to #5979

@marc-hb Thanks for the patches! I hope you didn't manually do the edits. I assume you didn't update SRC's Matlab generator script so I need to add those lines output there, right?

2022-07-25 11:23 UTC, singalsu commented
Marc's patches solve this issue, so this approach is not needed.

2022-07-25 11:23 UTC, closed without merging

2022-07-25 16:06 UTC, marc-hb commented
> @marc-hb Thanks for the patches! I hope you didn't manually do the edits.

No, I wrote a very small script of course :-)

> I assume you didn't update SRC's Matlab generator script so I need to add those lines output there, right?

Unfortunately not, sorry I'm not familiar enough with Matlab. See commit message of 31b14782d25990e1d:
> Temporary, manual solution until the `\cond` directive is also generated
by the sof/tools/tune/src/*export*.m script(s)

Welcome back from vacation! Can you do this? :-)