EQ IIR conversion Take 2
thesofproject/sof pull request #6030
Opened 2022-07-19 20:20 UTC by ranj063

2022-07-19 20:44 UTC, fredoh9 commented
This is passed with check-signal-stop-start.sh on ADLP_RVP_NOCODEC. run-test-all.sh -l 1 is running now, looking good so far.

2022-07-19 20:54 UTC, fredoh9 commented
Failed in multiple-pipeline-capture.sh, DSP panic. We can wait and see official PR testing result as well.

```
+ /home/ubuntu/sof-test/test-case/multiple-pipeline-capture.sh -l 1
2022-07-19 20:47:24 UTC Sub-Test: [INFO] DUT is running IPC3 mode
...
===========================>>
[  974.550619] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ------------[ DSP dump start ]------------
[  974.550620] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: DSP panic!
[  974.550620] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: fw_state: SOF_FW_BOOT_COMPLETE (6)
[  974.550625] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: 0x00000005: module: ROM, state: FW_ENTERED, running
[  974.550627] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: status code: 0xdead006 (unknown)
[  974.550713] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: reason: runtime exception (0x6)
[  974.550714] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: trace point: 0x00004000
[  974.550715] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: panic at :0
[  974.550715] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: error: DSP Firmware Oops
[  974.550716] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: error: Exception Cause: LoadStorePIFDataErrorCause, Synchronous PIF data error during LoadStore access
```

2022-07-20 04:07 UTC, aiChaoSONG commented
part of this pr is already merged，only two commits valid
- module_adapter: set state to INITIALIZED after reset
- data_blob: modify comp_data_blob_handler_free()

2022-07-20 06:31 UTC, lyakh requested changes

2022-07-20 06:31 UTC, lyakh commented on src/audio/data_blob.c
> +		rfree(blob_handler);
this commit looks like a NOP to me and it doesn't match the commit description

2022-07-20 06:31 UTC, ranj063 commented
> part of this pr is already merged，only two commits valid
> 
> * module_adapter: set state to INITIALIZED after reset
> * data_blob: modify comp_data_blob_handler_free()

@aiChaoSONG i'm aware of that and thats why it is still a draft. I will make it ready for review when I have clarity

2022-07-21 14:30 UTC, lgirdwood commented
> +bool cpu_power_down[CONFIG_CORE_COUNT];
> +

Not cache coherent, Any array of elems where the elems are not multiples of cache line size are incoherent.

2022-07-21 14:54 UTC, ranj063 commented
@lgirdwood @lyakh I've updated the PR with Guennadi's suggested patch. Please let me know if it looks ok

2022-07-21 16:24 UTC, lyakh commented
> > +bool cpu_power_down[CONFIG_CORE_COUNT];
> > +
> 
> Not cache coherent, Any array of elems where the elems are not multiples of cache line size are incoherent.

@lgirdwood we added `SHARED_DATA` to the array definition, it should be cache-coherent now. Also notice, that this change is XTOS-only, these files aren't used with Zephyr, and we already use static shared arrays of per-core data in other locations, e.g.
```
src/lib/notifier.c:static SHARED_DATA struct notify_data notify_data_shared[CONFIG_CORE_COUNT];
src/idc/idc.c:static SHARED_DATA struct idc_payload static_payload[CONFIG_CORE_COUNT];
```

2023-01-25 09:57 UTC, singalsu commented
@ranj063 This seems to be an abandoned PR. The other PR that I used for new #6992 was earlier with name "Take 3" before rename to current.

2023-04-06 10:20 UTC, sys-pt1s commented
Can one of the admins verify this patch?

2026-05-20 22:45 UTC, closed without merging