ADL support for ES83x6 codec alone  and  ADL support for ES83x6+HDMI_in support
thesofproject/sof pull request #6047
Opened 2022-07-26 04:33 UTC by reddymur

ADL support for ES83x6 codec alone  and  ADL support for ES83x6+HDMI_in support

2022-07-26 15:57 UTC, plbossart requested changes
Too much duplication for just 2 SSPs added.

2022-07-26 15:57 UTC, plbossart commented on tools/topology/topology1/sof-adl-es83x6-ssp1-hdmi-ssp02.m4
> +# Topology for generic Alderlake-P with es8316 codec, lt6911's.
no, that's too much duplication and it's unmaintainable.

I would recommend using the same sof-glk-es8336 and conditionally include an 'hdmi-in.m4' in which you can add your own stuff.

2022-07-26 15:57 UTC, plbossart commented on tools/topology/topology1/sof-adl-es83x6-ssp1-hdmi-ssp02.m4
> +	1000, 0, 0, SCHEDULE_TIME_DOMAIN_DMA)
lines 161 to here go to hdmi-in.m4

2022-07-26 15:57 UTC, plbossart commented on tools/topology/topology1/sof-adl-es83x6-ssp1-hdmi-ssp02.m4
> +PCM_DUPLEX_ADD(HDMI-2-In, 4, PIPELINE_PCM_8, PIPELINE_PCM_9)
lines 212-213 go to hdmi-in.m4

2022-07-26 15:57 UTC, plbossart commented on tools/topology/topology1/sof-adl-es83x6-ssp1-hdmi-ssp02.m4
> +		      SSP_CONFIG_DATA(SSP, 2, 32, 0)))
line 230 to here go to hdmi-in.m4

You will need to add defines for SSP0 and SSP2 so that there's no conflict should the primary SSP_NUM change.

2022-09-12 13:31 UTC, closed without merging

2022-09-12 13:44 UTC, paulstelian97 commented
Was this PR close accidental or intentional? If accidental I'd recommend creating a new pull request on a branch of yours other than "main" to avoid this happening again.

2022-09-15 09:05 UTC, reddymur commented
due to rebase issue , the review comments are addressed in new PR.  https://github.com/thesofproject/sof/pull/6299.

PR was closed intentional due to fork repo sync with this repo.