Intel Meteorlake platform upstream
thesofproject/sof pull request #6069
Opened 2022-08-03 03:01 UTC by aborisovich

2022-08-03 03:05 UTC, aborisovich commented
@piotrkmx what do we do with 9ef052f30b69ae517b8f80e72b2d2514878c2d0a? Remove? Leave?
@marcinszkudlinski do we leave any bug tracking references in commits like in ae38b5d5a36218d738ad052547666a5cfb026a35?
Looks like we can't since it points to completely different issue...

2022-08-03 07:07 UTC, abonislawski commented
This configuration still support non-zephyr build? I think for MTL we want to support only Zephyr option and all this ace platform&drivers stuff should not be upstreamed

2022-08-03 07:32 UTC, tmleman requested changes
In general, non-zephyr configuration will not be supported.

2022-08-03 07:32 UTC, tmleman commented on app/boards/intel_adsp_ace15_mtpm.conf
> +CONFIG_LOG_FUNC_NAME_PREFIX_INF=y
This looks like it was squashed from totally not related commits. Maybe better to move this to commit where this file was added?

2022-08-03 09:32 UTC, lgirdwood reviewed
@aborisovich can this PR be split into per topic PRs e.g for ssp, dmic, dma, pm etc ? This way should be easier to review and upstream. Thanks.

2022-08-03 14:00 UTC, nashif commented on src/include/ipc/regs_ipc_ace.h
> + * INTEL CONFIDENTIAL
??

2022-08-04 13:27 UTC, aborisovich commented
> @aborisovich can this PR be split into per topic PRs e.g for ssp, dmic, dma, pm etc ? This way should be easier to review and upstream. Thanks.

Please don't. It will be only easier to review but not to upstream.
The only measurement we have that whether upstream is complete and working after all refactors during review is building a firmware and run tests to confirm that results are similar to innersource test results.
If we split this upstream to multiple PRs there is no way to perform tests and fairly compare them.
Number of files will be reduced as MTL platform will have only Zephyr build.
@marc-hb how can I remove MTL platform from building in "Reproducible builds / main (pull_request)" CI?

2022-08-04 14:39 UTC, plbossart commented
> The only measurement we have that whether upstream is complete and working after all refactors during review is building a firmware and run tests to confirm that results are similar to innersource test results.
> If we split this upstream to multiple PRs there is no way to perform tests and fairly compare them.

That's what all other open-source programs programs do, including the Linux kernel. You can perfectly submit smaller PRs and rebase your internal code on the smaller merges. Doing one big merge from one branch to the other is really not encouraged.

2022-08-04 15:12 UTC, lgirdwood commented
> As soon as I will remove SOF XTOS content from upstream I will try to sort it better,

Please also remove any IP programming code as this belongs in Zephyr, e.g. I can see a header for register definitions (which I think we already have upstream in Zephyr alongside drivers).

2022-08-04 20:14 UTC, marc-hb commented
> @marc-hb how can I remove MTL platform from building in "Reproducible builds / main (pull_request)" CI?

"Reproducible builds" is XTOS only, no Zephyr and no MTL build. This failed because you changed code (also?) used by XTOS.

2022-08-05 06:41 UTC, marcinszkudlinski requested changes
this is not a complete review, pls start with removal everything that is not used or even compiled without zephyr

2022-08-05 06:41 UTC, marcinszkudlinski commented on src/drivers/intel/ace/timer.c
> +// SPDX-License-Identifier: BSD-3-Clause
don't upstream timer.c, obsolete since thre's no non-zephyr ACE

2022-08-05 06:41 UTC, marcinszkudlinski commented on src/drivers/intel/ace/CMakeLists.txt
> +if(NOT CONFIG_ZEPHYR_SOF_MODULE)
CONFIG_ZEPHYR_SOF_MODULE is obsolete - no "pure xtos" version

2022-08-05 06:41 UTC, marcinszkudlinski commented on zephyr/CMakeLists.txt
> +		${SOF_DRIVERS_PATH}/intel/dmic/dmic.c
xtos version again

2022-08-05 06:41 UTC, marcinszkudlinski commented on zephyr/CMakeLists.txt
> +		${SOF_DRIVERS_PATH}/intel/alh.c
xtos version again

2022-08-05 06:41 UTC, marcinszkudlinski commented on zephyr/CMakeLists.txt
> +		${SOF_DRIVERS_PATH}/intel/ssp/ssp.c
xtos version again

2022-08-05 06:41 UTC, marcinszkudlinski commented on app/boards/intel_adsp_ace15_mtpm.conf
> +CONFIG_INTEL_DMIC=y
zephyr DAI drivers should be used

2022-08-05 06:41 UTC, marcinszkudlinski commented on src/include/sof/drivers/dmic.h
> +#if CONFIG_METEORLAKE
again, zephyr only

2022-08-05 06:41 UTC, marcinszkudlinski commented on src/include/sof/drivers/ssp.h
> +#elif CONFIG_ACE || CONFIG_CAVS || CONFIG_HASWELL || CONFIG_BROADWELL
ditto

2022-08-31 10:26 UTC, closed without merging