[CI-TEST] github: remove the older HW from GitHub actions
thesofproject/sof pull request #6223
Opened 2022-08-31 06:57 UTC by keqiaozhang

We are no longer support the older Intel HW platforms than TGL on
main branch, these platfroms will park at stable-v2.2 branch.

Signed-off-by: Keqiao Zhang <keqiao.zhang@intel.com>

2022-08-31 09:34 UTC, lgirdwood commented
@keqiaozhang can you also remove sue and jsl from gcc build. Thanks

2022-08-31 09:35 UTC, lgirdwood commented
> @keqiaozhang can you also remove sue and jsl from gcc build. Thanks

this can be done in another PR though - this will give us some speed up today.

2022-08-31 10:31 UTC, lgirdwood commented
@keqiaozhang it looks like it's waiting on sue, jsl and tgl gcc build forever.

2022-08-31 12:45 UTC, marc-hb requested changes
This will leave the `-a` option broken in `./scripts/docker-run.sh ./scripts/xtensa-build-all.sh -a`.

I will submit a `-a` change instead.

2022-08-31 14:30 UTC, marc-hb commented
> I will submit a -a change instead.

- #6227

2022-08-31 14:46 UTC, marc-hb commented
> @keqiaozhang can you also remove sue and jsl from gcc build. Thanks

This is a Github bug, same is happening in #6227 even though they've been removed.

2022-09-02 20:26 UTC, marc-hb commented
I think #6227 is a superset of this and merged. Close?

2022-09-06 01:55 UTC, closed without merging