xtensa-build-zephyr: pass sof build version to rimage
thesofproject/sof pull request #6276
Opened 2022-09-08 15:05 UTC by dnikodem

Rimage expects to receive fw_ver_build to prepare the manifest.

Signed-off-by: Damian Nikodem <damian.nikodem@intel.com>

2022-09-09 13:39 UTC, mwasko commented
SOF CI

2022-09-12 06:25 UTC, aborisovich reviewed
This solution is generally bad - we have a version variables in CMake, we write them to header file and then we parse the header file to get variables back to CMake with regexes...
I do not like this at all and looking for better solutions to passing version to rimage.
I've tried using [configure_file](https://cmake.org/cmake/help/latest/command/configure_file.html) to create a sof_versions.h.in file replacing existing `sof_check_version_h` function but failed as Xtensa compilers (both commercial and from Zephyr SDK) do not have extensions to actually replace \#cmakedefine preprocessor (but that was just a refactor attempt). Maybe we can try something better with west sign command overload in sof?

2022-09-12 07:02 UTC, marc-hb requested changes
95% copy/paste/diverge of the function immediately above for no obvious reason.

2022-09-12 07:11 UTC, marc-hb commented
> This solution is generally bad - we have a version variables in CMake, we write them to header file and then we parse the header file to get variables back to CMake with regexes...

Yes this is a bit of a hack but it's been working fine and hasn't caused any problem for months. We all have more urgent things to do but if you have time: the real problem is `west sign`. We shouldn't use `west sign`, we should sign directly from CMake just like XTOS still does.

I think we could not do sign directly from CMake in the past because SOF was not a real Zephyr application, SOF used to hijack `zephyr/samples/audio/sof` and `zephyr/samples/` cannot have a dependency on `rimage`; they're just samples But these days are over, since commit 00c407f8c9962af66 SOF is a real Zephyr application and having a CMake-time dependency on rimage would be fine.

> I've tried using [configure_file (https://cmake.org/cmake/help/latest/command/configure_file.html)...

I'm afraid a `configure_file` is generated at CMake configure-time, not at ninja build-time. So it would not be suitable.

2022-09-12 07:14 UTC, marc-hb commented
> We shouldn't use west sign, we should sign directly from CMake just like XTOS still does.

Another problem caused by `west sign`: https://github.com/zephyrproject-rtos/zephyr/commit/9782b2cc0597fbe

2022-09-12 07:18 UTC, dnikodem commented
> 

About "west sign -b" - according to west sign help, the west allows us to pass any parameter to the rimage tool directly after the "--" character (we are passing in the same way fw version with '-f' flag). 
According to the rimage code base, the rimage tool recognizes several command flags. One of them is '-b'.

2022-09-12 09:35 UTC, lgirdwood reviewed
@dnikodem I'm guessing you will validate on Windows ?
@marc-hb I assume CI will validate on Linux ?

2022-09-12 10:22 UTC, aborisovich commented
> We shouldn't use west sign, we should sign directly from CMake just like XTOS still does.

Well that would be actually the easiest solution. Just use [add_custom_target](https://cmake.org/cmake/help/latest/command/add_custom_target.html) that DEPENDS on rimage_ep target (this target is defined in `src/arch/xtensa/CMakeLists.txt`: `ExternalProject_Add(rimage_ep`... Then you can trigger signing without using west at all with all needed cmake variables.

2022-09-12 10:37 UTC, lgirdwood commented
> Then we could remove `west sign` command from `xtensa-build-zephyr.py` and forget about this problem for now.

I think only Intel and AMD sign FW currently. We should migrate to west though, and is the ```-b``` reuse between rimage and west is stopping us today ?

2022-09-12 10:45 UTC, aborisovich commented
> > Then we could remove `west sign` command from `xtensa-build-zephyr.py` and forget about this problem for now.
> 
> I think only Intel and AMD sign FW currently. We should migrate to west though, and is the `-b` reuse between rimage and west stopping us today ?

No, nothing is stoping us. I'm not blocking anything just trying to provide better quality solutions because this one is not very good. As far as I spoke with @dnikodem this PR is not super urgent one or anything thus I'm trying to take a step in right direction.

2022-09-12 18:20 UTC, aborisovich approved these changes

2022-09-12 20:26 UTC, marc-hb requested changes

2022-09-12 20:26 UTC, marc-hb commented on scripts/xtensa-build-zephyr.py
> +	global sof_build_version
I'm fairly confident you don't need these `global` declarations. Otherwise looks good to me.

2022-09-13 06:01 UTC, marc-hb commented
> I think only Intel and AMD sign FW currently. 

This has been already solved with some CMake conditionals in the XTOS build, we could do more or less the same thing in the Zephyr application build.

>  @marc-hb what do you think?

I think we're on the same page for most or all topics. Good brainstorming for the longer term, in the mean time let's get this small and quick change merged.

2022-09-13 17:16 UTC, marc-hb commented
> just realized the first global was already there. Still, please take the opportunity to fix this while you're changing this code (or prove me wrong).

I was wrong, apologies. the `global` keyword is needed (and confusing IMHO). The code in your previous commit bfc29a2db30b55e was correct, I should have approved it. Please restore it. Sorry for the hassle.

In your current commit 3371aad526b8c you made the variables local and removed the caching feature. I wasn't asking you to remove caching, I just thought the keyword was not needed to achieve caching. But the `global` keyword is required to implement caching, my bad.

I find `global` confusing because it is not required to _read_ a global variable, BUT it is required to _write_ to a global variable!

https://python-course.eu/python-tutorial/global-local-variables-namespaces.php

You can also (mis?)use `global` to _declare_ a global inside a function. I wrongly assumed it was it's only purpose.

PS: `global` is not required to use mutator methods: what a mess. I guess it achieves one of the purposes: discourage us from using globals.

2022-09-14 10:57 UTC, kv2019i approved these changes

2022-09-14 13:49 UTC, lgirdwood approved these changes

2022-09-14 15:59 UTC, marc-hb commented
Unrelated suspend/resume failure in https://sof-ci.01.org/sofpr/PR6276/build1560/devicetest/
Unrelated license server failure in https://sof-ci.01.org/sofpr/PR6276/build1560/build/cnl_xcc_error.txt

2022-09-14 15:59 UTC, marc-hb commented
SOFCI TEST

2022-09-15 07:19 UTC, merged