Audio: EQ-FIR: fix the shift round bugs
thesofproject/sof pull request #6468
Opened 2022-10-24 02:58 UTC by andrula-song

Fix the shift round bugs caused by not suitable
xtensa intrinsics.

Signed-off-by: Andrula Song <xiaoyuan.song@intel.com>

2022-10-24 05:02 UTC, RanderWang approved these changes

2022-10-24 09:09 UTC, singalsu requested changes

2022-10-24 09:19 UTC, btian1 commented on src/audio/eq_fir/eq_fir_hifi3.c
> +			d1 = AE_SRAA32S(z1, 8);
wondering how this works, seem the difference are:

1. Saturate
2.  imm or AR register

if imm, should use left one, and if the shift value is stored in AR register, then should use right.
shift right seems not possible for saturate, correct?

Thanks
Tim

2022-10-24 11:18 UTC, lgirdwood commented
https://github.com/thesofproject/sof/pull/6308 needs this PR.

2022-10-24 13:37 UTC, singalsu commented on src/audio/eq_fir/eq_fir_hifi3.c
> +			d1 = AE_SRAA32S(z1, 8);
Yep, there's no S24_4LE type of saturate and round instruction in HiFi so it needs multiple operations. Xtensa's f24 format is 32 bit word MSB aligned while S24_4LE needs LSB align.

2022-10-24 13:44 UTC, singalsu commented on src/audio/eq_fir/eq_fir_hifi3.c
> +			d1 = AE_SRAA32S(z1, 8);
Adding 128 with saturation to z0 and z1 before shift would do the round. Or keep SRAI32R() and then do saturating shift left and again shift right. Not sure which would be faster.

A separate 24 bit FIR core version could initialize the accumulator to contain the round value.

2022-10-25 02:18 UTC, btian1 commented on src/audio/eq_fir/eq_fir_hifi3.c
> +			d1 = AE_SRAA32S(z1, 8);
I see, so it caused by format difference for S24_4LE  , let's go for merge it.
Regarding which fast, seems the second is more straight forward without imm 128 adding, just two shift is fine.

2022-10-25 02:19 UTC, btian1 approved these changes

2022-10-26 08:52 UTC, andrula-song commented on src/audio/eq_fir/eq_fir_hifi3.c
> +			d1 = AE_SRAA32S(z1, 8);
> Adding 128 with saturation to z0 and z1 before shift would do the round. Or keep SRAI32R() and then do saturating shift left and again shift right. Not sure which would be faster.
> 
> A separate 24 bit FIR core version could initialize the accumulator to contain the round value.

tested by xtensa simulator, these 2 methods cost the same cycles. So keep the second one.

2022-10-26 10:40 UTC, singalsu approved these changes
Looks good, thanks!

2022-10-26 12:26 UTC, merged