mt upstreaml: enable CONFIG_SCHED_CPU_MASK_PIN_ONLY
thesofproject/sof pull request #6518
Opened 2022-11-02 07:49 UTC by marcinszkudlinski

SOF pins threads to specific cores and don't need them to be executed in multiple cores. This options allows Zephyr to do cache optimizations during context switches.

Signed-off-by: Flavio Ceolin <flavio.ceolin@intel.com>

2022-11-02 08:38 UTC, abonislawski approved these changes

2022-11-02 11:14 UTC, kv2019i requested changes
@marcinszkudlinski This is already done in sof/app/prj.conf and is mandatory for all SOF builds.

2022-11-03 08:55 UTC, tmleman approved these changes

2022-11-03 11:31 UTC, kv2019i commented
@marcinszkudlinski @tmleman Hmm, am I missing something? This feature is already enabled without this PR. Just did a MTL build in current mian and:

$ grep _PIN_ONLY ../build-mtl/zephyr/.config
CONFIG_SCHED_CPU_MASK_PIN_ONLY=y

... this is enough, right?

2022-11-03 11:36 UTC, marcinszkudlinski commented
Yes, I checked and the option is in effective used config. 
Closing the PR

2022-11-03 11:36 UTC, closed without merging