ace: power: add platform_pm_runtime_is_active
thesofproject/sof pull request #6548
Opened 2022-11-07 12:11 UTC by tmleman

Adding platform_pm_runtime_is_active implementation for MTL.

Signed-off-by: Tomasz Leman <tomasz.m.leman@intel.com>

2022-11-09 11:10 UTC, marcinszkudlinski requested changes

2022-11-09 11:10 UTC, marcinszkudlinski commented on src/platform/intel/ace/lib/pm_runtime.c
> +bool platform_pm_runtime_is_active(uint32_t context, uint32_t index)
consider ifdef zephyr in pm_runtime_is_active

2022-11-10 09:18 UTC, kv2019i approved these changes
Still getting used to Zephyr "pm_policy_state_lock_is_active(PM_STATE_RUNTIME_IDLE" semantics, but after rechecking how this works (again), this indeed seems correct. Thanks @tmleman !

2022-11-10 09:34 UTC, iganakov approved these changes

2022-11-11 12:55 UTC, lgirdwood commented
@marcinszkudlinski good for you now ?
@tmleman good to merge, or do we have more dependencies ?

2022-11-15 19:51 UTC, marcinszkudlinski approved these changes

2022-11-16 08:01 UTC, abonislawski approved these changes

2022-11-16 08:38 UTC, tmleman commented
@lgirdwood good to merge

2022-11-16 13:57 UTC, lgirdwood approved these changes

2022-11-16 13:57 UTC, merged