ipc4: handler: Always invoke platform_context_save() when entering D3
thesofproject/sof pull request #6618
Opened 2022-11-16 16:28 UTC by ranj063

The host driver ignores the IPC errors and continues to power off the DSP after sending the request to power off the primary core. So, always platform_context_save() even in case of errors to avoid unexpected behaviour during resume.

Signed-off-by: Ranjani Sridharan <ranjani.sridharan@linux.intel.com>

2022-11-16 16:55 UTC, lgirdwood reviewed
This means the host driver wont know the BUSY FW state at D3 ? I think we still need to return the BUSY status (as the driver would know to take any corrective action).

2022-11-17 00:18 UTC, tmleman requested changes
How it will behave in a situation when we do save/restore context of a active ppl? @marcinszkudlinski, any thoughts?

I think that if we want to power-off DSP after error on SetDx ipc, power-up should be done with purge option enabled.

2022-11-17 09:19 UTC, marcinszkudlinski requested changes
We can't go to D3 if pipelines are running. 
FW must fail the flow in case it is in a wrong state - it won't be able to restore correctly from IMR 
Driver, however, may power it off regardless of IPC status and perform a full FW load / boot flow. Anyway, the firmware MUST NOT try to enter D3 if in wrong state

2022-11-17 15:45 UTC, ranj063 commented
> We can't go to D3 if pipelines are running. FW must fail the flow in case it is in a wrong state - it won't be able to restore correctly from IMR Driver, however, may power it off regardless of IPC status and perform a full FW load / boot flow. Anyway, the firmware MUST NOT try to enter D3 if in wrong state

Thanks for the confirmation @marcinszkudlinski. Let me see how to handle this on this host then.

2022-11-17 15:45 UTC, closed without merging