ipc4: Fix chain DMA trigger handling
thesofproject/sof pull request #6651
Opened 2022-11-22 19:27 UTC by jsarha

We need to pass the pipeline_trigger() return value through in ipc4_trigger_chain_dma() for the possibly delayed reply message sending to work correctly.

Signed-off-by: Jyri Sarha <jyri.sarha@intel.com>

2022-11-22 19:34 UTC, jsarha commented
With this PR together with https://github.com/thesofproject/linux/pull/3953 sof-test/test-case/multiple-pause-resume.sh test passes also with SOF FW. However, I am still not sure if !cdma->primary.r.enable && !cdma->primary.r.allocate message is handled correctly if the stream is active. Please check @lyakh and @RanderWang !

2022-11-23 01:31 UTC, RanderWang commented
> 

https://github.com/thesofproject/sof/commit/06226d00b034921fdb831d7de9c4b240c485248c

> With this PR together with [thesofproject/linux#3953](https://github.com/thesofproject/linux/pull/3953) sof-test/test-case/multiple-pause-resume.sh test passes also with SOF FW. However, I am still not sure if !cdma->primary.r.enable && !cdma->primary.r.allocate message is handled correctly if the stream is active. Please check @lyakh and @RanderWang !

@jsarha please check this commit https://github.com/thesofproject/sof/commit/06226d00b034921fdb831d7de9c4b240c485248c. We need to first pause and then check "ret != PPL_STATUS_SCHEDULED" to do reset.

2022-11-23 06:59 UTC, ujfalusi approved these changes
@jsarha, good catch!

2022-11-23 07:55 UTC, abonislawski approved these changes

2022-11-23 09:40 UTC, jsarha commented
> 
> @jsarha please check this commit [06226d0](https://github.com/thesofproject/sof/commit/06226d00b034921fdb831d7de9c4b240c485248c). We need to first pause and then check "ret != PPL_STATUS_SCHEDULED" to do reset.

Thanks @RanderWang ,  but I still do not see how ipc_pipeline_free() would get called. Or will it be cleaned up automatically by some later step?

2022-11-23 09:47 UTC, lyakh requested changes

2022-11-23 09:47 UTC, lyakh commented on src/ipc/ipc4/helper.c
> +		return ret;
sorry, don't understand, I don't see any path where a non-success return code would be lost? It looks like everywhere `ret` is in the "negative POSIX or 0" error space, and this seems to mix it with IPC4_* error codes. Yet another one...

2022-11-23 09:53 UTC, lyakh commented
I think the calling of `ipc4_trigger_chain_dma()` is wrong:
```
	ret = ipc4_trigger_chain_dma(ipc, &cdma);
	if (ret != PPL_STATUS_SCHEDULED) {
```
`ipc4_trigger_chain_dma()` returns IPC4 error codes, so, numerically `PPL_STATUS_SCHEDULED` is equal to 2 and is equal to `IPC4_UNKNOWN_MESSAGE_TYPE` which is probably not what we want to check

2022-11-23 10:49 UTC, jsarha commented
> I think the calling of `ipc4_trigger_chain_dma()` is wrong:
> 
> ```
> 	ret = ipc4_trigger_chain_dma(ipc, &cdma);
> 	if (ret != PPL_STATUS_SCHEDULED) {
> ```
> 
> `ipc4_trigger_chain_dma()` returns IPC4 error codes, so, numerically `PPL_STATUS_SCHEDULED` is equal to 2 and is equal to `IPC4_UNKNOWN_MESSAGE_TYPE` which is probably not what we want to check

@lyakh AFAIU trigger handling requires delayed reply handling. At least pipeline_trigger() may return PPL_STATUS_SCHEDULED, shouldn't we handle that properly?

2022-11-23 13:35 UTC, RanderWang commented
> > I think the calling of `ipc4_trigger_chain_dma()` is wrong:
> > ```
> > 	ret = ipc4_trigger_chain_dma(ipc, &cdma);
> > 	if (ret != PPL_STATUS_SCHEDULED) {
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `ipc4_trigger_chain_dma()` returns IPC4 error codes, so, numerically `PPL_STATUS_SCHEDULED` is equal to 2 and is equal to `IPC4_UNKNOWN_MESSAGE_TYPE` which is probably not what we want to check
> 
> @lyakh AFAIU trigger handling requires delayed reply handling. At least pipeline_trigger() may return PPL_STATUS_SCHEDULED, shouldn't we handle that properly?

@jsarha  I understood why IPC4_SUCCESS was returned. lyakh is correct, we can't return PPL_STATUS_SCHEDULED directly. You can add a function params like "bool *delay" for ipc4_trigger_chain_dma, then return the status in delay

2022-11-24 04:59 UTC, RanderWang commented
> > @jsarha please check this commit [06226d0](https://github.com/thesofproject/sof/commit/06226d00b034921fdb831d7de9c4b240c485248c). We need to first pause and then check "ret != PPL_STATUS_SCHEDULED" to do reset.
> 
> Thanks @RanderWang , but I still do not see how ipc_pipeline_free() would get called. Or will it be cleaned up automatically by some later step?

@jsarha  I got your idea. For normal pipeline there will be a pipeline free ipc msg, but none for chain dma.
````c
	ret = ipc4_trigger_chain_dma(ipc, &cdma);

	/* it is not scheduled in another thread */
	if (ret != PPL_STATUS_SCHEDULED) {
		msg_data.delayed_reply = 0;
		msg_data.delayed_error = 0;
	} else if (!cdma->primary.r.allocate) {
               ipc_wait_for_compound_msg();
		ret = ipc_pipeline_free(ipc, pipeline_id);
                if (ret < 0) {
				tr_err(&ipc_tr, "failed to free chain dma %d", ret);
				ret = IPC4_BAD_STATE;
		} else
                                 ret = IPC4_SUCCESS;
	}
````

2022-11-24 05:04 UTC, RanderWang commented on src/ipc/ipc4/helper.c
> +				return IPC4_SUCCESS;
add comments here: pipeline reset will be done by schedule thread

2022-11-24 08:44 UTC, lyakh approved these changes

2022-11-24 08:44 UTC, lyakh commented on src/ipc/ipc4/helper.c
> +			} else if (ret == PPL_STATUS_SCHEDULED) {
no `else` needed

2022-11-24 10:18 UTC, jsarha commented
> @jsarha I got your idea. For normal pipeline there will be a pipeline free ipc msg, but none for chain dma.
> 
> ```c
> 	ret = ipc4_trigger_chain_dma(ipc, &cdma, &delay);
>         if (ret != IPC4_SUCCUESS)
>                return ret;
> 
> 	/* it is not scheduled in another thread */
> 	if (!delay) {
> 		msg_data.delayed_reply = 0;
> 		msg_data.delayed_error = 0;
> 	} else if (!cdma->primary.r.allocate) {
>               /* waiting for pipeline reset done */
>                ipc_wait_for_compound_msg();
> 		ret = ipc_pipeline_free(ipc, pipeline_id);
>                 if (ret < 0) {
> 				tr_err(&ipc_tr, "failed to free chain dma %d", ret);
> 				ret = IPC4_BAD_STATE;
> 		} else
>                                  ret = IPC4_SUCCESS;
> 	}
> ```

This should never be true: (ret != IPC4_SUCCESS && delay), so there is really no need to check right after ipc4_trigger_chain_dma() call, and even in an error case we should reset msg_data.delayed_reply and delayed_error, right?

2022-11-24 12:28 UTC, jsarha commented
> yes, no harmful to reset msg_data. Checking the ret is to make it easy to understand.

@RanderWang but since we have set msg_data.delayed_reply to 1 isn't clearing it something we have to do, also in error case?

2022-11-24 13:05 UTC, RanderWang approved these changes
LGTM

2022-11-24 16:47 UTC, jsarha commented
Latest version just adds one newline between variable declaration and code.

2022-11-25 11:51 UTC, kv2019i commented
Approvals in place, tests pass, no more comments in last two days, proceeding with merge.

2022-11-25 11:51 UTC, merged