Added daily tests workflow
thesofproject/sof pull request #6654
Opened 2022-11-23 12:02 UTC by aborisovich

2022-11-23 12:19 UTC, lgirdwood commented on .github/workflows/daily-tests.yml
> +# https://docs.github.com/en/actions/using-workflows/reusing-workflows
can you update the commit message subject and add some context. Thanks.

2022-11-23 12:41 UTC, aborisovich commented
It looks like this workflow will not run until is merged to main branch.
I'll remove on: shedule node leaving only workflow_dispatch node to run action manually from actions tab and verify it is working correctly.

2022-11-23 13:22 UTC, aborisovich commented
Looks better now, "Main Actions" and "Zephyr" workflows had to be added new node:
```
on:
  workflow_call
```
so they can be called by Daily Tests workflow

2022-11-23 13:23 UTC, aborisovich commented
I'll remove "on pull-request trigger" and leave on: schedule to check whether this will be executed in time intervals on main branch.

2022-11-23 13:45 UTC, aborisovich commented
Still no sign of the "Daily Tests" action in Action tab...
But according to Github docs it may be delayed due to high traffic of other Actions currently running...
Let's wait a bit.
![image](https://user-images.githubusercontent.com/12482515/203561926-83deb246-3134-43c9-b30c-339f0311632c.png)

2022-11-23 13:53 UTC, aborisovich commented
It looks like sheduling will not work until this workflow is on the master branch (PR is merged).
I'll add "workflow_dispatch" to Daily Tests to check if it is working.

2022-11-23 14:06 UTC, aborisovich commented
@marc-hb is it possible that new workflow is not available in Github Actions tab despite having "workflow_dispatch" trigger?
I can add "on pull request" trigger as a test to check whether all sub-workflows are starting and then remove it when we merge.

2022-11-23 14:24 UTC, aborisovich commented
All checks starting with "Daily tests /" are new workflow.
Awaiting reviews from @lgirdwood and @marc-hb .

I've consulted today Intel Internal CI team about how to trigger those workflows from Daily tests:
![image](https://user-images.githubusercontent.com/12482515/203569307-b4561015-6679-48a3-a69f-077258990337.png)
received response that this can be done but not now as it requires manual work with Github REST API.
Currently we have higher priority tasks related to internal CI.

Looks like new workflow finally appeared in the Actions tab:
![image](https://user-images.githubusercontent.com/12482515/203569942-dd2441ef-552c-4ce8-8ba2-d8b136db4c69.png)

Basically, with this new workflow we can at least daily check whether all platforms are building and whether build with Zephyr main HEAD passes.
It would be great if sof-ci checks:
![image](https://user-images.githubusercontent.com/12482515/203570527-b1c9bb76-132c-42a4-ae3c-be1be6fa65ad.png)
could also be triggered by new Daily tests but I don't know how much work is required on the backend side on sof-ci.
However, it does listen for new PRs so I guess it can also listen for new action to appear?

2022-11-24 09:56 UTC, aborisovich commented
I think we can ignore codestyle check...
I've never seen anyone starting Action document with "---" characters on top.
Also, this warning related to "truthy" values seems wrong (there is "on" statement in line 6).

2022-11-24 12:32 UTC, lgirdwood approved these changes
This should speed up the PR CI.

2022-11-28 23:24 UTC, marc-hb requested changes
Surprisingly short and simple, thanks! Only need a very easy fix for the two minor yamllint warnings as far as I'm concerned.

I wonder where the results will appear?

> It would be great if sof-ci/jenkins checks could also be triggered by new Daily tests but I don't know how much work is required on the backend side on sof-ci.


I don't know either, @greg-intel, @keqiaozhang , @fredoh9 , @aiChaoSong?

Note sof-ci/jenkins already runs some more extensive, daily sof-test plans internally but the results can unfortunately not be made public as a whole.

> However, it does listen for new PRs so I guess it can also listen for new action to appear?

AFAIK sof-ci/jenkins is continuously polling Github, looking for recent PR changes.

> I think we can ignore codestyle check...

You forgot the link, I'm guessing you're referring to https://github.com/thesofproject/sof/actions/runs/3532835426/jobs/5927687763
Always link to test results when discussing them as they're very hard/impossible to find again after a force-push.

We cannot ignore these minor yamllint warnings because this would make this check fail every time on every force push of every PR in the future. These two warnings are super easy to silence, just look at other files in the same directory.

2022-11-28 23:25 UTC, marc-hb commented
> I wonder where the results will appear?

Wait, why is this drowning the results of this Pull Request in dozens of new "Daily tests" line in? This does not look right, this pull request is not a daily test...

2022-11-29 22:11 UTC, marc-hb commented
> I wonder where the results will appear?

Here I guess: https://github.com/thesofproject/sof/actions

2022-11-29 23:33 UTC, aborisovich commented
Fixed checkpatch/yamling warnings.

2022-11-29 23:36 UTC, marc-hb approved these changes

2022-11-29 23:45 UTC, aborisovich commented
Ok, removed test code (`on: pull_request`), ready to go.
It's 23:44 of UTC time so if you merge quickly we might observe triggering this action by Github scheduler at 00:00 ;-)

2022-11-30 10:52 UTC, marcinszkudlinski commented
please rebase on newest main and re-run checks with newest sof/zephyr

2022-11-30 14:40 UTC, merged

2022-12-02 20:07 UTC, marc-hb commented
Looking great now after 2 days, thank you @aborisovich : https://github.com/thesofproject/sof/actions/workflows/daily-tests.yml