west.yml: update rimage to 65f345a52
thesofproject/sof pull request #6680
Opened 2022-11-28 18:11 UTC by iganakov

Update rimage to
65f345a52e06a084192124364c563d8133d834c2v

65f345a rimage: add src support
fe5b959 rimage: correct module type
f51ff46 rimage: remove incorrect module order check 
6623073 config: mtl: add kpb module
85a2d1e config: mtl: add kd module

Signed-off-by: Ievgen Ganakov <ievgen.ganakov@intel.com>

2022-11-28 18:15 UTC, kv2019i requested changes
@iganakov Please check the previous rimage update for example "west.yml: upgrade rimage to 3ee717eebc6a2a512a0216363ae77473f94532c1". The sof/rimage git submodule needs to be updated to the same commit-id

2022-11-28 20:37 UTC, marc-hb requested changes
Please read the comments 6 lines above this change. They may be unclear or tedious (sorry about that) but simply ignoring them is not OK.

2022-11-29 09:45 UTC, iganakov commented
@marc-hb You mean the list of commits included in the PR description is not readable?

2022-11-29 09:48 UTC, iganakov commented
@kv2019i Fixed

2022-11-29 09:55 UTC, abonislawski commented
@iganakov there is a big comment with HOW-TO above your changes in west.yml  :)

2022-11-29 09:55 UTC, abonislawski approved these changes

2022-11-29 10:38 UTC, kv2019i approved these changes
Thanks @iganakov , looks good now.

2022-11-29 12:49 UTC, kv2019i commented
@marc-hb  can you check?

2022-11-29 17:36 UTC, marc-hb approved these changes

2022-11-30 03:13 UTC, aborisovich approved these changes

2022-11-30 11:58 UTC, lgirdwood approved these changes

2022-11-30 11:58 UTC, merged