Sram enable for AMD platforms
thesofproject/sof pull request #6759
Opened 2022-12-09 09:24 UTC by DINESHKUMARK1

2022-12-09 09:29 UTC, sunilkumardommati approved these changes

2022-12-09 09:56 UTC, bhiregoudar commented on src/platform/amd/rembrandt/rembrandt.x.in
>          org = HEAP_BUFFER_BASE + HEAP_BUFFER_SIZE,
origin should be HEAP_SYSTEM_BASE

2022-12-09 10:02 UTC, bhiregoudar commented on src/platform/amd/rembrandt/rembrandt.x.in
> +        len = SRAM1_SIZE- (HEAP_SYSTEM_SIZE +HEAP_SYS_RUNTIME_SIZE + HEAP_RUNTIME_SIZE + HEAP_BUFFER_SIZE + SOF_STACK_SIZE )
Keep the length to SRAM1_SIZE

2022-12-09 10:05 UTC, bhiregoudar requested changes
Please modify as mentioned in the comments and resubmit.

2022-12-09 10:19 UTC, gkbldcig commented
Can one of the admins verify this patch?

2022-12-09 14:39 UTC, lgirdwood commented
test this please

2022-12-09 14:39 UTC, lgirdwood commented
SOFCI TEST

2022-12-09 14:40 UTC, lgirdwood commented
I've run the CIs.

2022-12-09 14:41 UTC, lgirdwood reviewed
Commit messages are missing some detail regarding the changes but otherwise LGTM

2022-12-12 14:26 UTC, DINESHKUMARK1 commented
find the code changes and merge to SOF

2022-12-12 14:57 UTC, bhiregoudar approved these changes

2022-12-12 15:09 UTC, sunilkumardommati approved these changes

2022-12-12 16:02 UTC, lgirdwood commented
SOFCI TEST

2022-12-13 13:41 UTC, lgirdwood commented
@wszypelt can you check CI, not expecting this PR to fail. Thanks !

2022-12-13 13:45 UTC, wszypelt commented
@lgirdwood we have problem with internal service now ;/ 
It seems that we already know what is wrong, so I sincerely hope that everything will work today

2022-12-13 22:39 UTC, iuliana-prodan approved these changes

2022-12-14 14:04 UTC, merged