dma: update buffer period count
thesofproject/sof pull request #6835
Opened 2022-12-19 00:08 UTC by ArsenEloglian

Double the dma buffer period count as it
should be 128 for 1 channel, 256 for 2, etc.

Signed-off-by: Arsen Eloglian <ArsenX.Eloglian@intel.com>

2022-12-19 07:58 UTC, kv2019i requested changes
Some comments inline.

2022-12-19 07:58 UTC, kv2019i commented on src/platform/intel/ace/lib/dma.c
> +		.period_count	= 2 * HDA_DMA_BUFFER_PERIOD_COUNT,
A couple of points to commit message:

1. Please use "platform: ace: update buffer period count"
This helps reviewers to immediately see this is a change specific to one platform.

2. The reason for change is still a bit lacking. Double compared to what? Why not just increase HDA_DMA_BUFFER_PERIOD_COUNT byt two? These maybe obvious, but please explain in git commit message.

2022-12-19 17:24 UTC, lgirdwood approved these changes
Do we need the same fix for TGL ?

2022-12-20 18:17 UTC, tmleman approved these changes

2022-12-21 10:55 UTC, marcinszkudlinski approved these changes

2022-12-21 10:55 UTC, softwarecki approved these changes

2022-12-21 13:49 UTC, lgirdwood commented
@kv2019i update good for you ?

2022-12-21 13:51 UTC, kv2019i approved these changes
Thanks @ArsenEloglian , good now!

2022-12-21 13:54 UTC, merged