topology2: set DMIC0 pcm id to 6
thesofproject/sof pull request #6904
Opened 2023-01-03 10:15 UTC by libinyang

UCM requires DMIC PCM ID to be 6.

Signed-off-by: Libin Yang <libin.yang@intel.com>

2023-01-03 16:40 UTC, plbossart requested changes

2023-01-04 12:58 UTC, libinyang commented on tools/topology/topology2/platform/intel/dmic-generic.conf
> +		id 6
@plbossart Thanks for the suggestion. I will refine the patch by using a parameter based on the UCM for each mode.

2023-01-05 13:07 UTC, libinyang commented
v2 update:
use DMIC0_PCM_ID for dmic0 pcm id setting.

2023-01-06 15:22 UTC, lgirdwood commented
> This PR depends on #6787. Without #6787, sof hda will fail to create the snd card because of the conflict between HDMI PCM ID and DMIC0 PCM ID, which are both 6.

#6787 now pending final approval from @ranj063

2023-01-13 06:03 UTC, mengdonglin commented
@plbossart @RanderWang Can you please check if this PR can be merged? It depends on https://github.com/thesofproject/sof/pull/6787 that has been merged.

2023-01-17 06:08 UTC, libinyang commented
https://github.com/thesofproject/sof/pull/6787 is merged, but there are some more discussions on in https://github.com/thesofproject/sof/pull/6953. Let's wait for the final conclusion.

2023-01-18 13:30 UTC, lgirdwood commented
> #6787 is merged, but there are some more discussions in #6953. Let's wait for the final conclusion.

#6953 closed. @libinyang @bardliao @kv2019i whats the next move now ?

2023-01-19 06:55 UTC, bardliao approved these changes

2023-01-19 21:39 UTC, kv2019i approved these changes
Looks good. There's a conflict now though, so needs an update.

2023-01-30 09:43 UTC, libinyang commented
Patches update

2023-01-30 15:06 UTC, lgirdwood approved these changes
@plbossart changes good now ?

2023-01-30 17:20 UTC, ranj063 commented
> sounds incomplete to me. I am pretty sure the device 10 is not right for cavs-sdw topologies

@plbossart this may be incomplete but it doesnt make the existing topologies any worse right? We're currently setting 10 for all PCM IDs for all topologies. At least the HDA ones are fixed with this one

2023-01-30 17:27 UTC, plbossart commented
> > sounds incomplete to me. I am pretty sure the device 10 is not right for cavs-sdw topologies
> 
> @plbossart this may be incomplete but it doesnt make the existing topologies any worse right? We're currently setting 10 for all PCM IDs for all topologies. At least the HDA ones are fixed with this one

what the point of doing things one step at a time, apart from wasting reviewer time?
This is a shared module, so we do things right. I don't want to review this multiple times.

2023-01-31 08:23 UTC, libinyang commented
> what the point of doing things one step at a time, apart from wasting reviewer time? This is a shared module, so we do things right. I don't want to review this multiple times.
> 
> Edit: I provided the SAME feedback last month in [#6904 (comment)](https://github.com/thesofproject/sof/pull/6904#discussion_r1060760840). Seriously?

@plbossart We have a rule for the DMIC0 PCM ID described in https://github.com/thesofproject/sof/pull/6783. The DMIC0 PCM ID should be 10.
For the below topologies, I checked: what PCMID is set in topology1, what UCM requires the DMIC0 PCMID to be.
1. cavs-nocodec-bt.conf:
    There seems no counterpart in topology1 and no special requirement from UCM.
2. cavs-nocodec.conf 
    The PCMID is 10 in topology1 and no special requirement from UCM.
3. cavs-rt5682.conf 
    The PCMID is 99 in topology1 (We should not use 99 anymore, I think) and no special requirement from UCM.
4. cavs-sdw.conf 
    The PCMID is 10 and UCM2 can accept any PCMID for sof-soundwire card (no special requirement from UCM).
5. sof-hda-generic.conf. 
    The PCMID is 6 and UCM2 requires PCMID to be 6. 

So I think this PR can cover all the scenarios in topology2: set DMIC0 PCMID to 6 only on HDA platform and let other platforms to be 10.

2023-01-31 17:17 UTC, plbossart commented
> 3. cavs-rt5682.conf
>    The PCMID is 99 in topology1 (We should not use 99 anymore, I think) and no special requirement from UCM.

have you asked the Google/Chrome folks? They use UCM, don't they? @cujomalainey @sathya-nujella 
It's not our decision to change the device numbers, and there is nothing in the card name that identifies MTL/topology2/

> 4. cavs-sdw.conf
>    The PCMID is 10 and UCM2 can accept any PCMID for sof-soundwire card (no special requirement from UCM).

the requirement is this:
CapturePCM "hw:${CardId},${find-device:type=pcm,stream=capture,field=id,regex='DMIC '}"

is this met?

2023-01-31 18:14 UTC, plbossart commented
> > > 3. cavs-rt5682.conf
> > >    The PCMID is 99 in topology1 (We should not use 99 anymore, I think) and no special requirement from UCM.
> > 
> > 
> > have you asked the Google/Chrome folks? They use UCM, don't they? @cujomalainey @sathya-nujella It's not our decision to change the device numbers, and there is nothing in the card name that identifies MTL/topology2/
> 
> Topology1 based Chrome systems are using 99 for DMIC capture. Can you please limit the change to topology2 only if possible? If it is affecting topology2 only, then from MTL onwards we can update UCM's in Chromium gits accordingly.

if we change only for topology2, you won't be able to test this topology on existing TGL chromebooks. I see no value in changing the device number and make integration/testing more complicated. Yes 99 is not a very good number, but it's not worse than 10. It's easier to stick with legacy.

2023-02-01 06:23 UTC, libinyang commented
> > 
> > Topology1 based Chrome systems are using 99 for DMIC capture. Can you please limit the change to topology2 only if possible? If it is affecting topology2 only, then from MTL onwards we can update UCM's in Chromium gits accordingly.
> 
> if we change only for topology2, you won't be able to test this topology on existing TGL chromebooks. I see no value in changing the device number and make integration/testing more complicated. Yes 99 is not a very good number, but it's not worse than 10. It's easier to stick with legacy.

@plbossart @sathya-nujella Thanks for the feedback. I will follow @plbossart 's suggestion and make the DMIC0 PCMID to be 99 for sof-mtl-max98357a-rt5682 platforms on topology2, and topology1 will not be impacted. BTW: Our current rt5682 in tplg2 is used for sof-mtl-max98357a-rt5682 platforms. However, rt5682 can also be used in other combinations, for example, in tplg1, it can be used in sof-cml-rt1011-rt5682 and sof-cml-rt5682-max98357a, and the dmic0 PCMID is 1 on such platforms. To make it more flexible, I will set the ```DMIC0_PCM_ID=99``` in the CMakefile.

> the requirement is this:
> CapturePCM "hw:${CardId},${find-device:type=pcm,stream=capture,field=id,regex='DMIC '}"

> is this met?

Currently, it meets the requirement on our supported tplg2 platforms. But this may be conflicted with DMIC1, for example WoV PCM name. I will have a check and test. If there is conflict, I will fix it in another PR as this is a PCM name issue, not PCM ID.

2023-02-01 07:01 UTC, libinyang commented
patch updated:
1. set sof-mtl-max98357a-rt5682 DMIC0 pcm id to 99

2023-02-01 23:30 UTC, plbossart approved these changes

2023-02-02 05:57 UTC, mengdonglin commented
@plbossart @kv2019i @lgirdwood Are we good to merge this PR?

2023-02-02 14:59 UTC, ranj063 commented
> @plbossart @kv2019i @lgirdwood Are we good to merge this PR?

@libinyang @mengdonglin there are conflicts

2023-02-03 08:15 UTC, libinyang commented
Patches are updated based on the latest code.

2023-02-03 12:49 UTC, merged