imx: fix race condition in interrupt handling
thesofproject/sof pull request #7188
Opened 2023-02-28 14:12 UTC by iuliana-prodan

See each commit message

2023-02-28 15:08 UTC, paulstelian97 approved these changes

2023-02-28 18:10 UTC, dbaluta requested changes
Let's wait for more testing. I have a different patch for this.

2023-03-01 23:42 UTC, iuliana-prodan commented
> Let's wait for more testing. I have a different patch for this.

@dbaluta this was tested on 2 different 8QM boards with both SRC and MIXER tplgs, with suspend-resume.
The tests were run 5 times in a row, with no failure or crash.

2023-03-02 23:16 UTC, iuliana-prodan commented
I've added a 3rd commit to this PR to fix qemu boot failure on imx8 (this was due to commit 1 in which I've updated the interrupt initialization sequence).

2023-03-03 07:06 UTC, dbaluta commented on src/drivers/imx/ipc.c
>  		/* Disable GP interrupt #0 */
this seems unrelated. Is this intentional?

2023-03-03 07:08 UTC, dbaluta approved these changes

2023-03-03 07:09 UTC, dbaluta commented
Overnight tests passed. Excellent work Iulia!

2023-03-03 07:09 UTC, merged

2023-03-03 08:33 UTC, iuliana-prodan commented
> Overnight tests passed. Excellent work Iulia!

Thanks! It was a joint work!