Update GOOGLE_RTC_AUDIO_PROCESSING for Zephyr
thesofproject/sof pull request #7202
Opened 2023-03-02 20:15 UTC by andyross

Port over the existing integration for now.  This comes from an era where SOF had no C++ support and this module was effectively rolling its own.  Zephyr has a theoretically robust and featureful C++ layer, though it isn't exposed for Cadence toolchains yet (and until yesterday was actually plain broken for C++98 compilers -- you need Zephyr main to get this to build right now, the SOF snapshot is still behind).

Consider this a stepping stone to a feature that needs to land upstream.  Useful to have in a PR for reference, maybe not for merging right now.

Note that I discovered with horror that this crossed with the MTL switchover to xt-clang.  That configuration hasn't yet been tested, may not actually link, and will likely require two separate C++ integration layers upstream.

2023-03-02 22:43 UTC, cujomalainey approved these changes

2023-03-02 23:00 UTC, lgirdwood approved these changes

2023-03-02 23:10 UTC, marc-hb requested changes
> Note that I discovered with horror that this crossed with the MTL switchover to xt-clang. That configuration hasn't yet been tested, may not actually link, and will likely require two separate C++ integration layers upstream.

Yes let's please not merge this until it's rebased on top of
- #7027

Or you could just drop the xtensa-build-zephyr.py commit from this PR to speed it up; it seems unrelated.

2023-03-02 23:10 UTC, marc-hb commented on zephyr/lib/alloc.c
> +}
https://github.com/thesofproject/sof/actions/runs/4317869629/jobs/7535474369
```
/zep_workspace/sof/zephyr/lib/alloc.c: In function '_sbrk_r':
/zep_workspace/sof/zephyr/lib/alloc.c:372:1: error: control reaches end of non-void function [-Werror=return-type]
  372 | }
      | ^
cc1: all warnings being treated as errors
```

2023-03-30 11:51 UTC, kv2019i commented
@andyross https://github.com/thesofproject/sof/pull/7027 now merged, please rebase.

2023-04-06 10:17 UTC, sys-pt1s commented
Can one of the admins verify this patch?

2023-04-06 20:59 UTC, lgirdwood commented
@andyross ping - needs a rebase

2023-04-06 21:36 UTC, cujomalainey commented
Possibly won't happen for a couple weeks, we are quite busy on this end

2023-07-12 22:42 UTC, cujomalainey commented
Ping to @andyross to follow up on this

2023-08-02 15:06 UTC, andyross commented
(Rebased on mtl-005-drop-stable for ease of distribution.  Zephyr-side C++ integration still to come)

2023-08-02 15:54 UTC, lgirdwood commented
> (Rebased on mtl-005-drop-stable for ease of distribution. Zephyr-side C++ integration still to come)

Needs to be rebased on main sinec this PR is for main.

2023-08-02 19:42 UTC, cujomalainey commented
Looks like the rebase wasn't clean and pulled in a bunch of stuff

2023-12-11 08:56 UTC, abonislawski commented
@andyross should we finally merge this to main & 007? As far as I know these commits are cherry-picked for AEC build

2023-12-12 13:21 UTC, closed without merging