Add Peakvol attenuation adjustment
thesofproject/sof pull request #7208
Opened 2023-03-03 13:25 UTC by pblaszko

Add support for LargeConfigSet:SET_ATTENUATION IPC.

The purpose is to add attenuation adjustment for peak-meter.
To properly mix multiple streams without saturation, driver configures
attenuation to the input copier of each playback stream that is going
to be mixed into one output stream. In some topologies, PeakVol is
placed behind the copier with attenuation, hence its peak-meter value
is artificially scaled by FW. To report valid peak-meter value, FW has to
adjust the measurement by reverting attenuation provided in copier.

![image](https://user-images.githubusercontent.com/93585043/222731261-ddd8f51b-1a69-4e95-82cb-14f87b8721b9.png)

Missing implementation of SET_ATTENUATION for peak-meter blocks all Windows playback scenarios.

2023-03-03 16:27 UTC, lgirdwood approved these changes
@singalsu @andrula-song pls review.

2023-03-06 02:12 UTC, andrula-song requested changes

2023-03-06 02:12 UTC, andrula-song commented on src/audio/module_adapter/module/volume/volume_generic_with_peakvol.c
> +			struct output_stream_buffer *bsink, uint32_t frames, uint32_t attenuation)
alignment

2023-03-06 02:12 UTC, andrula-song commented on src/include/sof/audio/volume.h
> +			struct output_stream_buffer *sink, uint32_t frames, uint32_t attenuation);
alignment

2023-03-06 02:12 UTC, andrula-song commented on src/audio/module_adapter/module/volume/volume_hifi3_with_peakvol.c
> +			struct output_stream_buffer *bsink, uint32_t frames, uint32_t attenuation)
alignment

2023-03-06 02:12 UTC, andrula-song commented on src/audio/module_adapter/module/volume/volume_hifi3_with_peakvol.c
> +			struct output_stream_buffer *bsink, uint32_t frames, uint32_t attenuation)
alignment

2023-03-06 02:12 UTC, andrula-song commented on src/audio/module_adapter/module/volume/volume_hifi3_with_peakvol.c
> +			struct output_stream_buffer *bsink, uint32_t frames, uint32_t attenuation)
alignment

2023-03-06 02:12 UTC, andrula-song commented on src/audio/module_adapter/module/volume/volume_hifi3_with_peakvol.c
> +			struct output_stream_buffer *bsink, uint32_t frames, uint32_t attenuation)
alignment

2023-03-06 02:12 UTC, andrula-song commented on src/audio/module_adapter/module/volume/volume_hifi3_with_peakvol.c
> +			struct output_stream_buffer *bsink, uint32_t frames, uint32_t attenuation)
alignment

2023-03-06 02:12 UTC, andrula-song commented on src/audio/module_adapter/module/volume/volume_hifi3_with_peakvol.c
> +			struct output_stream_buffer *bsink, uint32_t frames, uint32_t attenuation)
alignment

2023-03-06 02:12 UTC, andrula-song commented on src/audio/module_adapter/module/volume/volume_hifi3.c
> +			struct output_stream_buffer *bsink, uint32_t frames, uint32_t attenuation)
alignment

2023-03-06 02:12 UTC, andrula-song commented on src/audio/module_adapter/module/volume/volume_hifi3.c
> +			struct output_stream_buffer *bsink, uint32_t frames, uint32_t attenuation)
alignment

2023-03-06 02:12 UTC, andrula-song commented on src/audio/module_adapter/module/volume/volume_hifi3.c
> +			struct output_stream_buffer *bsink, uint32_t frames, uint32_t attenuation)
alignment

2023-03-06 02:12 UTC, andrula-song commented on src/audio/module_adapter/module/volume/volume_generic_with_peakvol.c
> +			struct output_stream_buffer *bsink, uint32_t frames, uint32_t attenuation)
alignment

2023-03-06 02:12 UTC, andrula-song commented on src/audio/module_adapter/module/volume/volume_generic_with_peakvol.c
> +			cd->peak_regs.peak_meter[j] = tmp << attenuation;
does the calculation right? should there be cd->peak_regs.peak_meter[j] = MAX(tmp<< attenuation, cd->peak_regs.peak_meter[j]);?

2023-03-06 02:12 UTC, andrula-song commented on src/audio/module_adapter/module/volume/volume_hifi3_with_peakvol.c
> +					cd->peak_vol[i + channels_count]) << attenuation;
alignment

2023-03-06 02:12 UTC, andrula-song commented on src/audio/module_adapter/module/volume/volume_hifi3_with_peakvol.c
> +				cd->peak_vol[i + channels_count]) << attenuation;
alignment

2023-03-06 07:32 UTC, pblaszko commented on src/audio/module_adapter/module/volume/volume.c
> +			volume_set_chan(mod, i, cd->tvolume[i], true);
OK, thanks. For more logical history, let's wait for #7197 to merge, then I will "rebase" to include the fix.

2023-03-06 09:55 UTC, andrula-song approved these changes

2023-03-06 10:41 UTC, pblaszko commented
please do not merge - I still need to rebase with new Volume fixes

2023-03-06 10:56 UTC, dnikodem approved these changes

2023-03-06 12:10 UTC, lgirdwood commented
@pblaszko also some conflicts.

2023-03-06 12:15 UTC, pblaszko commented
Rebase done.

2023-03-06 12:19 UTC, lgirdwood approved these changes

2023-03-06 13:47 UTC, pblaszko commented
SOFCI TEST

2023-03-06 14:49 UTC, merged

2023-03-06 15:25 UTC, singalsu commented on src/audio/module_adapter/module/volume/volume_generic_with_peakvol.c
> +			tmp = tmp << attenuation;
I missed this review. But why isn't this max value scaling done at this function calling level?