topology: sof-adl-nau8825: add variant with nau8318 amplifier
thesofproject/sof pull request #7212
Opened 2023-03-06 07:17 UTC by macchian

Adding support for nau8318 Amplifier.

sof-adl-nau8318-nau8825:
    nau8825 headphone connects SSP0 link.
    nau8318 Amp speakers connects SSP1 link.
    bluetooth offload uses SSP2 link.

Signed-off-by: Ajye Huang <ajye_huang@compal.corp-partner.google.com>
Signed-off-by: Mac Chiang <mac.chiang@intel.com>
(cherry picked from commit cdcbdae705a42578dc99d6bf54f275c699afbc81)

2023-03-06 11:47 UTC, lgirdwood approved these changes

2023-03-06 12:36 UTC, kv2019i approved these changes

2023-03-07 01:16 UTC, cujomalainey requested changes
this should be targetting cavs2.5-001-drop-stable per @mwasko email.

@mwasko can we get dead branches archived/locked out?

2023-03-07 03:33 UTC, macchian commented
> 
@cujomalainey, yes, I should pick it to cavs2.5-001-drop-stable.

2023-03-08 14:40 UTC, lgirdwood commented
> > We should rename them to be like `intel/archive/rpl-001-drop-stable` this way they can be reused if needed e.g. to validate a fix in an updated kernel.
> 
> We could rename the branch and put it in a RO namespace for protected branches to guarantee the process works as intended rather than assuming a name implies the same process for everyone

@mwasko work for you ? If so what schedule would you have for this ?

2023-03-28 00:21 UTC, gkbldcig commented
Can one of the admins verify this patch?

2023-03-28 17:28 UTC, cujomalainey commented
This branch is closed

2023-03-28 17:28 UTC, closed without merging