Fix checkpatch styling errors
thesofproject/sof pull request #7334
Opened 2023-03-26 07:34 UTC by jiande-my

Fix checkpatch styling errors

This commit fixes specific checkpatch styling errors in the following files:

- In `ipc.c`, line 311 exceeds the 100-column limit. This is corrected by breaking the line into two.
- In `sai.c`, an argument is not aligned with an open parenthesis. This is fixed by aligning the argument.
- In `sdma.c`, a `fallthrough` comment is replaced with `fallthrough;` to follow Linux kernel coding conventions.

2023-03-26 07:36 UTC, sofci commented
Can one of the admins verify this patch?
> reply **test&nbsp;this&nbsp;please** to run this test once

2023-03-26 08:18 UTC, gkbldcig commented
Can one of the admins verify this patch?

2023-03-26 11:24 UTC, iuliana-prodan commented
@jiande-my thanks for the pull request. 
Please merge the first 2 commits, since the second is removing something introduced in commit 1.

Also, add a commit message and a commit description, for each patch. 
See an example in PR #7302

2023-03-26 11:24 UTC, iuliana-prodan commented
Test this please

2023-03-26 21:13 UTC, iuliana-prodan requested changes

2023-03-26 21:13 UTC, iuliana-prodan commented on src/drivers/imx/ipc.c
> -	/**/
squash this commit into the first one

2023-03-26 21:13 UTC, iuliana-prodan commented on src/drivers/imx/sdma.c
> +
no need for a newline

2023-03-26 21:13 UTC, iuliana-prodan commented on src/drivers/imx/ipc.c
please, add a commit message and a commit description

2023-03-26 21:13 UTC, iuliana-prodan commented on src/drivers/imx/ipc.c
>  	 * enable GP #0 for Host -> DSP message notification
Actually all 3 commits should be squashed into 1 and add a commit message and a commit description

2023-03-27 08:24 UTC, paulstelian97 commented
Besides the issues presented by Iuliana, I strongly recommend you visit https://thesofproject.github.io/latest/contribute/contribute_guidelines.html (specifically the developer certification of origin, but related pages are also important) and figure out the rules from that.

2023-03-28 07:01 UTC, jiande-my commented
@iuliana-prodan I have resolved the issue you addressed.

2023-03-28 07:42 UTC, iuliana-prodan requested changes

2023-03-28 07:42 UTC, iuliana-prodan commented on src/drivers/imx/ipc.c
>  	/* can't send notification when one is in progress */
Please, update commit message, by replacing "_shorts_" line with "short lines"

2023-03-28 07:47 UTC, jiande-my commented
> > @iuliana-prodan I have resolved the issue you addressed.
> 
> yes, thank you! One more comment to address.

Done

2023-03-28 07:48 UTC, iuliana-prodan approved these changes

2023-04-04 11:53 UTC, jiande-my commented on src/drivers/imx/sdma.c
> +		/* TODO: implement to support m2m */
I thought it was comment line I will add it back

2023-04-04 12:14 UTC, paulstelian97 approved these changes

2023-04-06 20:28 UTC, lgirdwood commented
@jiande-my I think checkpatch is failing due to the text after your Signed-off-by line.

2023-04-10 13:14 UTC, kv2019i approved these changes
Looks ok now, let's see if the CI runs pass.

2023-04-18 09:52 UTC, lgirdwood commented
SOFCI TEST

2023-04-24 08:57 UTC, merged