[dai-zephyr]: remove not used ptr and its assign
thesofproject/sof pull request #7457
Opened 2023-04-19 07:23 UTC by btian1

but_ptr is no longer valid, remove it.

2023-04-19 07:34 UTC, paulstelian97 approved these changes
Removing what is essentially dead code is usually good, and I don't see a reason why this should be an exception. Approve.

2023-04-19 12:01 UTC, kv2019i requested changes
Change is good, can you fix the git message.

2023-04-19 12:22 UTC, btian1 commented on src/audio/dai-zephyr.c
>  	struct dai_data *dd = comp_get_drvdata(dev);
sorry, before catch up shuttle, removed.

2023-04-19 15:51 UTC, lyakh approved these changes

2023-04-19 20:22 UTC, kv2019i approved these changes

2023-04-19 20:23 UTC, kv2019i commented
One fail in https://sof-ci.01.org/sofpr/PR7457/build6062/devicetest/index.html and one in https://sof-ci.01.org/sofpr/PR7457/build6063/devicetest/index.html . Both unrelated to this PR, proceeding with merge.

2023-04-20 11:12 UTC, tmleman approved these changes

2023-04-20 11:20 UTC, dnikodem approved these changes

2023-04-20 18:07 UTC, kv2019i commented
One fail in https://sof-ci.01.org/sofpr/PR7457/build6062/devicetest/index.html 
One system suspend fail in https://sof-ci.01.org/sofpr/PR7457/build6063/devicetest/index.html
Sparse fail that was introduced due to a bug in the sparse CI check (issue not reported).

All known things not related to this PR, merging.

2023-04-20 18:07 UTC, merged