platform: move tgl tgl-h to supported platforms
thesofproject/sof pull request #7507
Opened 2023-04-24 21:17 UTC by fredoh9

scripts/xtensa-build-all.sh -a throws error when tgl tgl-h are built with gcc tool chain. New SOF docker image don't have xtensa-cnl-elf-gcc any more. Related change is dc9ba281d76519dbed3670fe3691d0a9aedee85a.

Move tgl tgl-h from DEFAULT_PLATFORMS to SUPPORTED_PLATFORMS. Those platforms can be built if xcc/gcc toolchains are available.

2023-04-24 21:19 UTC, fredoh9 commented
New SOF docker image is coming https://github.com/thesofproject/sof/pull/7169

2023-04-24 21:20 UTC, marc-hb approved these changes

2023-04-24 22:09 UTC, marc-hb commented
Strange how MTL is missing from zephyr builds in https://sof-ci.01.org/sofpr/PR7507/build6398/build/index.html
@greg-intel any idea?

2023-04-24 23:32 UTC, greg-intel commented
@marc-hb I have to assume it's related to the large number of issues Jenkins experienced today.  Also could be due to a lack of availability.  But that's just a guess, I'm not sure what generates the piece that's missing, but if it's at the end...

2023-04-24 23:57 UTC, marc-hb commented
> @marc-hb I have to assume it's related to the large number of issues Jenkins experienced today.

Whatever problems happen, we should never get a build of the same branch with half the platforms

2023-04-25 16:13 UTC, marc-hb commented
SOFCI TEST

2023-04-26 04:24 UTC, marc-hb requested changes
Change of mind, let's keep the TGL toolchain instead: #7515

Simpler and faster.

2023-04-26 18:05 UTC, closed without merging