Remaining mixer renames
thesofproject/sof pull request #7769
Opened 2023-06-08 10:01 UTC by jsarha

Hopefully the final PR to complete "all controls and PCM names SHALL have a meaningful name."
in https://github.com/thesofproject/sof/issues/6576

This (and the previous PRs) all touch the PCM names, but does not change them. @plbossart if you would like to see some changes in the PCM names, you can comment that in this PR.

2023-06-08 14:21 UTC, plbossart requested changes

2023-06-08 14:21 UTC, plbossart commented on tools/topology/topology2/platform/intel/sdw-jack-generic.conf
> +       JACK_CAPTURE_PCM_NAME	"Jack in"
Jack Out/In

2023-06-13 16:27 UTC, jsarha commented on tools/topology/topology2/platform/intel/sdw-jack-generic.conf
> +       JACK_CAPTURE_PCM_NAME	"Jack in"
Fixed in the latest version.

2023-06-13 16:27 UTC, jsarha commented on tools/topology/topology2/cavs-sdw-src-gain-mixin.conf
> +	JACK_IN_PCM_NAME	"Jack in"
Fixed in the latest version.

2023-06-19 20:11 UTC, jsarha commented
@plbossart and @ranj063 a gentle ping.

2023-06-28 09:25 UTC, singalsu approved these changes

2023-06-28 14:17 UTC, kv2019i commented
Given this a topology2 change, I'll ignore the stuck Intel System CI tests, and I ignore the manifest-check as this does not change rimage (submodule or manifest version). I'll proceed with merge.

2023-06-28 14:17 UTC, merged