Update bug_report.md
thesofproject/sof pull request #7807
Opened 2023-06-15 11:23 UTC by wszypelt

Update bug_report with additional information that includes a request to attach kernel logs with complete IPC Payloads.

2023-06-15 13:47 UTC, wszypelt commented
SOFCI TEST

2023-06-15 19:25 UTC, marc-hb requested changes
> SOFCI TEST

Please don't spend hardware cycles testing irrelevant `.github/` changes. I added the `[SKIP SOF-TEST]` prefix to avoid this.

2023-06-15 22:50 UTC, marc-hb commented on .github/ISSUE_TEMPLATE/bug_report.md
> +Please include the relevant sections from the firmware log and kernel log(with complete IPC Payloads) in the report (and attach the full logs for complete reference also IPC payloads are required). K
> where and how do you get "IPC payloads"? I don't remember seeing any documentation about this. 

BTW it's a strange to request this in an open-source project when there's no open-source tool or test that can make use of it.

2023-06-16 16:32 UTC, cujomalainey commented on .github/ISSUE_TEMPLATE/bug_report.md
> +Please include the relevant sections from the firmware log and kernel log(with complete IPC Payloads) in the report (and attach the full logs for complete reference also IPC payloads are required). K
Ditto on that, IPC payloads is a very high bar, beyond kernel configs. Unless the snooping tools get better this is not acceptable as a requirement

2023-06-19 13:46 UTC, plbossart commented
@wszypelt kind reminder to push branches in your own cloned tree, not on the SOF tree directly. Thank you.

2023-06-20 10:12 UTC, wszypelt commented
@tmleman @marc-hb @plbossart @cujomalainey  Thanks for taking your time and commenting on this PR. I'll take everything into account. For now, I will close this PR, and perhaps open it in a new correct version after discussions with the team.

2023-06-20 10:12 UTC, closed without merging