audio/selector: Don't assert on input-controllable memcpy_s failure
thesofproject/sof pull request #7853
Opened 2023-06-22 21:20 UTC by andyross

The size argument to the memcpy_s() here is under the control of external data and can fail on garbage.  That needs to be a runtime failure, not an assertion.

2023-06-22 21:21 UTC, andyross commented
Another fuzz find

2023-06-23 10:56 UTC, tlissows requested changes

2023-06-23 10:56 UTC, tlissows commented on src/audio/selector/selector.c
> +		return NULL;
It looks like losing reference to allocated memory. Suggested change:
```
	if (ret) {
		rfree(cd);
		rfree(dev);
		return NULL;
	}
```

2023-07-06 17:22 UTC, andyross commented
Rebase, include the suggestion as it seems safe and obviously correct.

FWIW: this is a fatal error situation, where the host has sent a garbage command.  I'd left the recover out as it's essentially impossible for me to test locally (this failure just doesn't come up often enough in fuzzing outside the cloud rig).  But I can't see why it would hurt.

2023-07-06 19:38 UTC, lgirdwood approved these changes

2023-07-07 07:32 UTC, tlissows approved these changes

2023-07-07 10:06 UTC, lyakh approved these changes

2023-07-07 13:16 UTC, lgirdwood commented
@wszypelt @lrudyX good to merge ? @andyross has no way to check CI.

2023-07-11 06:54 UTC, wszypelt commented
@lgirdwood after rerun in internal intel CI System everything went fine, so it's green on my part

2023-07-11 13:12 UTC, merged