ipc: Fix typo in error checking
thesofproject/sof pull request #7856
Opened 2023-06-22 21:34 UTC by andyross

[Third time's the charm?  Still trying to extract that rogue rimage submodule delta.]

Found a oss-fuzz error I thought I'd fixed being reported again. Turns out the fix had a typo and only fixed half the problem space. Need to check source and sink, not source and source!

2023-06-22 21:35 UTC, andyross commented
Gah, nope.  Not happening to my other PRs though?  Closing the third one.  Will do some research before resubmitting.  Sorry for all the spam.

2023-06-22 22:37 UTC, andyross commented
Out of ideas with the submodule mess.  Reopening this one just to have something to review.  Will wait for HEAD to change when something else merges, then do a 100% clean resubmit.  Weirdest thing I've seen.

2023-06-23 06:48 UTC, marc-hb commented
I have no idea why but your commits apparently tend to include random rimage changes... This is purely local problem, only between you and your local git installation.

You're not using the evil `git commit -a` or similar?

<img width="898" alt="Screenshot 2023-06-22 at 23 47 48" src="https://github.com/thesofproject/sof/assets/46978960/6d9b5c0b-65e1-4c6e-aa95-d3b816b93086">

2023-06-26 06:30 UTC, lyakh requested changes

2023-06-26 06:30 UTC, lyakh commented on src/ipc/ipc-helper.c
> +	if (!icd->cd->bsource_list.next || !icd->cd->bsink_list.next) {
First of all please remove the rimage hunk. Secondly maybe we can fix the comment text below too then:
```
	 * have to do it here and eat the resulting memory
	 * leak on error.  Bug-free host drivers won't do
```

2023-06-26 07:31 UTC, bardliao commented
@andyross Can you try below?
git fetch origin
git reset --hard origin/main
Make your change in src/ipc/ipc-helper.c
git add src/ipc/ipc-helper.c
git commit -s
Then push again.

2023-07-03 15:47 UTC, lgirdwood commented
@kv2019i there should be no reason now why rimage is still a submodule with west now ?

2023-07-03 16:15 UTC, marc-hb commented
Yes the plan (detailed in sof/west.yml) is to un-nest rimage (and maybe the toml sub-sub-module) in west.yml.

This being said, there's not really any good reason for rimage changes to appear in a PR totally unrelated to rimage.

2023-07-04 06:26 UTC, lyakh commented
> @kv2019i there should be no reason now why rimage is still a submodule with west now ?

@lrgirdwo do XTOS builds also use west?

2023-07-05 01:14 UTC, marc-hb commented
> Yes the plan (detailed in sof/west.yml)

Ping.

2023-07-05 10:14 UTC, lgirdwood commented
> > Yes the plan (detailed in sof/west.yml)
> 
> Ping.

Sorry, no plan in that file. Lets do this for v2.7.

2023-07-05 20:41 UTC, marc-hb commented
> ~git reset --hard origin/main~

This is incredibly dangerous advice, please don't share stuff like this.  To remove spurious rimage changes from the last commit this is enough:

```
cd sof
west update rimage
git add rimage
git commit -C HEAD --amend
```

This does not affect anything else.

> Sorry, no plan in that sof/west.yml file. 

My bad it was in commit a9680388e55474fd8 and in PR review https://github.com/thesofproject/sof/pull/6398#discussion_r993678758. I added too many comments in `sof/west.yml` (which of course people don't read) but apparently I stopped short there.

One of the complexities is: toml is also a git submodule of rimage. So do we take the opportunity to change that too and break CI's and people's workspaces only once but harder? Or do we spread the pain in two steps?

Lots of build breakages and support calls overhead: fun! Not.

Again none of this explains why any sort of rimage change sneaked in this totally unrelated PR.

2023-07-06 15:48 UTC, lgirdwood commented
> My bad it was in commit [a968038](https://github.com/thesofproject/sof/commit/a9680388e55474fd8e20092d303a89d82cd4f6fe) and in PR review [#6398 (comment)](https://github.com/thesofproject/sof/pull/6398#discussion_r993678758). I added too many comments in `sof/west.yml` (which of course people don't read) but apparently I stopped short there.
> 
> One of the complexities is: toml is also a git submodule of rimage. So do we take the opportunity to change that too and break CI's and people's workspaces only once but harder? Or do we spread the pain in two steps?

Let's break once and do all submodules to west in 1 step. @juimonen lets discuss when you are back.

2023-07-06 17:48 UTC, andyross commented
Rebased.  Looks like the submodule persistance (which I swear was some kind of github misfeature: it wasn't in the patch I was pushing, I promise!) is gone.  I take no position on the west vs. submodule discussion

2023-07-06 19:42 UTC, lgirdwood approved these changes

2023-07-06 20:07 UTC, tmleman approved these changes

2023-07-07 07:53 UTC, lyakh approved these changes

2023-07-07 13:03 UTC, lgirdwood commented
@lrudyX @wszypelt good to merge ? @andyross has no way of checking CI.

2023-07-11 13:29 UTC, merged