topology2: Rename remaining non mixer kcontrols to follow new naming scheme
thesofproject/sof pull request #7870
Opened 2023-06-28 13:58 UTC by jsarha

Rename all remaining kcontrols to follow the new naming scheme that is already used for all mixers.

This commit changes kcontrol names as follows:

cavs-nocodec.conf:
'smart_amp_init' -> 'Main Playback and Port0 smart_amp_init'

cavs-mixin-mixout-hda.conf: name '$ANALOG_CAPTURE_PCM Iir Eq' '4 Main capture Iir Eq' -> 'Analog Capture Iir Eq'

dmic-generic.conf:
'DMIC0 capture Iir Eq' -> 'DMIC0 Capture Iir Eq'

sdw-jack-generic.conf:
'4 Main capture Iir Eq' -> 'Jack In Capture Iir Eq'

2023-06-28 16:00 UTC, ranj063 approved these changes

2023-06-29 12:46 UTC, jsarha commented
(Fixed a typo from the commit message)

2023-06-29 14:31 UTC, kv2019i approved these changes

2023-06-29 15:54 UTC, singalsu requested changes

2023-06-29 15:54 UTC, singalsu commented on tools/topology/topology2/cavs-mixin-mixout-hda.conf
> +					name '$ANALOG_CAPTURE_PCM Iir Eq'
Since doing edits, could you also convert Iir to capitals because it's an acronym, IIR.

2023-06-30 07:46 UTC, singalsu approved these changes

2023-06-30 10:24 UTC, merged