board: intel_adsp_ace15_mtpm: Disable MTL IMR context save for testing
thesofproject/sof pull request #7994
Opened 2023-07-31 09:45 UTC by mengdonglin

Please don't merge.
For testing only, to check if we can avoid issue https://github.com/thesofproject/sof/issues/7969 by disabling IMR context save on MTL.

2023-08-01 02:16 UTC, btian1 reviewed
if not for merge purpose, please change to DRAFT:
![image](https://github.com/thesofproject/sof/assets/17277136/924b7ac5-7be8-440d-bbcb-f85fdc882985)

2023-08-13 00:17 UTC, gkbldcig commented
Can one of the admins verify this patch?

2023-08-30 03:42 UTC, mengdonglin commented
SOF CI TEST

2023-08-30 11:50 UTC, kv2019i approved these changes

2023-08-30 12:54 UTC, lgirdwood approved these changes
@mengdonglin thanks, lets enable when needed by developers.

2023-08-30 13:56 UTC, mengdonglin commented
@kv2019i @lgirdwood @gkbldcig @abonislawski  
- All CI functionality tests are passing now. The previous Jenkins CI failure on system suspend/resume case is an RTC issue, not audio issue.
- Sparse Zephyr / warnings-subset (tgl) and (mtl) are common warnings as other PRs.
- I will check failure with 'Internal Intel CI System/merge/build`

2023-08-30 14:03 UTC, lgirdwood commented
@wszypelt @lrudyX is this a false positive, can someone check ? Thanks !

2023-08-31 02:47 UTC, mengdonglin commented
> @wszypelt @lrudyX is this a false positive, can someone check ? Thanks !

I checked QB CI log: https://quickbuild.igk.intel.com/build/12698102/log It seems building completed successfully for MTL and LNL, but CI cannot trigger smoke test for unknown reason. @wszypelt @lrudyX Can you help check?

2023-08-31 03:47 UTC, mengdonglin commented
@RanderWang @lyakh @kv2019i @abonislawski Can you help evaluate whether setting `CONFIG_ADSP_IMR_CONTEXT_SAVE = n` will break IPC4 multi-core support?

I learned from @RanderWang that cavs2.5 platform needs an extra 'z_init_cpu' to support multi-core. But since in https://github.com/thesofproject/sof/blob/main/zephyr/lib/cpu.c, we don't know if the SoC is MTL or cavs2.5, so we depend on CONFIG_ADSP_IMR_CONTEXT_SAVE to distinguish MTL from cavs2.5: 
9b08ce026 zephyr: cpu: use correct condition to init cpu  (This is the fixup of the 1st commit)
84befa256 zephyr: cpu: init cpu if context save is not support

@RanderWang Can you please confirm MTL doesn't need 'z_init_cpu' no matter CONFIG_ADSP_IMR_CONTEXT_SAVE is set or not?

2023-08-31 05:09 UTC, RanderWang commented
> @RanderWang @lyakh @kv2019i @abonislawski Can you help evaluate whether setting `CONFIG_ADSP_IMR_CONTEXT_SAVE = n` will break IPC4 multi-core support?
> 
> I learned from @RanderWang that cavs2.5 platform needs an extra 'z_init_cpu' to support multi-core. But since in https://github.com/thesofproject/sof/blob/main/zephyr/lib/cpu.c, we don't know if the SoC is MTL or cavs2.5, so we depend on CONFIG_ADSP_IMR_CONTEXT_SAVE to distinguish MTL from cavs2.5: [9b08ce0](https://github.com/thesofproject/sof/commit/9b08ce026ded73d1b84f4c142327d7851ea59f64) zephyr: cpu: use correct condition to init cpu (This is the fixup of the 1st commit) [84befa2](https://github.com/thesofproject/sof/commit/84befa2563f3cf74099f28da91d9bf3ab4031f02) zephyr: cpu: init cpu if context save is not support
> 
> @RanderWang Can you please confirm MTL doesn't need 'z_init_cpu' no matter CONFIG_ADSP_IMR_CONTEXT_SAVE is set or not?

@tmleman MTL doesn't need 'z_init_cpu' for your comment ?

2023-08-31 06:57 UTC, wszypelt commented
@mengdonglin @lgirdwood 
There were problems yesterday, in the internal service, PR is in the queue for retests, there should be correct results soon

2023-08-31 07:30 UTC, lyakh commented
> But since in https://github.com/thesofproject/sof/blob/main/zephyr/lib/cpu.c, we don't know if the SoC is MTL or cavs2.5

sorry, don't understand why we cannot check the DSP version there?

2023-08-31 07:48 UTC, tmleman requested changes
I'm blocking it so it doesn't get merge too early. Additional changes are required.

2023-08-31 11:04 UTC, mengdonglin commented
> Yes, if we want to disable this feature we need to change this condition. Second cpu init will break multicore support on MTL.

@tmleman Thanks for the confirmation! Can you please share more info why second cpu init will break multicore support on MTL (even w/o IMR context save?) but not on cavs2.5 platforms? 

And can we make another PR to decide whether it's MTL or cavs2.5 in https://github.com/thesofproject/sof/blob/main/zephyr/lib/cpu.c#L151, something like this?
--- a/zephyr/lib/cpu.c
+++ b/zephyr/lib/cpu.c
@@ -148,7 +148,7 @@ int cpu_enable_core(int id)
         * initialization. By reinitializing the idle thread, we would overwrite the kernel structs
         * and the idle thread stack.
         */
-       if (!IS_ENABLED(CONFIG_ADSP_IMR_CONTEXT_SAVE) ||
+       if (!defined(CONFIG_ACE) ||
            pm_state_next_get(id)->state == PM_STATE_ACTIVE)
                z_init_cpu(id);
 #endif

CONFIG_ACE is defined for MTL in https://github.com/thesofproject/sof/blob/main/src/platform/Kconfig#L22

@RanderWang @lyakh What do you think?

2023-09-01 01:23 UTC, btian1 commented
is it for LNL PORed feature? if not, I would suggest disable on LNL as well.
intel_adsp_ace20_lnl.conf.

2023-09-01 05:10 UTC, mengdonglin commented
> is it for LNL PORed feature? if not, I would suggest disable on LNL as well. intel_adsp_ace20_lnl.conf.
@btian1 No, it's not POR for LNL. We can sort out the dependencies on MTL at first and then look at LNL.

2023-09-01 06:47 UTC, lyakh commented
> > Yes, if we want to disable this feature we need to change this condition. Second cpu init will break multicore support on MTL.
> 
> @tmleman Thanks for the confirmation! Can you please share more info why second cpu init will break multicore support on MTL (even w/o IMR context save?) but not on cavs2.5 platforms?
> 
> And can we make another PR to decide whether it's MTL or cavs2.5 in https://github.com/thesofproject/sof/blob/main/zephyr/lib/cpu.c#L151, something like this?
> 
> ```
> --- a/zephyr/lib/cpu.c
> +++ b/zephyr/lib/cpu.c
> @@ -148,7 +148,7 @@ int cpu_enable_core(int id)
>          * initialization. By reinitializing the idle thread, we would overwrite the kernel structs
>          * and the idle thread stack.
>          */
> -       if (!IS_ENABLED(CONFIG_ADSP_IMR_CONTEXT_SAVE) ||
> +       if (!defined(CONFIG_ACE) ||
>             pm_state_next_get(id)->state == PM_STATE_ACTIVE)
>                 z_init_cpu(id);
>  #endif
> ```
> 
> CONFIG_ACE is defined for MTL in https://github.com/thesofproject/sof/blob/main/src/platform/Kconfig#L22
> 
> @RanderWang @lyakh What do you think?

if that's what works (and after replacing `defined` with `IS_ENABLED`) - then yes. But I don't understand the logic now: so on MTL we don't need to initialise the idle thread on secondary cores even if not saving to IMR? And on TGL we will re-initialise even if saving to IMR is enabled (if it is available on TGL)?

2023-09-01 08:55 UTC, tmleman commented
> But I don't understand the logic now: so on MTL we don't need to initialise the idle thread on secondary cores even if not saving to IMR?

@mengdonglin @lyakh when you are doing set_dx only for secondary cores no IMR context save takes place. Context save to IMR is done only when we are disabling primary core.

In case of a secondary core, Idle thread stack is still in memory and by calling `z_init_cpu(id)` we would overwrite it.

I discussed this with the team and we would prefer this feature to be disabled only on release branches. I suggest we discuss this further on Tuesday's sync.

2023-09-05 08:00 UTC, lyakh commented
> Context save to IMR is done only when we are disabling primary core.

@tmleman I don't think that was my concern. I just meant that specific change from checking for `CONFIG_ADSP_IMR_CONTEXT_SAVE` to checking for `CONFIG_ACE`. Currently the code means, that
1. if IMR context saving is enabled, then only run `z_init_cpu()` on boot, not when waking up from D3
2. if IMR context saving is disabled, run `z_init_cpu()` both on boot and on wake up.

If we replace the check for `IMR_CONTEXT_SAVE` with a check for `ACE` this would mean:
1. on MTL only run `z_init_cpu()` on boot, not when waking up from D3 - regardless whether saving to IMR is enabled or not
2. on other platforms run `z_init_cpu()` both on boot and on wake up - regardless whether saving to IMR is enabled or not

2023-09-05 08:25 UTC, tmleman commented
> If we replace the check for `IMR_CONTEXT_SAVE` with a check for `ACE` this would mean:
> 
> 1. on MTL only run `z_init_cpu()` on boot, not when waking up from D3 - regardless whether saving to IMR is enabled or not
> 2. on other platforms run `z_init_cpu()` both on boot and on wake up - regardless whether saving to IMR is enabled or not

This is how it should look like.

2023-09-05 10:42 UTC, mengdonglin commented
@lyakh @tmleman Thanks for your comments! I updated the PR with a new commit to only run z_init_cpu() on boot for MTL. Can you please review?

@kv2019i I will make another PR for v2.7 to run stress test.

2023-09-05 11:37 UTC, mengdonglin commented
@kv2019i https://github.com/thesofproject/sof/pull/8156 is submitted to test if we can disable IMR context save for v2.7

2023-09-05 12:24 UTC, lyakh commented
How about something like this for the comment in that file:
```
/*
 * Not every secondary core startup should execute z_init_cpu(). The condition pm_state_next_get(id)->state == 
 * PM_STATE_ACTIVE holds only when the DSP boots for the first time or the DSP resumes from D3 and saving
 * context to IMR isn't used. This is exactly the condition to execute z_init_cpu()  on ACE.
 * However, on other platforms z_init_cpu() should be run always when a secondary core is brought up -
 * regardless of whether it's the first boot and whether or not context saving to IMR is enabled.
 */
```
But please double-check that this is exactly what we need because it sounds strange.

2023-09-06 11:53 UTC, tmleman commented
@mengdonglin Do I understand it correctly? We will disable CONFIG_ADSP_IMR_CONTEXT_SAVE on main branch for purpose of 2.7 release and then re-enable it?

2023-09-06 13:47 UTC, kv2019i requested changes
@tmleman @mengdonglin Let's not merge this for main and instead just do a patch to stable-v2.7

2023-09-15 06:35 UTC, closed without merging