[DNM] POC: ] Direct use of cached / not-cached shared memory alias instead of coherent.h in case of buffers
thesofproject/sof pull request #8013
Opened 2023-08-08 10:10 UTC by marcinszkudlinski

This PR is a quick POC for discussuion https://github.com/thesofproject/sof/issues/8006

There are a lot of TODOs, yet it is ready to be tested 

TODOs:
1) Check if there is no need to extra spinlocks!!!! in case of shared buffers probably - yes because buffer_aquire was also performing as a mutex when in shared mode
2) remove buffer_aquire from the code (in inteligent way, keep point 1 in mind)
3) remove lots of __sparse_cache
4) add __sparse_cache to pointers pointing audio samples buffers

2023-08-16 10:06 UTC, lgirdwood commented
@marcinszkudlinski I assume you will continue with updates for teh TODOs here so that CI will turn all Green ?

2023-09-01 08:02 UTC, lyakh requested changes

2023-09-01 08:28 UTC, closed without merging

2023-09-01 08:28 UTC, marcinszkudlinski commented on src/include/sof/coherent.h
> +	return c;
@lyakh to be removed, I should not use this branch for CI check

2023-09-01 08:31 UTC, marcinszkudlinski commented
Closing this POC as it was accidently used as CI test branch
The PR is almost ready