Sof pawelxd loadable udm
thesofproject/sof pull request #8210
Opened 2023-09-18 05:04 UTC by pjdobrowolski

This is second approach to native sof loadable modules. This time are used zephyr's linker scripts to create separate archive for modules and put them into specific for module sections. After that cmake files, using objcopy put code for up-down-mixer to udm.mod file which is being sign by rimage.

Full process of building module is automated and run by python building scripts:
`xtensa-build-zephyr.py -u mtl -k ../keys/<used_key_for_project>`

2023-09-18 09:12 UTC, marcinszkudlinski commented on zephyr/CMakeLists.txt
> -if(CONFIG_IPC_MAJOR_3)
Conversion of a specific module to loadable should be in separate commit than the loadable module infrastructure

2023-09-18 09:12 UTC, marcinszkudlinski commented on src/audio/up_down_mixer/up_down_mixer.c
> +
DITTO

2023-09-18 09:12 UTC, marcinszkudlinski commented on src/include/sof/audio/module_adapter/library/loadable_processing_module.h
> +typedef int (ModulePackageEntryPoint)(uint32_t costam);
english please ;)

2023-09-18 09:12 UTC, marcinszkudlinski commented on src/include/sof/audio/module_adapter/library/loadable_processing_module.h
> + * #define DECLARE_LOADABLE_MODULE(MODULE, MODULE_FACTORY) \
why commeted out?

2023-09-18 11:41 UTC, marcinszkudlinski commented on zephyr/CMakeLists.txt
> +sof_loadable_library(udm ${SOF_AUDIO_PATH}/up_down_mixer/up_down_mixer.toml)
more meaningful name (updwmix) instead of udm

2023-09-18 11:41 UTC, marcinszkudlinski commented on src/audio/up_down_mixer/up_down_mixer.c
> +extern struct module_interface up_down_mixer_interface;
this forward really needed? Maybe move declaration of sof_module_api_build_info to the end of the file?

2023-09-18 11:41 UTC, marcinszkudlinski commented on src/audio/up_down_mixer/up_down_mixer.c
> +}
indent

2023-09-18 13:20 UTC, lyakh commented on src/include/sof/audio/module_adapter/library/loadable_processing_module.h
> +#include <sof/audio/module_adapter/library/module_api_ver.h>
this doesn't look right. You haven't changed anything in the header, so there's no reason why it now need that additional header

2023-09-18 21:26 UTC, marc-hb requested changes
Thanks but I'm pretty sure the plan for `/lib/firmare/intel/sof/` is to use `--use-platform-subdir` like this:

```
sof/scripts/xtensa-build-zephyr.py --use-platform-subdir mtl


build-sof-staging 
|-- sof 
|   +-- mtl 
|       |-- community 
|       |   +-- sof-mtl.ri 	sha256=401e8360bd1a...
|       |-- sof-mtl.ldc 	sha256=516ad1320ec8...
|       |-- loadable_module1.ri
|       |-- loadable_module2.ri

|       +-- loadable_module3.ri
```

EDIT: maybe `--use-platform-subdir` should be ON by default?

2023-09-18 21:33 UTC, plbossart commented
The 'base fw' and loadable modules can be signed with different keys, so we absolutely do not want them to land in the same directory - the loadable modules MUST be in a key-specific directory.

2023-09-18 21:45 UTC, marc-hb commented
@plbossart you're referring to `--key-type-subdir`.

I was talking about `--use-platform-subdir` which avoids the ugly `sof-{file}-lib.ri` rename hack.

They're not mutually exclusive.

In any case we need **a tiny bit of plain english documentation to be reviewed and approved first**, we don't want people to have to search and read python or kernel code[*] to try and fail to guess the `/lib/firmware/intel/sof/` structure.

This can be as simple as 1-2 pages with the output of a sample "tree" command with a few plain English words around it. Let's stop making the same mistake over and over again:
- https://github.com/thesofproject/linux/pull/4382
- https://github.com/thesofproject/linux/issues/4590

[*] from @plbossart https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/sof/intel/pci-mtl.c#L39

2023-09-20 06:33 UTC, marc-hb commented
> In any case we need a tiny bit of plain english documentation to be reviewed and approved first, we don't want people to have to search and read python or kernel code[*] to try and fail to guess the /lib/firmware/intel/sof/ structure.

Thank you @kv2019i !
- https://github.com/thesofproject/sof-docs/pull/475

So according to that sof-docs PR, the path for loadable modules is: `sof-ipc4-lib/PLAT/community/UUID.bin`

2023-09-20 15:41 UTC, lgirdwood commented on src/audio/up_down_mixer/up_down_mixer.c
> -SOF_MODULE_INIT(up_down_mixer, sys_comp_module_up_down_mixer_interface_init);
Linux Kconfig uses a tristate variable for modules
`y` = builtin
`n` = not built
`m` = module
We shoudl do the same to simplify our Kconfigs.

2023-10-25 09:42 UTC, closed without merging