audio: volume: move volume related config to component config
thesofproject/sof pull request #8211
Opened 2023-09-18 06:15 UTC by btian1

volume related config are missed to move during volume move out from module adapter, move volume kconfig from module adapter folder to component folder.

2023-09-18 08:06 UTC, btian1 commented
@kv2019i , do I need fix the code style check patch problem?

2023-09-18 09:54 UTC, kv2019i approved these changes
No need to change code due to checkpatch warnings, better to move as-is.

2023-09-20 14:34 UTC, lgirdwood reviewed
Content is good, we jsut need to have the Kconfig in the volume directory.

2023-09-20 14:34 UTC, lgirdwood commented on src/audio/Kconfig
> +config COMP_VOLUME
Can we create a Kconfig for each Module i.e. ```src/audio/volume/Kconfig``` and include it from here.

2023-09-20 14:42 UTC, singalsu approved these changes

2023-09-22 11:30 UTC, kv2019i requested changes
Wait a sec, @btian1 commit says we move files but patch diff shows only adding lines. So are the kconfig defs still left to module_adapter?

2023-09-22 14:35 UTC, lgirdwood approved these changes

2023-09-22 14:36 UTC, lgirdwood commented
@btian1 can you check internal CI. Thanks

2023-10-06 08:30 UTC, dnikodem approved these changes

2023-10-06 09:58 UTC, dbaluta approved these changes

2023-10-10 17:58 UTC, merged