[SKIP CI]github action: remove duplicate build for TGL/TGL-H
thesofproject/sof pull request #8261
Opened 2023-09-26 08:17 UTC by aiChaoSONG

At the beginning, we have two build jobs in github action to build IPC3 and IPC4 firmware for TGL/TGL-H.

The PR https://github.com/thesofproject/sof/pull/8048 switches cAVS2.5 configs to use IPC4 by default and empties the cAVS2.5 overlay files. After the change, the xtensa-build-zephyr.py script is building the
same IPC4 firmware with or without '-i IPC4' option. So we have two jobs running different build command but build the same IPC4 firmware.

Recently, commit 5004d0fe1e74 ("zephyr.yml: remove ipc option for zephyr build") removes '-i IPC4' option in github action for TGL/TGL-H IPC4 build. So we have duplicated jobs to build firmware for TGL and TGL-H now.

This patch removes the duplicated build job which previously is used to build IPC3 firmware for TGL/TGL-H.

2023-09-26 12:39 UTC, lgirdwood approved these changes
@keqiaozhang @marc-hb can we proceed and remove the duplication now ?

2023-09-26 16:15 UTC, marc-hb requested changes
Thanks @aiChaoSONG for the cleanup and very detailed commit message.

There are still some obsolete comments like "# Very few IPC3 platforms support IPC4 too.". That's not true any more.

Almost there!

2023-09-27 02:55 UTC, keqiaozhang approved these changes
LGTM

2023-09-27 17:56 UTC, marc-hb approved these changes

2023-09-28 11:45 UTC, tmleman approved these changes

2023-09-28 16:24 UTC, merged