module_adapter: Make free, prepare and reset methods optional
thesofproject/sof pull request #8542
Opened 2023-11-28 14:13 UTC by softwarecki

Simple modules may not need to provide `free`, `prepare` and `reset` functions. To avoid having to provide dummy methods, added an if to check if a module implemented these methods. This will prevent null reference if a module doesn't implement these methods.

2023-11-28 16:23 UTC, ranj063 approved these changes

2023-11-29 02:03 UTC, btian1 approved these changes

2023-11-29 06:16 UTC, pjdobrowolski approved these changes

2023-11-29 09:51 UTC, marcinszkudlinski requested changes
see generic.c
int module_init(struct processing_module *mod, const struct module_interface *interface)

there's a check:

```
	/*check interface, there must be one and only one of processing procedure */
	if (!interface->init || !interface->prepare ||
	    !interface->reset || !interface->free ||
	    (!!interface->process + !!interface->process_audio_stream +
	     !!interface->process_raw_data != 1)) {
		comp_err(dev, "module_init(): comp %d is missing mandatory interfaces",
			 dev_comp_id(dev));
		return -EIO;
	}

```

so free and prepare are still obligatory after your change

2023-11-30 01:50 UTC, btian1 commented on src/audio/up_down_mixer/up_down_mixer.c
> -	.prepare = up_down_mixer_prepare,
can we add comments to interface.h reset/prepare/free and mark these 3 are optional?

2023-11-30 11:07 UTC, tmleman approved these changes

2023-11-30 11:39 UTC, marcinszkudlinski approved these changes

2023-11-30 18:19 UTC, merged