lmdk: dwmix: Add example of loadable down mixer module
thesofproject/sof pull request #8546
Opened 2023-11-28 16:03 UTC by softwarecki

This PR adds the example of down mixer module ported from iadk. Its build as a native loadable sof module.

Ported additional error code definitions from iadk module API. These codes are not unique and their meaning depends on the context / which function returns it.

2023-11-28 16:16 UTC, serhiy-katsyuba-intel approved these changes

2023-11-29 06:39 UTC, pjdobrowolski commented on lmdk/modules/down_mixer/downmixer.c
> +	while (frames_processed < frames_to_process) {
I'm struggling with that frames processing. For an outsider it is a bit complex and without knowing how pipelines work looks like magic. @marcinszkudlinski do we have any docs for that?

2023-11-29 14:38 UTC, lgirdwood requested changes
We need to use the same module code regardless of built-in baseFW or library module.

2023-11-29 14:38 UTC, lgirdwood commented on src/include/module/iadk/adsp_error_code.h
> +#define ADSP_MODULE_CREATION_FAILURE (ADSP_MAX_VALUE + 1)
Wont the max value be changed here if we add more errors ?

2023-11-29 14:38 UTC, lgirdwood commented on lmdk/modules/down_mixer/downmixer.c
> +// SPDX-License-Identifier: BSD-3-Clause
Lets not duplicate the module sources in the code base, we should use the same module code regardless of basefw or module/library build.

2024-01-15 22:43 UTC, softwarecki commented
Closing PR as we need to use the same module code for built-in and loadable module.

2024-01-15 22:43 UTC, closed without merging