copier: store gateway config in copier_data
thesofproject/sof pull request #8558
Opened 2023-11-30 17:55 UTC by plbossart

Calculate actual size of copier module gateway config. Copy and store it in copier_data. It needs to be available even after copier is created e.g. during SET_PIPELINE_STATE IPC when dai_config_dma_channel() is called second time and DMA config is used to assign dma_channel_id value.

2023-11-30 23:28 UTC, fredoh9 commented
I tested multiple times but still seeing `FW reported error: 7 - Unsupported operation requested`
Doesn't seem improve any thing.

2023-12-01 07:25 UTC, RanderWang commented
@plbossart  please check 4cc9d5418b0e9389a8ebdaf81eda13ea2c1d24e2. At first we save the gateway config, but it was deleted
````
+       /*
+        * Don't copy the config_data[] variable size array, we don't need to
+        * store it, it's only used during IPC processing, besides we haven't
+        * allocated space for it, so don't "fix" this!
+        */
````

2023-12-01 09:24 UTC, lyakh requested changes

2023-12-01 09:24 UTC, lyakh commented on src/audio/copier/copier.c
> +				  gtw_cfg_size);
please use `rmalloc()` - you overwrite it completely 5 lines later

2023-12-05 10:04 UTC, iganakov commented
@plbossart @fredoh9 Let me submit a proper fix for DMIC and SSP, we've already tested it internally. SNDW needs additional changes related to blob format which is now different for Linux and Windows

2023-12-05 15:39 UTC, closed without merging