lmdk: fix building system-service modules
thesofproject/sof pull request #8812
Opened 2024-01-29 13:37 UTC by lyakh

System-service modules cannot include Zephyr headers and don't use exported symbols, they link sink_api.c and source_api.c into their images. Disable symbol exporting for them.

2024-01-29 13:43 UTC, kv2019i approved these changes

2024-01-29 13:57 UTC, softwarecki submitted a review, later dismissed

2024-01-29 14:28 UTC, softwarecki requested changes
This PR doesn't solve the problem. The `__SOF_MODULE_SERVICE_BUILD__` symbol is defined only in one example module. We need more universal solution.

2024-01-29 16:44 UTC, lyakh commented
> This PR doesn't solve the problem. The `__SOF_MODULE_SERVICE_BUILD__` symbol is defined only in one example module. We need more universal solution.

@softwarecki you don't use it when building LMDK modules? Ok, I thought you did. Is there anything that you do define for all system-service modules?

2024-01-30 08:18 UTC, softwarecki commented
> Ok, I thought you did. Is there anything that you do define for all system-service modules?

We don't define it in our examples of lmdk modules. Please check files in `lmdk/cmake` or use some definition used by llmodules.

2024-01-31 14:13 UTC, lgirdwood commented
@softwarecki btw, why does system services build and link to a base FW file (e.fg the source/sink API) ? Shouldn't these be unresolved in the library and then be resolved when the library is loaded ?

2024-01-31 16:52 UTC, marc-hb commented on src/module/audio/sink_api.c
> +#endif
I find this not obvious at all so I think most the commit message should be moved to a comment here.

2024-02-02 16:31 UTC, softwarecki approved these changes
This is a very surprising solution, but it works so I accept it.

2024-02-05 07:26 UTC, lyakh commented
I think we can safely state, that this PR cannot be a reason for all the CI failures:
- cAVS suspend-resume https://sof-ci.01.org/sofpr/PR8812/build2551/devicetest/index.html
- ACE multiple pipelines and multiple pause-resume with nocodec https://sof-ci.01.org/sofpr/PR8812/build2550/devicetest/index.html
- Broken fuzzing is a recent regression
- Failing zmain builds are a known Zephyr breakage too

2024-02-05 20:55 UTC, marc-hb commented
> This is a very surprising solution, but it works so I accept it.

Moreover it's short, well documented and self-contained in only 2 places to change if needed in the future. So very low technical debt if any!

2024-02-06 06:09 UTC, pjdobrowolski approved these changes

2024-02-06 07:50 UTC, merged