config L3_HEAP: add missing "ACE" dependency
thesofproject/sof pull request #8827
Opened 2024-02-02 06:27 UTC by marc-hb

In Zephyr, adsp_memory.h is available only for ace15 and ace20 right now.

Don't allow configuration that can't possible compile.

2024-02-02 10:10 UTC, lyakh requested changes
Something isn't right here, at least in the commit description: I see adsp_memory.h included in src/platform/tigerlake/include/platform/lib/memory.h.
Could you clarify which files, enabled by `L3_HEAP` include adsp_memory.h? In my local (almost current) tree I only see adsp_memory.h included in src/ipc/ipc4/helper.c, in zephyr/include/sof/lib/regions_mm.h and in src/platform/${platform}/include/platform/lib/memory.h

2024-02-02 15:56 UTC, marc-hb commented
> Could you clarify which files, enabled by L3_HEAP include adsp_memory.h? 

Sorry I should have written something like: "L3_HEAP is currently available in adsp_memory.h only for ace15 and ace20". Would that work for you?

2024-02-05 14:20 UTC, lgirdwood commented
Btw, is there no prefix on ```ACE``` ? It seems like this will collide at some point. What does Zephyr use here for this IP version ?

2024-02-28 03:03 UTC, marc-hb commented
The PUBLISH step failed as usual today but all the tests passed in https://sof-ci.01.org/sof-pr-viewer/#/build/PR8827/build13641692

2024-02-28 15:35 UTC, lgirdwood approved these changes
Ok, we need to revisit all the Kconfig and API common names we have and prefix them for v2.110.

2024-03-05 09:49 UTC, merged