logger: convert: fix variable type for negative value
thesofproject/sof pull request #8839
Opened 2024-02-06 12:27 UTC by abonislawski

This will fix scan tool reported issue:

time_precision variable can be used as -1

```
case 'f':
        config.time_precision = atoi(optarg);
   	if (config.time_precision < 0) {

case 'g':
   	config.time_precision = -1;
```

Fixes commit ff9343aa4a59

2024-02-06 18:20 UTC, marc-hb requested changes
@dbaluta can you please get ready to test (future versions of) this with the GCC 13 compiler that produced the warning reported in #8778?

2024-02-06 18:20 UTC, marc-hb commented on tools/logger/convert.c
> +static int8_t timestamp_width(int8_t precision)
Please change the `config->precision` but do not change the prototype of `timestamp_width()`. It's not designed to deal with negative numbers at all and every invocation of it makes sure of that.

2024-02-07 09:49 UTC, dbaluta approved these changes

2024-02-12 08:34 UTC, marc-hb approved these changes

2024-02-13 17:18 UTC, lgirdwood approved these changes

2024-02-13 17:20 UTC, merged