topology2: pcm_caps: Remove defaults for rate_min/rate_max
thesofproject/sof pull request #9017
Opened 2024-04-09 18:00 UTC by ranj063

Use 'rates' instead to specify that 48K is the default supported rate.

2024-04-09 19:28 UTC, plbossart approved these changes

2024-04-10 06:19 UTC, ujfalusi approved these changes

2024-04-10 06:27 UTC, kv2019i approved these changes

2024-04-10 06:28 UTC, kv2019i requested changes
Tests failing on all platforms:
https://sof-ci.01.org/sofpr/PR9017/build3818/devicetest/index.html

2024-04-10 06:32 UTC, ujfalusi commented
> Tests failing on all platforms: https://sof-ci.01.org/sofpr/PR9017/build3818/devicetest/index.html

and no dmesg

2024-04-10 06:44 UTC, ujfalusi commented
Something is wrong with CI, in the failing cases it tries to use 0Hz rate:
`aplay   -Dhw:0,0 -r 0 -c 2 -f S16_LE -d 10 /dev/zero -v -q`
`arecord   -Dhw:0,0 -r 0 -c 2 -f S16_LE -d 3 /dev/null -v -q`

resulting `bad speed value 0`

2024-04-10 07:39 UTC, ujfalusi commented
> Something is wrong with CI, in the failing cases it tries to use 0Hz rate: `aplay -Dhw:0,0 -r 0 -c 2 -f S16_LE -d 10 /dev/zero -v -q` `arecord -Dhw:0,0 -r 0 -c 2 -f S16_LE -d 3 /dev/null -v -q`
> 
> resulting `bad speed value 0`

The reason is that the sof-test is parsing the topology and uses rate_min, rate_max which is now 0 if it is not set explicitly. The same issue with #9004 (converted back to draft).
I have not looked at the sof-test that closely, but tools/sof-tplgreader.py loadFile() only reads rate_min, rate_max

2024-04-10 09:24 UTC, ujfalusi commented
```
PIPELINE_LST[3]="pcm=HDA Analog;id=0;type=playback;cap_name=Analog Playback;eq=eqiir.2.1 eqfir.2.1;fmts=S16_LE S24_LE S32_LE;fmt=S16_LE;rate_min=48000;rate_max=48000;ch_min=2;ch_max=2;rate=48000;channel=2;dev=hw:0,0;snd=/dev/snd/pcmC0D0p;"
```
vs
```
PIPELINE_LST[3]="pcm=HDA Analog;id=0;type=playback;cap_name=Analog Playback;eq=eqiir.2.1 eqfir.2.1;fmts=S16_LE S24_LE S32_LE;fmt=S16_LE;rate_min=0;rate_max=0;ch_min=2;ch_max=2;rate=0;channel=2;dev=hw:0,0;snd=/dev/snd/pcmC0D0p;"
```

2024-04-10 13:47 UTC, plbossart commented
that's a spectacular dependency on sof-test parsing of topology. Oh well. Glad it was caught, our CI results just improved over the last week, probably not wise to run CI into the ground again...

2024-04-10 15:01 UTC, ranj063 commented
> > Something is wrong with CI, in the failing cases it tries to use 0Hz rate: `aplay -Dhw:0,0 -r 0 -c 2 -f S16_LE -d 10 /dev/zero -v -q` `arecord -Dhw:0,0 -r 0 -c 2 -f S16_LE -d 3 /dev/null -v -q`
> > resulting `bad speed value 0`
> 
> The reason is that the sof-test is parsing the topology and uses rate_min, rate_max which is now 0 if it is not set explicitly. The same issue with #9004 (converted back to draft). I have not looked at the sof-test that closely, but tools/sof-tplgreader.py loadFile() only reads rate_min, rate_max

@ujfalusi yes softest relies on rate min/max. I have a fix coming soon

2024-04-17 00:21 UTC, fredoh9 commented
SOFCI TEST

2024-04-17 00:50 UTC, fredoh9 commented
After https://github.com/thesofproject/sof-test/pull/1174 merged, I re-triggered the device test. It looks good so far.

2024-04-17 06:15 UTC, kv2019i approved these changes

2024-04-17 06:15 UTC, merged

2024-04-22 16:30 UTC, marc-hb commented
Another problem with this:
- #9068