Part 1 of #9013
thesofproject/sof pull request #9024
Opened 2024-04-10 14:47 UTC by lyakh

a split up of https://github.com/thesofproject/sof/pull/9013/commits/fb6286dbfc48e3f8d12dc99d5ac982cfd4d16124 . Can be merged independently since this code isn't used yet, but to work it'll need the rest of #9013, including a Zephyr update, which is now available as #9019

2024-04-10 21:50 UTC, marc-hb commented
Lots of build failures in https://sof-ci.01.org/sofpr/PR9024/build3859/build/index.html and https://github.com/thesofproject/sof/actions/runs/8633265152/job/23665921289?pr=9024

2024-04-12 14:12 UTC, lyakh commented
The fuzzer failure https://github.com/thesofproject/sof/actions/runs/8657935406/job/23740891264?pr=9024 is curious, but I'm rather sure it's unrelated. The whole library management depends on IPC4, and all these run-time changes only affect it. The only potentially relevant for IPC3 change is the change for rimage, which makes it less sensitive to invalid ELF files, but that's a build-time change, and as far as I understand the fuzzer doesn't attempt invalid builds.

2024-04-12 23:36 UTC, marc-hb commented
@andyross  I downloaded the input "crash" file (attached again here for convenience), debugged it and noticed something that looks bad.

[IPC3-fuzz9024-logs.zip](https://github.com/thesofproject/sof/files/14964498/IPC3-fuzz9024-logs.zip)

The IPC3 `mailbox_validate()` function returns NULL when the `hdr` is malformed. I'm not sure what the "real" IPC3 code does with that NULL (I didn't look) but what you did in commit c50eddce1f81b and `src/platform/posix/ipc.c` does not look correct: you keep going like nothing happened?!

Most of the time it surprisingly does not crash (lack of defensive programming?) but it's not too surprising if that crashes from time to time - as it just did in https://github.com/thesofproject/sof/actions/runs/8657935406/job/23740891264?pr=9024

2024-04-12 23:39 UTC, marc-hb commented
>  I'm not sure what the "real" IPC3 code does with that NULL (I didn't look) 

Actually, AMD, IMX and mediatek keep trying to process that NULL like posix/ipc.c does. Not sure about Intel

2024-04-13 00:04 UTC, andyross commented
To clarify: you're seeing a NULL header passed to ipc_cmd() because of an invalid parse (an expected failure, this is fuzzing aftera all) that happens in mailbox_validate()?   I'll admit I'm not sure exactly what the specified behavior there is.   The POSIX code was written to try to duplicate the original scheme, but... yeah, it's pretty confusing how this is intended to work.  There's a big comment in posix/ipc.c trying to explain what I think is happening.

FWIW, src/ipc/ipc-zephyr.c looks broadly similar: I see ipc_compact_read_msg() returning an uninspected outptut of mailbox_validate(), which ends up in ipc_platform_do_cmd() where it's passed straight to ipc_cmd().  Basically the same code path?

My gut says this is a core issue and that ipc_cmd() is expected to be tolerant of NULLs at runtime, I guess?  But we could absolutely disallow it and check before the call too.

2024-04-13 00:35 UTC, marc-hb commented
> My gut says this is a core issue and that ipc_cmd() is expected to be tolerant of NULLs at runtime, I guess?

I think you must be right.

Now I suspect the timeout logic in the fuzzing framework. I suspect it because the failing run lasted exactly as long as the passing runs.

I ran it a second time and it passed https://github.com/thesofproject/sof/actions/runs/8657935406/job/23776321942

I also run the crash input locally a million times and no problem were ever found.

Let's ignore this. We still have the .zip attached if we ever need to get back to it.

2024-04-15 12:44 UTC, lgirdwood approved these changes

2024-04-15 20:45 UTC, marc-hb commented on src/samples/audio/smart_amp_llext/CMakeLists.txt
> +if("${ZEPHYR_TOOLCHAIN_VARIANT}" STREQUAL "zephyr")
Add a "FIXME: replace this hack with new `add_llext_target()` in Zephyr"

2024-04-15 20:51 UTC, marc-hb requested changes
https://pylint.pycqa.org/en/latest/user_guide/messages/warning/broad-except.html

2024-04-15 20:51 UTC, marc-hb commented on src/library_manager/llext_manager.c
> +	size_t mod_size = desc->header.preload_page_count * PAGE_SZ - 0x8000;
Magic number

2024-04-15 20:51 UTC, marc-hb commented on scripts/llext_link_helper.py
> +		except:
No, just catch the exception you're expecting. Copy/paste its name from the stack trace, it should take seconds. Also, use `pylint`.

https://pylint.pycqa.org/en/latest/user_guide/messages/warning/broad-exception-caught.html

2024-04-15 20:51 UTC, marc-hb commented on scripts/llext_link_helper.py
> +import os
Where is this used in this commit?

2024-04-16 13:35 UTC, lgirdwood commented
> https://pylint.pycqa.org/en/latest/user_guide/messages/warning/broad-except.html

@marc-hb these are all minor improvements, the main benefit is getting this used and @lyakh can circle back and do the updates when he's back from vacation.  I'm going to merge so we can start looking at the next steps for testing, CI and signing.

2024-04-16 14:03 UTC, kv2019i approved these changes
The lllext_link_helpe.py points are valid, but otherwise this is ready to merge.

2024-04-16 14:30 UTC, merged

2024-04-16 15:28 UTC, marc-hb commented
Actually, "broad-except" is not a minor warning and this is the type of coding mistakes that gets fixed only if/when being hit hard by it and wasting a lot of time. Same as ignoring errors in C.