Audio: Optimize division by speed of sound using fixed-point reciprocal
thesofproject/sof pull request #9160
Opened 2024-05-23 08:34 UTC by ShriramShastry

This commit optimizes the division by the speed of sound in the `theoretical_time_differences` function. By precomputing the fixed-point reciprocal of the speed of sound, we eliminate the need for a costly division operation in each iteration.

2024-05-23 13:46 UTC, ShriramShastry commented
SOFCI

2024-05-23 16:13 UTC, singalsu commented
Thanks @ShriramShastry , this saves 1.4 MCPS with 4ch beamformer in TGL platform. I'll review this PR later.

2024-05-29 10:04 UTC, lgirdwood approved these changes
Nice one @ShriramShastry !

2024-06-11 15:32 UTC, ShriramShastry commented on src/audio/tdfb/tdfb_direction.c
> +			(int32_t)((((int64_t)delta_d) * RECIPROCAL_SPEED_OF_SOUND_Q8) >> 8);
Done !! There is no noticeable performance degradation..

Thanks

2024-06-13 15:49 UTC, ShriramShastry commented on src/include/sof/math/numbers.h
> +#define RECIPROCAL_SPEED_OF_SOUND_Q8 24457 /* Precomputed inverse in Q8 */
Yup, It is Q9.23. 

```
>> speedofsound = 343

speedofsound =

   343

F = fimath('OverflowAction','Saturate','RoundingMethod','Convergent');

x = fi(1/speedofsound,1,32,39); 
y = fi(bitsll(1,8),1,32,22);
z = mpy(F,x,y);
a = fi(z, 1,32, 23);

b = fi(2^23,1,32,7);
invsnd = fi(mpy(F,a , b),1,32,8)

invsnd = 

     6260885

          DataTypeMode: Fixed-point: binary point scaling
            Signedness: Signed
            WordLength: 32
        FractionLength: 8
```

2024-06-17 13:55 UTC, singalsu requested changes
The code works correctly, checked with direction_test.m but need to reject due to mistakes in comments, sorry! Can you please fix. This is a quick approve after done.

2024-06-17 13:55 UTC, singalsu commented on src/audio/tdfb/tdfb_direction.c
> -	if (!cd->direction_updates)
Good catch, thank you!

2024-06-17 13:55 UTC, singalsu commented on src/audio/tdfb/tdfb_direction.c
> +		 * right-shift the result by 12 bits to preserve the Q4.12 format.
The comment "right-shift the result by 12 bits to preserve the Q4.12 format" is not correct. The timediff_iter[] is Q1.31.  E.g. "right-shift the result by 12 bits for Q1.31 format".

2024-06-17 13:55 UTC, singalsu commented on src/include/sof/math/numbers.h
> +#define RECIPROCAL_SPEED_OF_SOUND_Q31 6260885 /* Q9.23 */
Wrong comment, it's Q1.31.

2024-06-17 14:37 UTC, singalsu approved these changes

2024-06-20 11:59 UTC, kv2019i commented
Ready to merge, pending the mandatory CI to pass.

2024-06-25 15:46 UTC, lgirdwood commented
@wszypelt looks like CI has been pending a while. Good to merge ?

2024-06-26 13:16 UTC, wszypelt commented
@lgirdwood good to merge :)

2024-06-26 13:38 UTC, merged