topology2: common: pcm_caps: Change the periods_max from 1024 to 255
thesofproject/sof pull request #9204
Opened 2024-06-06 14:52 UTC by ujfalusi

HDA host DMA has limitation on the number of BDL entries which translates to number of periods, this limit is 255.

The Chrome ALSA compliance test is eagerly try to use as many periods as it can which exceeds the BDL limit and the stream cannot be started.

Fixes: b3a6d1c5708e ("topology2: common: pcm_caps: Increase periods_max from 16 to 1024")

2024-06-06 14:52 UTC, ujfalusi commented
@kv2019i, this is a candidate to backport for stable branches.

2024-06-06 15:23 UTC, yongzhi1 approved these changes

2024-06-06 15:28 UTC, plbossart requested changes

2024-06-06 15:28 UTC, plbossart commented on tools/topology/topology2/include/common/pcm_caps.conf
> +	periods_max		255
off-by-one, the spec says 256.

2024-06-07 05:37 UTC, ujfalusi commented
Changes since v1:
- fixed off by one (255 -> 256 max periods)

2024-06-07 16:00 UTC, lgirdwood approved these changes

2024-06-10 10:17 UTC, lgirdwood commented
@plbossart good now ?

2024-06-13 11:21 UTC, kv2019i approved these changes

2024-06-13 12:37 UTC, lgirdwood commented
SOFCI TEST

2024-06-14 08:01 UTC, plbossart approved these changes

2024-06-14 08:03 UTC, merged