cpu: multiprocessing: add new broadcast rutine
thesofproject/sof pull request #9217
Opened 2024-06-10 13:31 UTC by pjdobrowolski

Platforms that support IPIs allow them to be broadcast via the
new arch_sched_broadcast_ipi() routine (replacing arch_sched_ipi()).
Those that also allow IPIs to be directed to specific CPUs may
use arch_sched_directed_ipi() to do so.

2024-06-11 09:45 UTC, tmleman requested changes
I recommend combining the three commits into a single commit to ensure that each commit in the repository is buildable and maintains git bisect functionality.

2024-06-11 11:22 UTC, tmleman requested changes

2024-06-11 11:22 UTC, tmleman commented on zephyr/wrapper.c
>  {
Incorrect indentations in the code. You should use tabs with a size of 8 spaces.

2024-06-11 11:46 UTC, tmleman approved these changes
For me, it's already OK. The only thing I would change if I had time is the description. It shows that it's the result of a squash. My proposal is:
```txt
west.yml: update Zephyr to 2efc447c1b4

This commit updates the SOF codebase to align with recent changes in the Zephyr project. It includes the following changes:

- Updates the Zephyr project to the revision `2efc447c1b41efd23447ea180731d673114f06d8`.
- Introduces a new routine `arch_sched_broadcast_ipi()` to replace the deprecated `arch_sched_ipi()` for broadcasting IPIs.
- Replaces the deprecated `z_arch_esf_t` struct with the new `struct arch_esf` in the `k_sys_fatal_error_handler` function.
```

2024-06-11 12:40 UTC, gbernatxintel approved these changes

2024-06-11 13:25 UTC, lgirdwood approved these changes

2024-06-11 13:27 UTC, lgirdwood commented
@pjdobrowolski good stuff, CI mostly green. One build failure for TGL though (I suspect we need a copy and paste change from MTL to TGL)
https://sof-ci.01.org/sofpr/PR9217/build5353/build/firmware_community/tgl.log

2024-06-11 13:35 UTC, marcinszkudlinski approved these changes

2024-06-12 06:33 UTC, lyakh commented
This duplicates a part of #9199. I was OoO for the last two days, so couldn't update it to account for the now merged https://github.com/zephyrproject-rtos/zephyr/pull/73856 . I'll update #9199 in a couple of minutes

2024-06-12 10:08 UTC, lgirdwood commented
ok, I've merged #9199 since it had the build fix for TGL too. Thanks all, think we are back to health again.

2024-06-12 10:14 UTC, closed without merging