copier: Add bind function to configure source/sink buffers params
thesofproject/sof pull request #9276
Opened 2024-07-02 13:36 UTC by softwarecki

Setting the source/sink buffers parameters in the copier_update_params function is not sufficient. If a sink buffer is attached during copier operation, the module will not set buffers parameters. Move the buffer parameter configurations to the new copier_bind bind function. Delete the sink buffers configurations from the copier_module_copy function. There is no need to configure sink buffers parameters on each copy. We are assured that they were configured at the time of bind.

Fixes: #9123

2024-07-02 14:24 UTC, iganakov reviewed
Looks like duplicate of
https://github.com/thesofproject/sof/pull/9197 copier: update buffer format on bind

2024-07-02 15:38 UTC, kv2019i approved these changes

2024-07-03 06:47 UTC, iganakov requested changes

2024-07-03 06:47 UTC, iganakov commented on src/audio/copier/copier.c
> +			uint32_t id = IPC4_SINK_QUEUE_ID(buf_get_id(buffer));
There is a wrong macro used to retrieve sink id. Buffer id is created by `IPC4_COMP_ID(src_queue, dst_queue)`, in such a case `IPC4_SINK_QUEUE_ID` will return `dst_queue` id and not the `src_queue` id which we are interested in. Thus, you won't be able to update corresponding copier sink for sink num > 1.
`IPC4_SRC_QUEUE_ID()` should be used instead

2024-07-03 07:32 UTC, lyakh commented on src/audio/copier/copier.c
> +			buffer = list_first_item(&dev->bsource_list, struct comp_buffer, sink_list);
copiers cannot have multiple sources? But yes, it's a copy of the original code

2024-07-03 11:45 UTC, tmleman approved these changes

2024-07-03 14:17 UTC, iganakov reviewed
Driver sends SET_SINK_FORMAT IPC to configure copier module sink processing parameters before bind when there is no processing buffer between connected components. Please also remove sink buffer's update from `copier_set_sink_fmt()`. 
It would be nice to simplify copier bind operation, please find my suggestions below

2024-07-03 14:17 UTC, iganakov commented on src/audio/copier/copier.c
> +	src_id = IPC4_COMP_ID(bu->primary.r.module_id, bu->primary.r.instance_id);
I think the whole function could be simplified. 
```suggestion
	uint32_t src_queue_id = bu->extension.r.src_queue;
	uint32_t dst_id = IPC4_COMP_ID(bu->extension.r.dst_module_id,
				       bu->extension.r.dst_instance_id);
	if (dev->ipc_config.id == dst_id)
		return 0;

	/* Update corresponding sink buffer format */
	list_for_item(sink_list, &dev->bsink_list) {
		int sink_id;

		sink = container_of(sink_list, struct comp_buffer, source_list);
		sink_id = IPC4_SRC_QUEUE_ID(buf_get_id(sink));
		if (sink_id == src_queue_id) {
			ipc4_update_buffer_format(sink, &cd->out_fmt[sink_id]);
			return 0;
		}
	}

	comp_err(dev, "No sink buffer found for src_queue=%d", src_queue_id);
	return -ENODEV;
```

2024-07-05 07:40 UTC, iganakov approved these changes
Looks good to me

2024-07-05 07:42 UTC, dnikodem approved these changes

2024-07-05 07:43 UTC, gbernatxintel approved these changes

2024-07-05 13:37 UTC, lgirdwood commented
@softwarecki can you confirm if internal CI is good to merge ? Seeing some red on Jenkins, lets rerun to be sure.

2024-07-05 13:37 UTC, lgirdwood commented
SOFCI TEST

2024-07-08 14:42 UTC, softwarecki commented
I restored the code that sets the sink parameters in the `copier_update_params` function. Parameters set in the `bind` function can be overwritten by the `comp_verify_params` function called by `ipc4_pipeline_prepare` -> `ipc4_pipeline_params`.

I look forward to the new CI results...

2024-07-09 11:31 UTC, lgirdwood commented
> I restored the code that sets the sink parameters in the `copier_update_params` function. Parameters set in the `bind` function can be overwritten by the `comp_verify_params` function called by `ipc4_pipeline_prepare` -> `ipc4_pipeline_params`.
> 
> I look forward to the new CI results...

All look good except for LNL SDW, can you check ? I would expect copier changes to fail on all test (not just SDW), we can rerun again if you think its DUT or testing infra related.

2024-07-09 13:39 UTC, kv2019i commented
@lgirdwood wrote:
> All look good except for LNL SDW, can you check ? I would expect copier changes to fail on all test (not just SDW), we can rerun again if you think its DUT or testing infra related.

The LNL SDW is caused by this: https://github.com/thesofproject/linux/issues/5098

2024-07-11 07:07 UTC, marcinszkudlinski approved these changes

2024-07-12 08:09 UTC, softwarecki commented
SOFCI TEST

2024-07-12 22:35 UTC, marc-hb commented
The pause/resume failure in https://sof-ci.01.org/sofpr/PR9276/build6454/devicetest/index.html?model=LNLM_RVP_HDA&testcase=check-pause-resume-capture-100 is addressed by https://github.com/thesofproject/sof-test/pull/1218, please review.

2024-07-15 13:31 UTC, softwarecki commented
SOFCI TEST

2024-07-15 15:54 UTC, merged