topology2: fix LNL RT712 and RT722 HDMI dailink index
thesofproject/sof pull request #9302
Opened 2024-07-15 08:19 UTC by plbossart

There's no amp feedback so the indices are off-by-one compared to the default. This should be the index map on these boards:

0: headphone
1: headset
2: speakers
3: mic
4..6: HDMI

Closes: https://github.com/thesofproject/sof/issues/9295

2024-07-16 09:55 UTC, wszypelt commented
@plbossart Hi, in internal intel CI system, cmake tools failed at syntax error. I think this can be a issue:
![image](https://github.com/user-attachments/assets/8cdf61a7-adbb-4972-a91f-34cdde5e51bd)

2024-07-16 13:28 UTC, kv2019i approved these changes

2024-07-16 13:48 UTC, bardliao commented
@plbossart We have `#define SOC_SDW_DMIC_DAI_ID               4`, I think the mic be id is expected to be 4 no matter amp feedback is there or not. Maybe we should check what is wrong on kernel side?

2024-07-16 14:21 UTC, plbossart commented
moved back to draft, it seems the BIOS settings are not correct?

2024-07-16 14:21 UTC, bardliao requested changes
I don't think this will fix #9295. Please see the dmesg log below
```
[    5.453986] snd_soc_sof_sdw:sof_card_dai_links_create: sof_sdw sof_sdw: sdw 4, ssp 0, dmic 2, hdmi 0, bt: 0
[    5.453989] snd_soc_sdw_utils:asoc_sdw_init_dai_link: sof_sdw sof_sdw: create dai link SDW0-Playback-SimpleJack, id 0
[    5.454027] snd_soc_sdw_utils:asoc_sdw_init_dai_link: sof_sdw sof_sdw: create dai link SDW0-Capture-SimpleJack, id 1
[    5.454030] snd_soc_sdw_utils:asoc_sdw_init_dai_link: sof_sdw sof_sdw: create dai link SDW0-Playback-SmartAmp, id 2
[    5.454032] snd_soc_sdw_utils:asoc_sdw_init_dai_link: sof_sdw sof_sdw: create dai link SDW0-Capture-SmartMic, id 4
[    5.454033] snd_soc_sdw_utils:asoc_sdw_init_dai_link: sof_sdw sof_sdw: create dai link dmic01, id 5
[    5.454035] snd_soc_sdw_utils:asoc_sdw_init_dai_link: sof_sdw sof_sdw: create dai link dmic16k, id 6
[    5.454037] snd_soc_sdw_utils:asoc_sdw_init_dai_link: sof_sdw sof_sdw: create dai link iDisp1, id 7
[    5.454038] snd_soc_sdw_utils:asoc_sdw_init_dai_link: sof_sdw sof_sdw: create dai link iDisp2, id 8
[    5.454040] snd_soc_sdw_utils:asoc_sdw_init_dai_link: sof_sdw sof_sdw: create dai link iDisp3, id 9
```

2024-07-17 09:22 UTC, plbossart commented
this PR is not needed, closing

2024-07-17 09:22 UTC, closed without merging