audio: selector: fix init pointers
thesofproject/sof pull request #9473
Opened 2024-09-13 18:27 UTC by cujomalainey

Selector has been broken since its last init migration as the memcpy passes in the first byte of data rather than the pointer to the data.

Fixes: 141efbd7b0 ("ipc4: convert selector to use the new module interface")
Fixes: oss-fuzz:59343

2024-09-13 18:28 UTC, cujomalainey commented
This also suggests that our stub testing could go a bit further and actually initialize the components.

2024-09-16 07:46 UTC, lyakh requested changes
I think the current code is correct. The commit is copying an address of the `.data` member of `struct ipc_process`, which doesn't look correct to me

2024-09-17 06:41 UTC, lyakh commented
> Hmm, actually the changes appear to resolve to the same value in gcc and clang on macos, but when I was testing in the fuzzer environment (clang) on my linux machine I was getting values [0,255] which suggested it was dereferencing the pointer.

@cujomalainey I cannot imaging how this can be correct. In your test code - yes, it's correct, because you have an **array** there. However `.data` in https://github.com/thesofproject/sof/blob/3c0eb1aac4b215bcd814459fa3c7ba594f697e57/src/include/sof/audio/ipc-config.h#L141 is a **pointer**. In `int x[2];` `x` and `&x` will have the same value. But in `int *x = &i;` they will have different values. `x` will return its contents, i.e. address of `i`, whereas `&x` will return address of the `x` variable. Same when that pointer is inside a structure.

2024-09-17 16:46 UTC, cujomalainey commented
ah yes you are right i had the types confused, hmm this is interesting as I was certain I traced the path to correct for making sure data was valid. Thanks for catching the error. I will have to debug this further. Let me know if you want to take a look, i can give you the test case.

2024-09-17 16:46 UTC, closed without merging