Audio: Copier: Use SOF_DIV_ROUND_UP() instead of ROUND_UP()
thesofproject/sof pull request #9579
Opened 2024-10-15 10:46 UTC by singalsu

The ROUND_UP() is provided by Zephyr headers and can't be used in testbench (IPC4) build.

2024-10-15 13:52 UTC, lgirdwood approved these changes

2024-10-15 14:50 UTC, jsarha submitted a review, later dismissed

2024-10-16 06:19 UTC, abonislawski approved these changes

2024-10-16 07:03 UTC, lyakh requested changes
these are two quite different macros. One rounds up, another one divides, rounding up. The former can however be used here by removing the `>> 2` shift

2024-10-16 07:25 UTC, singalsu commented
Closing, sorry!

2024-10-16 08:22 UTC, singalsu commented
Thanks @lyakh for avoiding me to break totally the code. Fixed now as you suggested.

2024-10-17 06:07 UTC, lyakh approved these changes

2024-10-17 07:57 UTC, merged